const preguntas = [
{ pregunta: "¿Qué protege la acción protectora por muerte y supervivencia?", respuesta: "La pérdida de ingresos por fallecimiento del causante." },
{ pregunta: "¿Qué contingencias cubre la protección por muerte y supervivencia?", respuesta: "Contingencias comunes y profesionales." },
{ pregunta: "¿Qué prestación sustituye a la antigua orfandad absoluta?", respuesta: "La pensión en favor de familiares." },
{ pregunta: "¿Qué prestación corresponde al cónyuge superviviente?", respuesta: "La pensión de viudedad." },
{ pregunta: "¿Qué prestación corresponde a los hijos del causante?", respuesta: "La pensión de orfandad." },
{ pregunta: "¿Qué prestación cubre a otros familiares convivientes?", respuesta: "La pensión en favor de familiares." },
{ pregunta: "¿Qué prestación cubre los gastos del sepelio?", respuesta: "El auxilio por defunción." },
{ pregunta: "¿Cuál es la cuantía del auxilio por defunción?", respuesta: "30,05 euros." },
{ pregunta: "¿Quién tiene preferencia para cobrar el auxilio por defunción?", respuesta: "El cónyuge o pareja de hecho." },
{ pregunta: "¿Qué porcentaje general corresponde a la viudedad?", respuesta: "52% de la base reguladora." },

{ pregunta: "¿Qué porcentaje de viudedad corresponde a mayores de 65 sin ingresos?", respuesta: "60%." },
{ pregunta: "¿Qué porcentaje de viudedad corresponde con cargas familiares y bajos ingresos?", respuesta: "70%." },
{ pregunta: "¿Qué porcentaje corresponde a cada huérfano?", respuesta: "20% de la base reguladora." },
{ pregunta: "¿Cuál es el límite conjunto de viudedad y orfandad?", respuesta: "100% de la base reguladora." },
{ pregunta: "¿Cuál es la edad máxima general para cobrar orfandad?", respuesta: "21 años." },
{ pregunta: "¿Hasta qué edad puede cobrarse orfandad si no se trabaja?", respuesta: "25 años." },
{ pregunta: "¿Qué ocurre si el huérfano tiene discapacidad del 33% antes de los 21/25?", respuesta: "La pensión es vitalicia." },
{ pregunta: "¿Qué cotización se exige para contingencias comunes?", respuesta: "500 días en los últimos 5 años." },
{ pregunta: "¿Se exige cotización en contingencias profesionales?", respuesta: "No." },
{ pregunta: "¿Qué es la base reguladora?", respuesta: "El promedio de bases del causante según la contingencia." },

{ pregunta: "¿Puede cobrar viudedad una pareja de hecho?", respuesta: "Sí, si cumple requisitos legales." },
{ pregunta: "¿Cuántos años de convivencia se exigen a la pareja de hecho?", respuesta: "5 años." },
{ pregunta: "¿Qué documento acredita la pareja de hecho?", respuesta: "Inscripción registral o escritura pública." },
{ pregunta: "¿Puede cobrar viudedad un matrimonio separado legalmente?", respuesta: "Sí, si percibía pensión compensatoria." },
{ pregunta: "¿Qué ocurre si la pensión compensatoria se extinguía por fallecimiento?", respuesta: "Da derecho a viudedad." },
{ pregunta: "¿Puede haber varios beneficiarios de viudedad?", respuesta: "Sí, se reparte proporcionalmente." },
{ pregunta: "¿Qué requisito económico se exige para el 70% de viudedad?", respuesta: "Ingresos bajos y cargas familiares." },
{ pregunta: "¿Qué requisito se exige para el 60% de viudedad?", respuesta: "Ser mayor de 65 y no tener ingresos propios." },
{ pregunta: "¿Qué ocurre si el causante estaba en alta?", respuesta: "Se calcula la BR según bases reales." },
{ pregunta: "¿Qué ocurre si el causante no estaba en alta?", respuesta: "Se aplica la BR de no alta." },
{ pregunta: "¿Qué es una situación asimilada al alta?", respuesta: "Situación que permite acceder a prestaciones sin estar en alta." },
{ pregunta: "¿Qué ejemplo típico es situación asimilada al alta?", respuesta: "El desempleo con prestación." },
{ pregunta: "¿Qué ocurre si el fallecimiento es por accidente laboral?", respuesta: "No se exige cotización previa." },
{ pregunta: "¿Qué ocurre si el fallecimiento es por enfermedad profesional?", respuesta: "No se exige cotización previa." },
{ pregunta: "¿Qué es el hecho causante?", respuesta: "El momento en que se produce el fallecimiento o declaración." },
{ pregunta: "¿Qué fecha se toma como hecho causante en desaparición?", respuesta: "La resolución judicial." },
{ pregunta: "¿Qué fecha se toma como hecho causante en accidente?", respuesta: "El día del accidente." },
{ pregunta: "¿Qué fecha se toma como hecho causante en enfermedad?", respuesta: "El día del fallecimiento." },
{ pregunta: "¿Qué ocurre si el causante estaba jubilado?", respuesta: "La BR se calcula según su pensión." },
{ pregunta: "¿Qué ocurre si el causante era pensionista de incapacidad?", respuesta: "La BR se calcula según su pensión." },

{ pregunta: "¿Qué prestación se reconoce si no hay viudo ni huérfanos?", respuesta: "Pensión en favor de familiares." },
{ pregunta: "¿Qué familiares pueden cobrar la pensión en favor de familiares?", respuesta: "Nietos, hermanos y ascendientes." },
{ pregunta: "¿Qué requisito exige la pensión en favor de familiares?", respuesta: "Convivencia y dependencia económica." },
{ pregunta: "¿Qué ocurre si el beneficiario trabaja?", respuesta: "Puede ser compatible según ingresos." },
{ pregunta: "¿Qué ocurre si el beneficiario supera los ingresos permitidos?", respuesta: "Se suspende la pensión." },
{ pregunta: "¿Qué ocurre si vuelve a cumplir requisitos?", respuesta: "Se reactiva la pensión." },
{ pregunta: "¿Es compatible la viudedad con trabajo?", respuesta: "Sí." },
{ pregunta: "¿Es compatible la orfandad con trabajo?", respuesta: "Sí, si ingresos < SMI anual." },
{ pregunta: "¿Qué ocurre si el huérfano supera el SMI?", respuesta: "Se suspende la orfandad." },
{ pregunta: "¿Qué ocurre si vuelve a ganar menos del SMI?", respuesta: "Se reactiva la orfandad." },

{ pregunta: "¿Qué prestación se reconoce si el fallecido estaba en alta?", respuesta: "Las prestaciones de muerte y supervivencia según corresponda." },
{ pregunta: "¿Qué prestación se reconoce si estaba en situación asimilada al alta?", respuesta: "Las mismas que si estuviera en alta." },
{ pregunta: "¿Qué prestación cubre los gastos del sepelio?", respuesta: "El auxilio por defunción." },
{ pregunta: "¿Qué prestación recibe el cónyuge superviviente?", respuesta: "La pensión de viudedad." },
{ pregunta: "¿Qué prestación reciben los hijos del causante?", respuesta: "La pensión de orfandad." },
{ pregunta: "¿Qué prestación cubre a familiares dependientes convivientes?", respuesta: "La pensión en favor de familiares." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido era pensionista de incapacidad?", respuesta: "Prestaciones según su pensión." },
{ pregunta: "¿Qué prestación se reconoce si era pensionista de jubilación?", respuesta: "Prestaciones según su pensión." },
{ pregunta: "¿Qué prestación se reconoce si el fallecimiento es por accidente laboral?", respuesta: "Prestaciones sin requisito de cotización previa." },
{ pregunta: "¿Qué prestación se reconoce si es por enfermedad profesional?", respuesta: "Prestaciones sin requisito de cotización previa." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido estaba en desempleo con prestación?", respuesta: "Prestaciones de muerte y supervivencia (asimilada al alta)." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido estaba en ERTE?", respuesta: "Prestaciones de muerte y supervivencia (asimilada al alta)." },
{ pregunta: "¿Qué prestación se reconoce si estaba en excedencia por cuidado de hijos?", respuesta: "Prestaciones de muerte y supervivencia (asimilada al alta)." },
{ pregunta: "¿Qué prestación se reconoce si estaba en convenio especial?", respuesta: "Prestaciones de muerte y supervivencia." },
{ pregunta: "¿Qué prestación se reconoce si estaba en pluriempleo?", respuesta: "Prestaciones con suma de bases." },
{ pregunta: "¿Qué prestación se reconoce si estaba en pluriactividad?", respuesta: "Prestaciones en uno o varios regímenes." },
{ pregunta: "¿Qué prestación se reconoce si era autónomo?", respuesta: "Prestaciones del RETA." },
{ pregunta: "¿Qué prestación se reconoce si era agrario?", respuesta: "Prestaciones del Sistema Especial Agrario." },
{ pregunta: "¿Qué prestación se reconoce si era empleada de hogar?", respuesta: "Prestaciones del Sistema Especial de Hogar." },
{ pregunta: "¿Qué prestación se reconoce si era trabajador del mar?", respuesta: "Prestaciones gestionadas por el ISM." },

{ pregunta: "¿Qué ocurre si el fallecido tenía lagunas de cotización?", respuesta: "Se integran lagunas según normativa." },
{ pregunta: "¿Qué ocurre si tenía bases muy bajas?", respuesta: "Prestaciones calculadas con su BR real." },
{ pregunta: "¿Qué ocurre si tenía bases muy altas?", respuesta: "Prestaciones con tope máximo de BR." },
{ pregunta: "¿Qué ocurre si tenía deudas con la Seguridad Social?", respuesta: "No afectan a los beneficiarios." },
{ pregunta: "¿Qué ocurre si tenía sanciones?", respuesta: "No afectan a las prestaciones." },
{ pregunta: "¿Qué ocurre si estaba desaparecido?", respuesta: "Prestaciones tras declaración judicial." },
{ pregunta: "¿Qué ocurre si murió en el extranjero?", respuesta: "Prestaciones con documentación acreditativa." },
{ pregunta: "¿Qué ocurre si murió en acto de servicio?", respuesta: "Prestaciones con posible recargo empresarial." },
{ pregunta: "¿Qué ocurre si hubo falta de medidas de seguridad?", respuesta: "Recargo del 30% al 50%." },
{ pregunta: "¿Qué ocurre si el fallecido tenía varios regímenes cotizados?", respuesta: "Se aplica pluriactividad o totalización." },

{ pregunta: "¿Qué prestación se reconoce si el cónyuge no cumple requisitos de viudedad?", respuesta: "Pensión temporal de viudedad." },
{ pregunta: "¿Qué ocurre si la pareja de hecho no acredita convivencia?", respuesta: "No procede viudedad." },
{ pregunta: "¿Qué ocurre si la pareja de hecho acredita convivencia?", respuesta: "Pensión de viudedad." },
{ pregunta: "¿Qué ocurre si el matrimonio estaba separado legalmente?", respuesta: "Viudedad si había pensión compensatoria." },
{ pregunta: "¿Qué ocurre si la pensión compensatoria se extinguía por fallecimiento?", respuesta: "Da derecho a viudedad." },
{ pregunta: "¿Qué ocurre si hay varios excónyuges?", respuesta: "Viudedad prorrateada." },
{ pregunta: "¿Qué ocurre si el huérfano tiene discapacidad del 33%?", respuesta: "Orfandad vitalicia." },
{ pregunta: "¿Qué ocurre si el huérfano tiene 21 años y no trabaja?", respuesta: "Pensión de orfandad." },
{ pregunta: "¿Qué ocurre si el huérfano tiene 25 años y no trabaja?", respuesta: "Pensión de orfandad." },
{ pregunta: "¿Qué ocurre si el huérfano trabaja pero gana menos del SMI?", respuesta: "Orfandad compatible." },
{ pregunta: "¿Qué ocurre si el fallecido convivía con sobrinos dependientes?", respuesta: "Pensión en favor de familiares si cumplen requisitos." },
{ pregunta: "¿Qué ocurre si convivía con un familiar discapacitado?", respuesta: "Pensión en favor de familiares." },
{ pregunta: "¿Qué ocurre si convivía con un familiar mayor de 65 años?", respuesta: "Pensión en favor de familiares." },
{ pregunta: "¿Qué ocurre si convivía con un familiar sin ingresos?", respuesta: "Pensión en favor de familiares." },
{ pregunta: "¿Qué ocurre si el fallecido tenía varios hijos de distintos matrimonios?", respuesta: "Todos los hijos con derecho cobran orfandad." },
{ pregunta: "¿Qué ocurre si el fallecido tenía nietos a cargo?", respuesta: "Pensión en favor de familiares." },
{ pregunta: "¿Qué ocurre si el fallecido tenía hermanos a cargo?", respuesta: "Pensión en favor de familiares." },
{ pregunta: "¿Qué ocurre si el fallecido tenía ascendientes a cargo?", respuesta: "Pensión en favor de familiares." },
{ pregunta: "¿Qué ocurre si el fallecido tenía un único familiar dependiente?", respuesta: "Puede acceder a pensión en favor de familiares." },
{ pregunta: "¿Qué ocurre si el fallecido tenía familiares no convivientes?", respuesta: "No procede pensión en favor de familiares." },

{ pregunta: "¿Qué requisito económico se exige para la pensión en favor de familiares?", respuesta: "Dependencia económica del causante." },
{ pregunta: "¿Qué requisito de convivencia se exige para familiares?", respuesta: "Convivencia de 2 años previos al fallecimiento." },
{ pregunta: "¿Qué ocurre si el familiar beneficiario trabaja?", respuesta: "Puede ser compatible según ingresos." },
{ pregunta: "¿Qué ocurre si el familiar supera ingresos?", respuesta: "Se suspende la pensión." },
{ pregunta: "¿Qué ocurre si vuelve a cumplir requisitos económicos?", respuesta: "Se reactiva la pensión." },
{ pregunta: "¿Qué ocurre si el fallecido tenía pensión no contributiva?", respuesta: "Puede generar auxilio por defunción." },
{ pregunta: "¿Qué ocurre si el fallecido no tenía cotización suficiente?", respuesta: "Solo procede auxilio por defunción." },
{ pregunta: "¿Qué ocurre si el fallecido era pensionista de viudedad?", respuesta: "Puede generar prestaciones si cumple requisitos." },
{ pregunta: "¿Qué ocurre si el fallecido era pensionista de orfandad?", respuesta: "No genera nuevas prestaciones." },
{ pregunta: "¿Qué ocurre si el fallecido tenía pensión en favor de familiares?", respuesta: "No genera nuevas prestaciones." },

{ pregunta: "¿Qué ocurre si el fallecido tenía convenio especial activo?", respuesta: "Se considera situación asimilada al alta." },
{ pregunta: "¿Qué ocurre si el fallecido estaba en huelga legal?", respuesta: "Situación asimilada al alta." },
{ pregunta: "¿Qué ocurre si estaba en cierre patronal?", respuesta: "Situación asimilada al alta." },
{ pregunta: "¿Qué ocurre si estaba en traslado al extranjero?", respuesta: "Situación asimilada al alta." },
{ pregunta: "¿Qué ocurre si estaba en excedencia forzosa?", respuesta: "Situación asimilada al alta." },
{ pregunta: "¿Qué ocurre si estaba en prisión preventiva?", respuesta: "Situación asimilada al alta." },
{ pregunta: "¿Qué ocurre si estaba en servicio militar obligatorio?", respuesta: "Situación asimilada al alta." },
{ pregunta: "¿Qué ocurre si estaba en servicio social sustitutivo?", respuesta: "Situación asimilada al alta." },
{ pregunta: "¿Qué ocurre si estaba en incapacidad temporal?", respuesta: "Situación de alta." },
{ pregunta: "¿Qué ocurre si estaba en maternidad o paternidad?", respuesta: "Situación de alta." }


];
