const preguntas = [
  { pregunta: "¿Cuál es el artículo de la Constitución Española (CE) que sirve de eje central para la Seguridad Social?", respuesta: "El artículo 41 de la CE." },
  { pregunta: "¿Qué tipo de régimen exige el artículo 41 de la CE que mantengan los poderes públicos?", respuesta: "Un régimen público de Seguridad Social para todos los ciudadanos." },
  { pregunta: "¿Cuál es la finalidad primordial de la Seguridad Social según el artículo 41 de la CE?", respuesta: "Garantizar la asistencia y prestaciones sociales suficientes ante situaciones de necesidad." },
  { pregunta: "¿Qué situación de necesidad menciona explícitamente el artículo 41 de la CE que debe protegerse especialmente?", respuesta: "La situación de desempleo." },
  { pregunta: "¿Qué carácter atribuye el artículo 41 de la CE a la asistencia y prestaciones complementarias?", respuesta: "Establece expresamente que serán libres (carácter privado y voluntario)." },
  { pregunta: "¿Cuáles son los 4 principios del sistema de Seguridad Social que la doctrina extrae del artículo 41 de la CE?", respuesta: "Sistema público, universalidad subjetiva, generalidad objetiva y suficiencia prestacional." },
  { pregunta: "¿Qué significa el principio de universalidad subjetiva derivado del artículo 41 de la CE?", respuesta: "Que todos los ciudadanos son destinatarios de la asistencia y prestaciones del sistema público." },
  { pregunta: "¿Qué implica el principio de generalidad objetiva en el artículo 41 de la CE?", respuesta: "Que el sistema debe garantizar prestaciones sociales e integrales, no únicamente de carácter económico." },
  { pregunta: "¿Qué criterio numérico o matemático fija la CE para determinar cuándo una prestación es 'suficiente'?", respuesta: "Ninguno; la CE no define el concepto de suficiencia, dejándolo al arbitrio del desarrollo legislativo ordinario." },
  { pregunta: "¿A quién corresponde fijar las normas reguladoras y la gestión directa del sistema público de la SS?", respuesta: "A los poderes públicos del Estado." },
  { pregunta: "¿En qué precepto constitucional se reconoce el derecho de los reclusos a los beneficios de la SS?", respuesta: "En el artículo 25.2 de la CE." },
  { pregunta: "¿Qué derecho concreto se le reconoce al condenado a pena de prisión respecto a la SS en el art. 25.2 CE?", respuesta: "Derecho a un trabajo remunerado y a los beneficios correspondientes de la Seguridad Social." },
  { pregunta: "¿Cuál es la naturaleza jurídica y el nivel de protección procesal del artículo 25.2 de la CE?", respuesta: "Es un derecho fundamental (Título I, Capítulo II, Sección 1ª) protegido mediante recurso de amparo." },
  { pregunta: "¿Qué artículo de la CE encomienda a los poderes públicos asegurar la protección social y económica de la familia?", respuesta: "El artículo 39.1 de la CE." },
  { pregunta: "¿Qué artículo de la CE consagra el derecho a la protección de la salud y la tutela de la salud pública?", respuesta: "El artículo 43 de la CE." },
  { pregunta: "¿Qué artículo constitucional fue reformado en 2024 para regular la autonomía personal de las personas con discapacidad?", respuesta: "El artículo 49 de la CE." },
  { pregunta: "¿Qué artículo de la CE garantiza la suficiencia económica de la tercera edad mediante pensiones?", respuesta: "El artículo 50 de la CE." },
  { pregunta: "¿Cómo deben ser las pensiones de la tercera edad según las exigencias del artículo 50 de la CE?", respuesta: "Deben ser adecuadas y estar periódicamente actualizadas." },
  { pregunta: "¿Qué artículo constitucional regula la participación de los interesados en los organismos públicos de la SS?", respuesta: "El artículo 129 de la CE." },
  { pregunta: "¿En qué cuatro únicos artículos de la CE se utiliza textualmente la expresión 'Seguridad Social'?", respuesta: "En los artículos 25.2, 41, 129.1 y 149.1.17ª." },
  { pregunta: "¿Cuál es la naturaleza jurídica de los artículos 39, 43, 49 y 50 de la Constitución Española?", respuesta: "Son principios rectores de la política social y económica (Título I, Capítulo III)." },
  { pregunta: "¿Se puede interponer directamente un recurso de amparo basado en el incumplimiento del artículo 50 de la CE?", respuesta: "No, los principios rectores solo pueden alegarse ante la jurisdicción ordinaria de acuerdo con las leyes que los desarrollen." },
  { pregunta: "¿Qué artículo de la CE regula los efectos normativos e informadores de los principios rectores?", respuesta: "El artículo 53.3 de la CE." },
  { pregunta: "¿Qué dos grandes modalidades de protección integran el nivel obligatorio del sistema de la SS?", respuesta: "La modalidad contributiva (o profesional) y la modalidad no contributiva (o básica)." },
  { pregunta: "¿Cuál es el ámbito de aplicación subjetivo del nivel básico o no contributivo de la Seguridad Social?", respuesta: "Es de carácter universal, dirigido a todos los ciudadanos residentes que demuestren estado de necesidad." },
  { pregunta: "¿Cuál es el objetivo principal del nivel contributivo o profesional del sistema?", respuesta: "Garantizar rentas de sustitución proporcionales a los salarios y cotizaciones previas del trabajador activo." },
  { pregunta: "¿Cómo se financia el nivel contributivo o profesional de la Seguridad Social?", respuesta: "Mediante las cotizaciones sociales obligatorias a cargo de trabajadores y empresarios, con aportaciones estatales." },
  { pregunta: "¿Cómo se financia de forma principal el nivel básico y no contributivo de la Seguridad Social?", respuesta: "A través de transferencias de los Presupuestos Generales del Estado (PGE)." },
  { pregunta: "Si los servicios de asistencia sanitaria están transferidos a las CCAA, ¿cómo se financian?", respuesta: "A través del sistema general de financiación autonómica." },
  { pregunta: "¿Qué artículo del TRLGSS detalla la estructura y separación de las fuentes de financiación del sistema?", respuesta: "El artículo 109.3 del TRLGSS." },
  { pregunta: "¿Las pensiones no contributivas de invalidez y jubilación se financian con cotizaciones o con el Estado?", respuesta: "Se financian con cargo al Estado a través de las aportaciones pautadas en los PGE." },
  { pregunta: "¿Menciona un subsidio del nivel básico que no exija cotizaciones previas pero esté regulado en el TRLGSS?", respuesta: "El subsidio por maternidad de naturaleza no contributiva (arts. 181-182 TRLGSS)." },
  { pregunta: "¿Qué nivel de protección abarca las prestaciones y pensiones derivadas de AT y EP en su totalidad?", respuesta: "El nivel profesional o contributivo del sistema." },
  { pregunta: "¿Qué carácter ostenta el nivel complementario de la Seguridad Social según la doctrina?", respuesta: "Es libre, voluntario y tiene carácter privado u opcional." },
  { pregunta: "¿El nivel complementario de la Seguridad Social puede sustituir al sistema obligatorio de protección?", respuesta: "No, tiene carácter estrictamente adicional y nunca sustitutivo del régimen público." },
  { pregunta: "¿Cómo se financia de forma exclusiva el nivel complementario de la Seguridad Social?", respuesta: "Mediante las aportaciones económicas directas y exclusivas de los sujetos partícipes." },
  { pregunta: "Menciona dos ejemplos prácticos que integren el nivel complementario de la protección social.", respuesta: "Los planes de pensiones privados y las mejoras voluntarias de la acción protectora a cargo de las empresas." },
  { pregunta: "¿Qué artículo de la CE distribuye las competencias que pueden asumir las Comunidades Autónomas?", respuesta: "El artículo 148 de la CE." },
  { pregunta: "¿Qué competencia reconoce el artículo 148.1.20ª de la CE a las Comunidades Autónomas?", respuesta: "La competencia en materia de asistencia social." },
  { pregunta: "¿Qué competencia reconoce el artículo 148.1.21ª de la CE a las Comunidades Autónomas?", respuesta: "La competencia sobre sanidad e higiene." },
  { pregunta: "¿Qué artículo de la CE blinda las competencias exclusivas e indelegables del Estado central?", respuesta: "El artículo 149 de la CE." },
  { pregunta: "¿Qué materia reserva el artículo 149.1.16ª de la CE al Estado en materia sanitaria?", respuesta: "La sanidad exterior, las bases y la coordinación general de la sanidad, y la legislación sobre productos farmacéuticos." },
  { pregunta: "¿Qué competencias concretas reserva el artículo 149.1.17ª de la CE al Estado central sobre la SS?", respuesta: "La legislación básica y el régimen económico de la Seguridad Social." },
  { pregunta: "¿Qué margen de actuación otorga el artículo 149.1.17ª de la CE a las CCAA en materia de SS?", respuesta: "Permite que las Comunidades Autónomas asuman la ejecución de los servicios de la Seguridad Social." },
  { pregunta: "¿Puede una Comunidad Autónoma dictar una ley propia que modifique los requisitos de jubilación?", respuesta: "No, porque la legislación básica es competencia exclusiva y ciega del Estado central." },
  { pregunta: "¿Qué principio financiero del sistema de la SS se protege al reservar el régimen económico al Estado?", respuesta: "El principio de caja única del sistema de la Seguridad Social." },
  { pregunta: "¿Qué artículo del TRLGSS consagra el derecho de los españoles a recibir la protección del sistema?", respuesta: "El artículo 1 del TRLGSS." },
  { pregunta: "¿Cuáles son los cuatro principios rectores de ordenación recogidos en el artículo 2.1 del TRLGSS?", respuesta: "Universalidad, unidad, solidaridad e igualdad." },
  { pregunta: "¿Cuál es el fin principal de la SS según el artículo 2.2 del TRLGSS?", respuesta: "Garantizar a las personas comprendidas en su campo una protección adecuada ante las contingencias legales." },
  { pregunta: "¿Qué establece el artículo 3 del TRLGSS respecto a la renuncia de los derechos de protección social?", respuesta: "Consagra el principio de irrenunciabilidad; será nulo todo pacto (individual o colectivo) de renuncia a los derechos de la ley." },
  { pregunta: "¿Qué órgano o institución es responsable de coordinar la SS con los demás servicios públicos según el art. 6?", respuesta: "El Gobierno de la Nación." },
  { pregunta: "¿Qué prohibición lucrativa pesa sobre las entidades gestoras y actividades de la SS?", respuesta: "Las actividades y gestión del sistema público no pueden ser utilizadas para obtener beneficios mercantiles o de lucro." },
  { pregunta: "¿En qué año se aprobó la primera Ley de Bases de la Seguridad Social en España?", respuesta: "En el año 1963 (Ley 193/1963, de 28 de diciembre)." },
  { pregunta: "¿Qué norma articulada sustituyó a la Ley de Bases de 1963 configurando el sistema antiguo?", respuesta: "El Texto Refundido aprobado por el Decreto 2065/1974, de 30 de mayo." },
  { pregunta: "¿Qué Real Decreto Legislativo operaba como Ley de SS inmediatamente antes de la norma vigente actual?", respuesta: "El Real Decreto Legislativo 1/1994, de 20 de junio." },
  { pregunta: "¿Cuál es la norma, número y fecha del Texto Refundido de la Ley General de la Seguridad Social vigente?", respuesta: "El Real Decreto Legislativo 8/2015, de 30 de octubre (TRLGSS)." },
  { pregunta: "¿Qué rango normativo posee el actual TRLGSS aprobado en el año 2015?", respuesta: "Tiene rango de Ley ordinaria (es un Real Decreto Legislativo emanado por delegación)." },
  { pregunta: "¿Qué ley específica otorgó al Gobierno la autorización para refundir los textos legales de la SS en 2015?", respuesta: "La Ley 20/2014, de 29 de octubre, de medidas de reforma administrativa." },
  { pregunta: "¿En qué fecha exacta entró en vigor el actual TRLGSS de 2015?", respuesta: "Entró en vigor el día 2 de enero de 2016." },
  { pregunta: "¿Cuántos artículos componen el cuerpo articulado del TRLGSS vigente?", respuesta: "Está compuesto por un total de 373 artículos." },
  { pregunta: "¿Cuántas disposiciones adicionales contiene el TRLGSS de 2015?", respuesta: "Contiene un total de 53 disposiciones adicionales." },
  { pregunta: "¿Cuántas disposiciones transitorias estructuran el TRLGSS actual?", respuesta: "Cuenta con un total de 44 disposiciones transitorias." },
  { pregunta: "¿Cuántas disposiciones finales integran el cierre del TRLGSS?", disappearance: "", respuesta: "Dispone de un total de 8 disposiciones finales." },
  { pregunta: "¿Qué materia regula de forma general el Título I del TRLGSS?", respuesta: "Las normas generales del sistema (campo de aplicación, afiliación, cotización, gestión, recaudación y sanciones)." },
  { pregunta: "¿Qué materia regula de forma exclusiva el Título II del TRLGSS?", respuesta: "El Régimen General de la Seguridad Social (inscripción, cotización y todas sus prestaciones contributivas)." },
  { pregunta: "¿Qué materia regula detalladamente el Título III del TRLGSS?", respuesta: "La protección por desempleo (tanto en su nivel contributivo como en su nivel asistencial o de subsidios)." },
  { pregunta: "¿Qué colectivo y régimen se regula a lo largo del Título IV del TRLGSS?", respuesta: "El Régimen Especial de la Seguridad Social de los Trabajadores por Cuenta Propia o Autónomos (RETA)." },
  { pregunta: "¿Qué contingencia y protección específica para autónomos se desarrolla en el Título V del TRLGSS?", respuesta: "La protección por cese de actividad (el denominado 'paro de los autónomos')." },
  { pregunta: "¿Qué se regula a lo largo del Título VI del TRLGSS?", respuesta: "Las prestaciones no contributivas (pensiones de invalidez/jubilación no contributivas y prestaciones familiares)." },
  { pregunta: "¿Qué norma reglamentaria regula el cuadro de prestaciones de la SS heredado del sistema originario?", respuesta: "El Decreto 3158/1963, de 23 de diciembre (Reglamento General de Prestaciones)." },
  { pregunta: "¿Qué Real Decreto aprueba el Reglamento General sobre inscripción de empresas, afiliación, altas y bajas?", respuesta: "El Real Decreto 84/1996, de 26 de enero." },
  { pregunta: "¿Qué Real Decreto aprueba el Reglamento General sobre cotización y liquidación de otros derechos de la SS?", respuesta: "El Real Decreto 2064/1995, de 22 de diciembre." },
  { pregunta: "¿Qué Real Decreto aprueba el Reglamento General de Recaudación de la Seguridad Social?", respuesta: "El Real Decreto 1415/2004, de 11 de junio." },
  { pregunta: "¿Qué rango jerárquico tienen los Reales Decretos de inscripción, cotización y recaudación frente al TRLGSS?", respuesta: "Rango reglamentario o de norma subordinada a la Ley (rango inferior)." },
  { pregunta: "¿Qué principio del artículo 2 del TRLGSS prohíbe establecer diferencias de derechos por motivos territoriales?", respuesta: "El principio de igualdad." },
  { pregunta: "¿Qué principio del artículo 2 del TRLGSS exige que las aportaciones de los activos sostengan a los pasivos?", respuesta: "El principio de solidaridad intergeneracional." },
  { pregunta: "¿Qué principio del artículo 2 del TRLGSS mandata la existencia de una sola estructura financiera centralizada?", respuesta: "El principio de unidad (un solo sistema para todo el Estado)." },
  { pregunta: "¿Cuál es el régimen que opera como supletorio para colmar las lagunas de los Regímenes Especiales?", respuesta: "El Régimen General de la Seguridad Social." },
  { pregunta: "¿A qué ministerio se encuentra adscrita la gestión superior y tutela de la SS a nivel nacional?", respuesta: "Al Ministerio de Inclusión, Seguridad Social y Migraciones." },
  { pregunta: "¿Qué ley habilitó la reestructuración y delegación normativa que dio origen al RD Legislativo 8/2015?", respuesta: "La Ley 20/2014, de 29 de octubre." },
  { pregunta: "¿La Seguridad Social puede delegar la recaudación coactiva de cuotas en las CCAA?", respuesta: "No, la recaudación y el régimen económico son competencia exclusiva e irrenunciable del Estado (TGSS)." },
  { pregunta: "¿Qué disposición del TRLGSS regula expresamente las remisiones normativas hacia otras leyes?", respuesta: "La Disposición Adicional Única del Real Decreto de aprobación." },
  { pregunta: "¿Qué disposición del Real Decreto del TRLGSS declara la pérdida de vigencia de las normas previas de igual rango?", respuesta: "La Disposición Derogatoria Única." },
  { pregunta: "¿El subsidio por desempleo de nivel asistencial se financia con cotizaciones o con PGE?", respuesta: "Se financia mediante aportaciones del Estado incorporadas a los PGE." },
  { pregunta: "¿Qué artículo de la CE garantiza la defensa de los consumidores e influye tangencialmente en la sanidad?", respuesta: "El artículo 51 de la CE." },
  { pregunta: "¿Cuál es el plazo de actualización de las pensiones exigido por el artículo 50 de la CE?", respuesta: "Exige que se realice de forma 'periódica' (actualmente ligado por ley al IPC anual)." },
  { pregunta: "¿La asistencia social del artículo 148 de la CE es una competencia obligatoria del Estado?", respuesta: "No, es una competencia que las Comunidades Autónomas pueden asumir plenamente en sus Estatutos." },
  { pregunta: "¿Qué entidad asume la competencia sobre el régimen económico y titularidad de los bienes de la SS?", respuesta: "El Estado central a través de la Tesorería General de la Seguridad Social (TGSS)." },
  { pregunta: "¿En qué año entró en vigor el primer Texto Refundido de la Ley General de la Seguridad Social?", respuesta: "En el año 1974 (Decreto 2065/1974)." },
  { pregunta: "¿La Constitución Española prohíbe la existencia de mutuas colaboradoras privadas en la SS?", respuesta: "No, el artículo 41 permite la colaboración privada siempre que se someta al régimen público rector." },
  { pregunta: "¿Qué principio impide que un trabajador renuncie a su pensión de jubilación a cambio de un pago de la empresa?", respuesta: "El principio de irrenunciabilidad de derechos consagrado en el artículo 3 del TRLGSS." },
  { pregunta: "¿Qué disposición final del Real Decreto de aprobación fija la entrada en vigor del TRLGSS en 2016?", respuesta: "La Disposición Final Única." },
  { pregunta: "¿Qué capítulo del Título I del TRLGSS recoge el campo de aplicación y los sistemas especiales?", respuesta: "El Capítulo II del Título I." },
  { pregunta: "¿Qué capítulo del Título I regula la acción protectora en sus líneas generales?", respuesta: "Análisis sistemático: El Capítulo III del Título I del TRLGSS." },
  { pregunta: "¿Los complementos por mínimos de las pensiones contributivas se financian con cotizaciones o PGE?", respuesta: "Se financian mediante transferencias del Estado a través de los PGE." },
  { pregunta: "¿Quién ejerce la alta dirección y la inspección de los servicios de la Seguridad Social?", respuesta: "El Estado central a través del Ministerio competente y la Inspección de Trabajo y Seguridad Social." },
  { pregunta: "¿Qué principio del artículo 41 de la CE garantiza que la cobertura alcance a situaciones de necesidad reales?", respuesta: "El principio de suficiencia." },
  { pregunta: "¿La legislación sobre productos farmacéuticos es competencia autonómica o estatal según el art. 149 CE?", respuesta: "Es competencia exclusiva del Estado central (artículo 149.1.16ª CE)." },
  { pregunta: "¿Qué artículo del TRLGSS recoge las funciones y el objeto de la Seguridad Social de forma introductoria?", respuesta: "El artículo 2 del TRLGSS." },
  { pregunta: "¿El Ingreso Mínimo Vital (IMV) se encuadra en el nivel contributivo o en el nivel no contributivo?", respuesta: "Se encuadra plenamente en el nivel no contributivo o básico (asistencial de necesidad)." },
  { pregunta: "¿Qué garantiza el artículo 41 de la Constitución Española?", respuesta: "Un régimen público de Seguridad Social para todos los ciudadanos que asegure asistencia y prestaciones suficientes ante situaciones de necesidad." },
  { pregunta: "¿Qué contingencia menciona expresamente el artículo 41 CE como prioritaria?", respuesta: "El desempleo." },
  { pregunta: "¿Qué carácter tienen las prestaciones complementarias según el artículo 41 CE?", respuesta: "Son libres y voluntarias." },
  { pregunta: "¿Cuál es el primer principio derivado del artículo 41 CE?", respuesta: "El carácter público del sistema de Seguridad Social." },
  { pregunta: "¿Qué principio del art. 41 CE implica que todos los ciudadanos son destinatarios del sistema?", respuesta: "La universalidad subjetiva." },
  { pregunta: "¿Qué principio del art. 41 CE implica que la protección abarca asistencia y prestaciones sociales?", respuesta: "La generalidad objetiva." },
  { pregunta: "¿Qué principio del art. 41 CE exige que las prestaciones sean suficientes?", respuesta: "La suficiencia prestacional." },
  { pregunta: "¿Qué criterio establece la Constitución para determinar cuándo una prestación es suficiente?", respuesta: "Ninguno; la CE no fija criterios de suficiencia." },
  { pregunta: "¿Qué artículo constitucional garantiza la protección social, económica y jurídica de la familia?", respuesta: "El artículo 39 CE." },
  { pregunta: "¿Qué artículo constitucional garantiza la protección de la salud?", respuesta: "El artículo 43 CE." },
  { pregunta: "¿Qué artículo constitucional garantiza la autonomía personal e inclusión de las personas con discapacidad?", respuesta: "El artículo 49 CE." },
  { pregunta: "¿Qué artículo constitucional garantiza pensiones adecuadas y actualizadas para la tercera edad?", respuesta: "El artículo 50 CE." },
  { pregunta: "¿Qué artículo constitucional reconoce el derecho a un trabajo remunerado y beneficios de la Seguridad Social para personas en prisión?", respuesta: "El artículo 25.2 CE." },
  { pregunta: "¿Qué naturaleza jurídica tiene el artículo 25.2 CE?", respuesta: "Es un derecho fundamental (Título I, Capítulo 2º, Sección 1ª)." },
  { pregunta: "¿Qué naturaleza jurídica tienen los artículos 39, 43, 49 y 50 CE?", respuesta: "Son principios rectores de la política social y económica." },
  { pregunta: "¿Cuántos artículos de la Constitución utilizan literalmente la expresión 'Seguridad Social'?", respuesta: "Cuatro: arts. 25.2, 41, 129 y 149.1.17ª." },
  { pregunta: "¿Qué competencia exclusiva tiene el Estado según el art. 149.1.17ª CE?", respuesta: "La legislación básica y el régimen económico de la Seguridad Social." },
  { pregunta: "¿Qué pueden hacer las Comunidades Autónomas respecto a la Seguridad Social según el art. 149.1.17ª CE?", respuesta: "Ejecutar los servicios de la Seguridad Social." },
  { pregunta: "¿Qué materias pueden asumir las CCAA según el art. 148 CE relacionadas con la protección social?", respuesta: "Asistencia social y sanidad e higiene." },
  { pregunta: "¿Qué principio del art. 2 TRLGSS garantiza que todos los ciudadanos estén protegidos por el sistema?", respuesta: "La universalidad." },
    { pregunta: "¿Qué artículo constitucional garantiza la protección social, económica y jurídica de la familia?", respuesta: "El artículo 39 CE." },
  { pregunta: "¿Qué artículo constitucional garantiza la protección de la salud?", respuesta: "El artículo 43 CE." },
  { pregunta: "¿Qué artículo constitucional garantiza la autonomía personal e inclusión de las personas con discapacidad?", respuesta: "El artículo 49 CE." },
  { pregunta: "¿Qué artículo constitucional garantiza pensiones adecuadas y actualizadas para la tercera edad?", respuesta: "El artículo 50 CE." },
  { pregunta: "¿Qué artículo constitucional reconoce la participación de los interesados en la Seguridad Social?", respuesta: "El artículo 129 CE." },
  { pregunta: "¿Cuántos artículos constitucionales utilizan literalmente la expresión 'Seguridad Social'?", respuesta: "Cuatro: arts. 25.2, 41, 129 y 149.1.17ª." },
  { pregunta: "¿Qué naturaleza jurídica tiene el artículo 25.2 CE?", respuesta: "Es un derecho fundamental del Título I, Capítulo 2º, Sección 1ª." },
  { pregunta: "¿Qué naturaleza jurídica tienen los artículos 39, 43, 49 y 50 CE?", respuesta: "Son principios rectores de la política social y económica." },
  { pregunta: "¿Qué implica que los arts. 39, 43, 49 y 50 sean principios rectores?", respuesta: "Que requieren desarrollo legislativo y solo pueden alegarse conforme a las leyes que los desarrollen." },
  { pregunta: "¿Qué artículo constitucional establece la competencia exclusiva del Estado sobre la legislación básica de la Seguridad Social?", respuesta: "El artículo 149.1.17ª CE." },
  { pregunta: "¿Qué pueden hacer las CCAA respecto a la Seguridad Social según el art. 149.1.17ª CE?", respuesta: "Ejecutar los servicios de la Seguridad Social." },
  { pregunta: "¿Qué materias pueden asumir las CCAA según el art. 148 CE relacionadas con la protección social?", respuesta: "Asistencia social y sanidad e higiene." },
  { pregunta: "¿Qué nivel de protección se financia con los Presupuestos Generales del Estado?", respuesta: "El nivel básico o no contributivo." },
  { pregunta: "¿Qué nivel de protección se financia con cotizaciones sociales?", respuesta: "El nivel profesional o contributivo." },
  { pregunta: "¿Qué nivel de protección es voluntario y complementario?", respuesta: "El nivel complementario." },
  { pregunta: "¿Qué prestaciones incluye el nivel básico según el art. 109.3 TRLGSS?", respuesta: "Asistencia sanitaria, pensiones no contributivas, subsidio por maternidad, prestaciones familiares y complementos por mínimos." },
  { pregunta: "¿Qué prestaciones incluye el nivel profesional según el art. 109.3 TRLGSS?", respuesta: "IT, IP, jubilación contributiva, MYS, riesgos, NYCM y AT/EP." },
  { pregunta: "¿Qué principio del art. 2 TRLGSS garantiza que todos los ciudadanos estén protegidos por el sistema?", respuesta: "La universalidad." },
  { pregunta: "¿Qué principio del art. 2 TRLGSS garantiza que el sistema funcione como un todo coherente?", respuesta: "La unidad." },
  { pregunta: "¿Qué principio del art. 2 TRLGSS implica redistribución y apoyo mutuo entre colectivos?", respuesta: "La solidaridad." },
  { pregunta: "¿Qué principio del art. 2 TRLGSS garantiza que todos reciban la misma protección en igualdad de condiciones?", respuesta: "La igualdad." },
  { pregunta: "¿Qué establece el artículo 3 TRLGSS sobre la renuncia a derechos?", respuesta: "Que será nulo todo pacto por el cual el trabajador renuncie a derechos de la Seguridad Social." },
  { pregunta: "¿Qué establece el artículo 6 TRLGSS sobre la coordinación?", respuesta: "Que el Gobierno debe coordinar la SS con otros servicios públicos para garantizar protección integral." },
  { pregunta: "¿Qué prohíbe el sistema según el vídeo del Tema 1?", respuesta: "Obtener beneficios mercantiles mediante actividades relacionadas con la Seguridad Social." },
  { pregunta: "¿Qué norma aprueba el actual TRLGSS?", respuesta: "El Real Decreto Legislativo 8/2015, de 30 de octubre." },
  { pregunta: "¿Qué ley autorizó al Gobierno a refundir la normativa de Seguridad Social?", respuesta: "La Ley 20/2014, de 29 de octubre." },
  { pregunta: "¿Cuándo entró en vigor el TRLGSS actual?", respuesta: "El 2 de enero de 2016." },
  { pregunta: "¿Cuántos artículos tiene el TRLGSS?", respuesta: "373 artículos." },
  { pregunta: "¿Cuántas disposiciones adicionales tiene el TRLGSS?", respuesta: "53 disposiciones adicionales." },
  { pregunta: "¿Cuántas disposiciones transitorias tiene el TRLGSS?", respuesta: "44 disposiciones transitorias." },
    { pregunta: "¿Qué artículo del TRLGSS reconoce expresamente el derecho a la Seguridad Social?", respuesta: "El artículo 1 TRLGSS." },
  { pregunta: "¿Qué principios recoge el artículo 2 TRLGSS?", respuesta: "Universalidad, unidad, solidaridad e igualdad." },
  { pregunta: "¿Qué finalidad establece el artículo 2.2 TRLGSS?", respuesta: "Garantizar protección adecuada frente a contingencias previstas en la ley." },
  { pregunta: "¿Qué establece el artículo 3 TRLGSS sobre la renuncia a derechos?", respuesta: "Será nulo todo pacto por el cual el trabajador renuncie a derechos de la Seguridad Social." },
  { pregunta: "¿Qué establece el artículo 6 TRLGSS sobre la coordinación?", respuesta: "El Gobierno debe coordinar la SS con otros servicios públicos para garantizar protección integral." },
  { pregunta: "¿Qué prohíbe el sistema según el vídeo del Tema 1?", respuesta: "Obtener beneficios mercantiles mediante actividades relacionadas con la Seguridad Social." },
  { pregunta: "¿Qué nivel de protección se financia con los Presupuestos Generales del Estado?", respuesta: "El nivel básico o no contributivo." },
  { pregunta: "¿Qué nivel de protección se financia con cotizaciones sociales?", respuesta: "El nivel profesional o contributivo." },
  { pregunta: "¿Qué nivel de protección es voluntario y complementario?", respuesta: "El nivel complementario." },
  { pregunta: "¿Qué prestaciones incluye el nivel básico según el art. 109.3 TRLGSS?", respuesta: "Asistencia sanitaria, PNC, subsidio por maternidad, prestaciones familiares e IMV." },
  { pregunta: "¿Qué prestaciones incluye el nivel profesional según el art. 109.3 TRLGSS?", respuesta: "IT, IP, jubilación contributiva, MYS, riesgos y AT/EP." },
  { pregunta: "¿Qué carácter tienen las prestaciones complementarias según el art. 41 CE?", respuesta: "Son libres y voluntarias." },
  { pregunta: "¿Qué artículo constitucional establece la competencia exclusiva del Estado sobre la legislación básica de la SS?", respuesta: "El artículo 149.1.17ª CE." },
  { pregunta: "¿Qué pueden hacer las CCAA respecto a la Seguridad Social según el art. 149.1.17ª CE?", respuesta: "Ejecutar los servicios de la Seguridad Social." },
  { pregunta: "¿Qué materias pueden asumir las CCAA según el art. 148 CE relacionadas con la protección social?", respuesta: "Asistencia social y sanidad e higiene." },
  { pregunta: "¿Qué artículo constitucional garantiza la protección de la salud?", respuesta: "El artículo 43 CE." },
  { pregunta: "¿Qué artículo constitucional garantiza la protección de la familia?", respuesta: "El artículo 39 CE." },
  { pregunta: "¿Qué artículo constitucional garantiza la inclusión de personas con discapacidad?", respuesta: "El artículo 49 CE." },
  { pregunta: "¿Qué artículo constitucional garantiza pensiones adecuadas y actualizadas?", respuesta: "El artículo 50 CE." },
  { pregunta: "¿Qué artículo constitucional reconoce la participación de los interesados en la SS?", respuesta: "El artículo 129 CE." },
  { pregunta: "¿Qué artículo constitucional reconoce beneficios de la SS a personas en prisión?", respuesta: "El artículo 25.2 CE." },
  { pregunta: "¿Qué naturaleza jurídica tiene el artículo 25.2 CE?", respuesta: "Es un derecho fundamental." },
  { pregunta: "¿Qué naturaleza jurídica tienen los artículos 39, 43, 49 y 50 CE?", respuesta: "Son principios rectores." },
  { pregunta: "¿Qué implica que los principios rectores sean del Capítulo III del Título I?", respuesta: "Requieren desarrollo legislativo y solo pueden alegarse conforme a las leyes que los desarrollen." },
  { pregunta: "¿Qué contingencia menciona expresamente el art. 41 CE como prioritaria?", respuesta: "El desempleo." },
  { pregunta: "¿Qué criterio fija la Constitución para determinar la suficiencia de las prestaciones?", respuesta: "Ninguno; la CE no establece criterios de suficiencia." },
  { pregunta: "¿Qué tipo de gestión permite el art. 41 CE para la Seguridad Social?", respuesta: "Gestión directa estatal o indirecta a través de entes instrumentales." },
  { pregunta: "¿Qué organismos gestionan indirectamente la SS según el Tema 1?", respuesta: "Entes instrumentales como INSS y TGSS." },
  { pregunta: "¿Qué significa que la SS sea un sistema público según el art. 41 CE?", respuesta: "Que corresponde al Estado organizar y gestionar el sistema." },
  { pregunta: "¿Qué significa la universalidad subjetiva del art. 41 CE?", respuesta: "Que todos los ciudadanos son destinatarios del sistema." },
  { pregunta: "¿Qué significa la generalidad objetiva del art. 41 CE?", respuesta: "Que la protección incluye asistencia y prestaciones sociales." },
  { pregunta: "¿Qué significa la suficiencia prestacional del art. 41 CE?", respuesta: "Que las prestaciones deben ser suficientes para cubrir necesidades." },
  { pregunta: "¿Qué norma aprueba el actual TRLGSS?", respuesta: "El Real Decreto Legislativo 8/2015, de 30 de octubre." },
  { pregunta: "¿Qué ley autorizó al Gobierno a refundir la normativa de SS?", respuesta: "La Ley 20/2014, de 29 de octubre." },
  { pregunta: "¿Cuándo entró en vigor el TRLGSS actual?", respuesta: "El 2 de enero de 2016." },
  { pregunta: "¿Cuántos artículos tiene el TRLGSS?", respuesta: "373 artículos." },
  { pregunta: "¿Cuántas disposiciones adicionales tiene el TRLGSS?", respuesta: "53 disposiciones adicionales." },
  { pregunta: "¿Cuántas disposiciones transitorias tiene el TRLGSS?", respuesta: "44 disposiciones transitorias." },
  { pregunta: "¿Qué rango normativo tiene el TRLGSS?", respuesta: "Real Decreto Legislativo (norma con rango de ley)." },
  { pregunta: "¿Qué estructura formal tiene el TRLGSS según el Tema 1?", respuesta: "Preámbulo, artículo único, DA única, DD única y DF única." },
  { pregunta: "¿Cuántos títulos sistemáticos tiene el TRLGSS?", respuesta: "Seis títulos." },
  { pregunta: "¿Qué regula el Título I del TRLGSS?", respuesta: "Normas generales del sistema: campo de aplicación, afiliación, acción protectora, gestión, recaudación y régimen económico." },
  { pregunta: "¿Qué regula el Título II del TRLGSS?", respuesta: "El Régimen General y sus prestaciones." },
  { pregunta: "¿Qué regula el Título III del TRLGSS?", respuesta: "La protección por desempleo." },
  { pregunta: "¿Qué regula el Título IV del TRLGSS?", respuesta: "El Régimen Especial de Trabajadores Autónomos (RETA)." },
  { pregunta: "¿Qué regula el Título V del TRLGSS?", respuesta: "La protección por cese de actividad de autónomos." },
  { pregunta: "¿Qué regula el Título VI del TRLGSS?", respuesta: "Las prestaciones no contributivas." },
  { pregunta: "¿Qué reglamento regula la inscripción de empresas y afiliación?", respuesta: "El Real Decreto 84/1996." },
  { pregunta: "¿Qué reglamento regula la cotización y liquidación?", respuesta: "El Real Decreto 2064/1995." },
  { pregunta: "¿Qué reglamento regula la recaudación en vía voluntaria y ejecutiva?", respuesta: "El Real Decreto 1415/2004." },
  { pregunta: "¿Qué reglamento regula las prestaciones de la Seguridad Social?", respuesta: "El Decreto 3158/1963." }
];


