const preguntas = [
{ pregunta: "¿Qué es la acción protectora de la Seguridad Social?", respuesta: "El conjunto de prestaciones destinadas a cubrir situaciones de necesidad." },
{ pregunta: "¿Qué principio garantiza que todos los ciudadanos estén protegidos?", respuesta: "Universalidad." },
{ pregunta: "¿Qué principio asegura que todos reciben la misma protección en igualdad de condiciones?", respuesta: "Igualdad." },
{ pregunta: "¿Qué principio implica que todos contribuyen según su capacidad?", respuesta: "Contributividad." },
{ pregunta: "¿Qué principio implica que los recursos se distribuyen para cubrir necesidades?", respuesta: "Solidaridad." },
{ pregunta: "¿Qué principio implica que la acción protectora es única para todo el sistema?", respuesta: "Unidad." },
{ pregunta: "¿Qué incluye la acción protectora en asistencia sanitaria?", respuesta: "Prevención, diagnóstico, tratamiento y rehabilitación." },
{ pregunta: "¿Qué incluye la acción protectora en prestaciones económicas?", respuesta: "IT, maternidad, paternidad, IP, jubilación, muerte y supervivencia." },
{ pregunta: "¿Qué incluye la acción protectora en servicios sociales?", respuesta: "Rehabilitación, integración y asistencia social." },
{ pregunta: "¿Qué incluye la acción protectora en prestaciones familiares?", respuesta: "Asignaciones económicas por hijo a cargo." },
{ pregunta: "¿Qué es la automaticidad absoluta?", respuesta: "Prestación garantizada aunque la empresa no cotice." },
{ pregunta: "¿Qué prestaciones tienen automaticidad absoluta?", respuesta: "AT/EP y desempleo." },
{ pregunta: "¿Qué es la automaticidad relativa?", respuesta: "Prestación garantizada si el trabajador está en alta o asimilada." },
{ pregunta: "¿Qué prestaciones tienen automaticidad relativa?", respuesta: "Enfermedad común y accidente no laboral." },
{ pregunta: "¿Qué es el anticipo de prestaciones?", respuesta: "Pago provisional cuando hay dudas sobre la responsabilidad." },
{ pregunta: "¿Quién puede anticipar prestaciones?", respuesta: "El INSS o la mutua." },
{ pregunta: "¿Qué ocurre si se determina que la empresa es responsable del pago?", respuesta: "Debe reintegrar el capital coste." },
{ pregunta: "¿Qué es el capital coste de pensiones?", respuesta: "El valor actuarial de la prestación que debe pagar la empresa." },
{ pregunta: "¿Qué ocurre si la empresa incumple medidas de seguridad?", respuesta: "Se aplica recargo del 30% al 50%." },
{ pregunta: "¿Quién paga el recargo por falta de medidas de seguridad?", respuesta: "La empresa, siempre." },
{ pregunta: "¿Qué es el reintegro de prestaciones indebidas?", respuesta: "Devolución de prestaciones cobradas sin derecho." },
{ pregunta: "¿Cuál es el plazo general para reclamar reintegros indebidos?", respuesta: "4 años." },
{ pregunta: "¿Qué ocurre si el cobro indebido se debe a dolo o fraude?", respuesta: "No hay plazo de prescripción." },
{ pregunta: "¿Qué ocurre si el trabajador cobra indebidamente por error administrativo?", respuesta: "Debe devolverlo, pero puede fraccionarse." },
{ pregunta: "¿Qué ocurre si el trabajador está en alta de pleno derecho?", respuesta: "Se considera en alta aunque la empresa no lo haya dado." },
{ pregunta: "¿Qué situaciones generan alta de pleno derecho?", respuesta: "AT/EP y desempleo." },
{ pregunta: "¿Qué es una situación asimilada al alta?", respuesta: "Situación que permite acceder a prestaciones sin estar trabajando." },
{ pregunta: "¿Qué situación asimilada al alta es la más frecuente?", respuesta: "Inscripción como demandante de empleo." },
{ pregunta: "¿Qué ocurre si el trabajador está en excedencia forzosa?", respuesta: "Se considera asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en excedencia voluntaria?", respuesta: "No está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en convenio especial?", respuesta: "Se considera en situación de alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en huelga legal?", respuesta: "Se considera asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en prisión preventiva?", respuesta: "Se considera asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en traslado al extranjero?", respuesta: "Se mantiene el alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en IT tras extinguirse el contrato?", respuesta: "Se mantiene la protección." },
{ pregunta: "¿Qué ocurre si la empresa no ingresa las cotizaciones?", respuesta: "No afecta al derecho del trabajador." },
{ pregunta: "¿Qué ocurre si la empresa no da de alta al trabajador?", respuesta: "Puede reconocerse alta de oficio." },
{ pregunta: "¿Qué ocurre si el trabajador no cumple los requisitos de carencia?", respuesta: "No puede acceder a la prestación." },
{ pregunta: "¿Qué ocurre si el trabajador cumple requisitos pero no está en alta?", respuesta: "Debe estar en alta o asimilada." },
{ pregunta: "¿Qué es la acción protectora de la Seguridad Social?", respuesta: "El conjunto de prestaciones destinadas a cubrir situaciones de necesidad." },
{ pregunta: "¿Qué principio garantiza que todos los ciudadanos estén protegidos?", respuesta: "Universalidad." },
{ pregunta: "¿Qué principio asegura igualdad en el acceso a prestaciones?", respuesta: "Igualdad." },
{ pregunta: "¿Qué principio implica que todos contribuyen según su capacidad?", respuesta: "Contributividad." },
{ pregunta: "¿Qué principio implica que los recursos se distribuyen para cubrir necesidades?", respuesta: "Solidaridad." },
{ pregunta: "¿Qué principio implica que la acción protectora es única para todo el sistema?", respuesta: "Unidad." },
{ pregunta: "¿Qué incluye la acción protectora en asistencia sanitaria?", respuesta: "Prevención, diagnóstico, tratamiento y rehabilitación." },
{ pregunta: "¿Qué incluye la acción protectora en prestaciones económicas?", respuesta: "IT, maternidad, paternidad, IP, jubilación, muerte y supervivencia." },
{ pregunta: "¿Qué incluye la acción protectora en servicios sociales?", respuesta: "Rehabilitación, integración y asistencia social." },
{ pregunta: "¿Qué incluye la acción protectora en prestaciones familiares?", respuesta: "Asignaciones económicas por hijo a cargo." },
{ pregunta: "¿Qué es la automaticidad absoluta?", respuesta: "Prestación garantizada aunque la empresa no cotice." },
{ pregunta: "¿Qué prestaciones tienen automaticidad absoluta?", respuesta: "AT/EP y desempleo." },
{ pregunta: "¿Qué es la automaticidad relativa?", respuesta: "Prestación garantizada si el trabajador está en alta o asimilada." },
{ pregunta: "¿Qué prestaciones tienen automaticidad relativa?", respuesta: "Enfermedad común y accidente no laboral." },
{ pregunta: "¿Qué es el anticipo de prestaciones?", respuesta: "Pago provisional cuando hay dudas sobre la responsabilidad." },
{ pregunta: "¿Quién puede anticipar prestaciones?", respuesta: "El INSS o la mutua." },
{ pregunta: "¿Qué ocurre si se determina que la empresa es responsable del pago?", respuesta: "Debe reintegrar el capital coste." },
{ pregunta: "¿Qué es el capital coste de pensiones?", respuesta: "El valor actuarial de la prestación que debe pagar la empresa." },
{ pregunta: "¿Qué ocurre si la empresa incumple medidas de seguridad?", respuesta: "Se aplica recargo del 30% al 50%." },
{ pregunta: "¿Quién paga el recargo por falta de medidas de seguridad?", respuesta: "La empresa, siempre." },
{ pregunta: "¿Qué es el reintegro de prestaciones indebidas?", respuesta: "Devolución de prestaciones cobradas sin derecho." },
{ pregunta: "¿Cuál es el plazo general para reclamar reintegros indebidos?", respuesta: "4 años." },
{ pregunta: "¿Qué ocurre si el cobro indebido se debe a dolo o fraude?", respuesta: "No prescribe." },
{ pregunta: "¿Qué ocurre si el trabajador cobra indebidamente por error administrativo?", respuesta: "Debe devolverlo, pero puede fraccionarse." },
{ pregunta: "¿Qué es el alta de pleno derecho?", respuesta: "Situación en la que se considera al trabajador en alta aunque la empresa no lo haya hecho." },
{ pregunta: "¿Qué situaciones generan alta de pleno derecho?", respuesta: "AT/EP y desempleo." },
{ pregunta: "¿Qué es una situación asimilada al alta?", respuesta: "Situación que permite acceder a prestaciones sin estar trabajando." },
{ pregunta: "¿Qué situación asimilada al alta es la más frecuente?", respuesta: "Inscripción como demandante de empleo." },
{ pregunta: "¿Qué ocurre si el trabajador está en excedencia forzosa?", respuesta: "Se considera asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en excedencia voluntaria?", respuesta: "No está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en convenio especial?", respuesta: "Se considera en situación de alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en huelga legal?", respuesta: "Se considera asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en prisión preventiva?", respuesta: "Se considera asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en traslado al extranjero?", respuesta: "Se mantiene el alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en IT tras extinguirse el contrato?", respuesta: "Se mantiene la protección." },
{ pregunta: "¿Qué ocurre si la empresa no ingresa las cotizaciones?", respuesta: "No afecta al derecho del trabajador." },
{ pregunta: "¿Qué ocurre si la empresa no da de alta al trabajador?", respuesta: "Puede reconocerse alta de oficio." },
{ pregunta: "¿Qué ocurre si el trabajador no cumple los requisitos de carencia?", respuesta: "No puede acceder a la prestación." },
{ pregunta: "¿Qué ocurre si el trabajador cumple requisitos pero no está en alta?", respuesta: "Debe estar en alta o asimilada." },
{ pregunta: "¿Qué es una prestación contributiva?", respuesta: "Prestación que exige cotización previa." },
{ pregunta: "¿Qué es una prestación no contributiva?", respuesta: "Prestación que no exige cotización previa." },
{ pregunta: "¿Qué prestación cubre la muerte y supervivencia?", respuesta: "Viudedad, orfandad y auxilio por defunción." },
{ pregunta: "¿Qué prestación cubre la pérdida temporal de ingresos por enfermedad?", respuesta: "Incapacidad temporal." },
{ pregunta: "¿Qué prestación cubre la pérdida permanente de capacidad laboral?", respuesta: "Incapacidad permanente." },
{ pregunta: "¿Qué prestación cubre la falta de ingresos por cese involuntario?", respuesta: "Desempleo." },
{ pregunta: "¿Qué prestación cubre la maternidad y paternidad?", respuesta: "Nacimiento y cuidado del menor." },
{ pregunta: "¿Qué prestación cubre el cuidado de menores con cáncer?", respuesta: "Cuidado de menores con enfermedad grave." },
{ pregunta: "¿Qué organismo gestiona la mayoría de prestaciones?", respuesta: "El INSS." },
{ pregunta: "¿Qué organismo gestiona AT/EP?", respuesta: "Mutuas colaboradoras." },
{ pregunta: "¿Qué organismo gestiona desempleo?", respuesta: "SEPE." },
{ pregunta: "¿Qué organismo gestiona pensiones no contributivas?", respuesta: "IMSERSO." },
{ pregunta: "¿Qué organismo gestiona servicios sociales complementarios?", respuesta: "IMSERSO." },
{ pregunta: "¿Qué ocurre si el trabajador está en situación de alta presunta?", respuesta: "Se considera en alta a efectos de prestaciones." },
{ pregunta: "¿Qué es el alta presunta?", respuesta: "Alta reconocida cuando hay indicios suficientes de relación laboral." },
{ pregunta: "¿Qué ocurre si el trabajador sufre AT sin estar dado de alta?", respuesta: "Se reconoce alta de pleno derecho." },
{ pregunta: "¿Qué ocurre si el trabajador sufre EP sin estar dado de alta?", respuesta: "Se reconoce alta de pleno derecho." },
{ pregunta: "¿Qué ocurre si el trabajador está en situación de paro involuntario?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en paro voluntario?", respuesta: "No está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en excedencia por cuidado de hijos?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en excedencia por cuidado de familiares?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en suspensión por violencia de género?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en vacaciones retribuidas no disfrutadas?", respuesta: "Se considera en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en periodo de prueba no superado?", respuesta: "Está en alta hasta la extinción." },
{ pregunta: "¿Qué ocurre si el trabajador está en prácticas no laborales?", respuesta: "No está en alta salvo cotización." },
{ pregunta: "¿Qué ocurre si el trabajador está en formación profesional dual?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en ERTE?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en suspensión por fuerza mayor?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en reducción de jornada por guarda legal?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en reducción por cuidado de familiar?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en IT derivada de AT?", respuesta: "Tiene automaticidad absoluta." },
{ pregunta: "¿Qué ocurre si el trabajador está en IT derivada de enfermedad común?", respuesta: "Tiene automaticidad relativa." },
{ pregunta: "¿Qué ocurre si el trabajador está en desempleo contributivo?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en subsidio por desempleo?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en jubilación activa?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en jubilación parcial?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en jubilación flexible?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en situación de convenio especial tras despido?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en situación de convenio especial voluntario?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en situación de convenio especial por ERE?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en situación de incapacidad permanente?", respuesta: "No está en alta salvo revisión." },
{ pregunta: "¿Qué ocurre si el trabajador está en revisión de incapacidad permanente?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en prisión cumpliendo condena?", respuesta: "No está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en libertad condicional?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en retorno voluntario al país de origen?", respuesta: "No está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en misión diplomática?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en organismos internacionales?", respuesta: "Puede estar en convenio especial." },
{ pregunta: "¿Qué ocurre si el trabajador está en servicio militar obligatorio?", respuesta: "No está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en servicio social sustitutivo?", respuesta: "No está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en prácticas académicas externas?", respuesta: "Está en alta si cotiza." },
{ pregunta: "¿Qué ocurre si el trabajador está en prácticas extracurriculares?", respuesta: "Está en alta si cotiza." },
{ pregunta: "¿Qué finalidad tiene la acción protectora?", respuesta: "Cubrir situaciones de necesidad mediante prestaciones." },
{ pregunta: "¿Qué principio garantiza que la protección se aplica a todos por igual?", respuesta: "Igualdad." },
{ pregunta: "¿Qué principio asegura que el sistema es único y coherente?", respuesta: "Unidad." },
{ pregunta: "¿Qué principio implica que todos contribuyen según su capacidad económica?", respuesta: "Contributividad." },
{ pregunta: "¿Qué principio implica que los recursos se distribuyen para ayudar a quien lo necesita?", respuesta: "Solidaridad." },
{ pregunta: "¿Qué principio garantiza que la protección se extiende a toda la población?", respuesta: "Universalidad." },
{ pregunta: "¿Qué cubre la asistencia sanitaria dentro de la acción protectora?", respuesta: "Prevención, diagnóstico, tratamiento y rehabilitación." },
{ pregunta: "¿Qué cubren las prestaciones económicas dentro de la acción protectora?", respuesta: "Pérdidas de ingresos por contingencias protegidas." },
{ pregunta: "¿Qué cubren los servicios sociales dentro de la acción protectora?", respuesta: "Rehabilitación e integración social." },
{ pregunta: "¿Qué cubren las prestaciones familiares dentro de la acción protectora?", respuesta: "Asignaciones por hijo a cargo." },
{ pregunta: "¿Qué es una prestación contributiva?", respuesta: "Exige cotización previa." },
{ pregunta: "¿Qué es una prestación no contributiva?", respuesta: "No exige cotización previa." },
{ pregunta: "¿Qué es una contingencia profesional?", respuesta: "Accidente de trabajo o enfermedad profesional." },
{ pregunta: "¿Qué es una contingencia común?", respuesta: "Enfermedad común o accidente no laboral." },
{ pregunta: "¿Qué organismo gestiona la mayoría de prestaciones económicas?", respuesta: "El INSS." },
{ pregunta: "¿Qué organismo gestiona AT y EP?", respuesta: "Las mutuas colaboradoras." },
{ pregunta: "¿Qué organismo gestiona el desempleo?", respuesta: "El SEPE." },
{ pregunta: "¿Qué organismo gestiona las pensiones no contributivas?", respuesta: "El IMSERSO." },
{ pregunta: "¿Qué organismo gestiona servicios sociales complementarios?", respuesta: "El IMSERSO." },
{ pregunta: "¿Qué es la automaticidad en el pago de prestaciones?", respuesta: "Garantía de cobro aunque falten cotizaciones." },
{ pregunta: "¿Qué es la automaticidad absoluta?", respuesta: "Prestación garantizada aunque la empresa no cotice." },
{ pregunta: "¿Qué es la automaticidad relativa?", respuesta: "Prestación garantizada si el trabajador está en alta o asimilada." },
{ pregunta: "¿Qué prestaciones tienen automaticidad absoluta?", respuesta: "AT/EP y desempleo." },
{ pregunta: "¿Qué prestaciones tienen automaticidad relativa?", respuesta: "Enfermedad común y accidente no laboral." },
{ pregunta: "¿Qué es el anticipo de prestaciones?", respuesta: "Pago provisional cuando hay dudas sobre la responsabilidad." },
{ pregunta: "¿Quién puede anticipar prestaciones?", respuesta: "El INSS o la mutua." },
{ pregunta: "¿Qué ocurre si la empresa es responsable del pago tras un anticipo?", respuesta: "Debe reintegrar el capital coste." },
{ pregunta: "¿Qué es el capital coste de pensiones?", respuesta: "Valor actuarial de la prestación que debe pagar la empresa." },
{ pregunta: "¿Qué ocurre si la empresa incumple medidas de seguridad?", respuesta: "Se aplica recargo del 30% al 50%." },
{ pregunta: "¿Quién paga el recargo por falta de medidas de seguridad?", respuesta: "La empresa, siempre." },
{ pregunta: "¿Qué es el reintegro de prestaciones indebidas?", respuesta: "Devolución de prestaciones cobradas sin derecho." },
{ pregunta: "¿Cuál es el plazo general para reclamar reintegros indebidos?", respuesta: "4 años." },
{ pregunta: "¿Qué ocurre si el cobro indebido se debe a fraude?", respuesta: "No prescribe." },
{ pregunta: "¿Qué ocurre si el cobro indebido se debe a error administrativo?", respuesta: "Debe devolverse, pero puede fraccionarse." },
{ pregunta: "¿Qué es el alta de pleno derecho?", respuesta: "Alta reconocida aunque la empresa no haya dado de alta." },
{ pregunta: "¿Qué situaciones generan alta de pleno derecho?", respuesta: "AT/EP y desempleo." },
{ pregunta: "¿Qué es una situación asimilada al alta?", respuesta: "Situación que permite acceder a prestaciones sin trabajar." },
{ pregunta: "¿Qué situación asimilada al alta es la más habitual?", respuesta: "Inscripción como demandante de empleo." },
{ pregunta: "¿Qué ocurre si el trabajador está en excedencia forzosa?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en excedencia voluntaria?", respuesta: "No está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en convenio especial?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en huelga legal?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en prisión preventiva?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en prisión cumpliendo condena?", respuesta: "No está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en traslado al extranjero?", respuesta: "Se mantiene el alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en IT tras extinguirse el contrato?", respuesta: "Se mantiene la protección." },
{ pregunta: "¿Qué ocurre si la empresa no ingresa cotizaciones?", respuesta: "No afecta al derecho del trabajador." },
{ pregunta: "¿Qué ocurre si la empresa no da de alta al trabajador?", respuesta: "Puede reconocerse alta de oficio." },
{ pregunta: "¿Qué ocurre si el trabajador no cumple la carencia exigida?", respuesta: "No puede acceder a la prestación." },
{ pregunta: "¿Qué ocurre si el trabajador cumple carencia pero no está en alta?", respuesta: "Debe estar en alta o asimilada." },
{ pregunta: "¿Qué ocurre si el trabajador está en paro involuntario?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en paro voluntario?", respuesta: "No está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en excedencia por cuidado de hijos?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en excedencia por cuidado de familiares?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en suspensión por violencia de género?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en vacaciones retribuidas no disfrutadas?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en periodo de prueba no superado?", respuesta: "Está en alta hasta la extinción." },
{ pregunta: "¿Qué ocurre si el trabajador está en prácticas no laborales?", respuesta: "No está en alta salvo cotización." },
{ pregunta: "¿Qué ocurre si el trabajador está en formación profesional dual?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en ERTE?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en suspensión por fuerza mayor?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en reducción de jornada por guarda legal?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en reducción por cuidado de familiar?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en IT por AT?", respuesta: "Tiene automaticidad absoluta." },
{ pregunta: "¿Qué ocurre si el trabajador está en IT por enfermedad común?", respuesta: "Tiene automaticidad relativa." },
{ pregunta: "¿Qué ocurre si el trabajador está en desempleo contributivo?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en subsidio por desempleo?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en jubilación activa?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en jubilación parcial?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en jubilación flexible?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en convenio especial tras despido?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en convenio especial voluntario?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en convenio especial por ERE?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en incapacidad permanente?", respuesta: "No está en alta salvo revisión." },
{ pregunta: "¿Qué ocurre si el trabajador está en revisión de incapacidad permanente?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en libertad condicional?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en retorno voluntario al país de origen?", respuesta: "No está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en misión diplomática?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en organismos internacionales?", respuesta: "Puede estar en convenio especial." },
{ pregunta: "¿Qué ocurre si el trabajador está en servicio militar obligatorio?", respuesta: "No está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en servicio social sustitutivo?", respuesta: "No está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en prácticas académicas externas?", respuesta: "Está en alta si cotiza." },
{ pregunta: "¿Qué ocurre si el trabajador está en prácticas extracurriculares?", respuesta: "Está en alta si cotiza." },
{ pregunta: "¿Qué ocurre si el trabajador está en situación de alta presunta?", respuesta: "Se considera en alta." },
{ pregunta: "¿Qué es el alta presunta?", respuesta: "Alta reconocida cuando hay indicios de relación laboral." },
{ pregunta: "¿Qué ocurre si el trabajador sufre AT sin estar dado de alta?", respuesta: "Se reconoce alta de pleno derecho." },
{ pregunta: "¿Qué ocurre si el trabajador sufre EP sin estar dado de alta?", respuesta: "Se reconoce alta de pleno derecho." },
{ pregunta: "¿Qué ocurre si el trabajador está en situación de incapacidad temporal tras despido?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en situación de maternidad tras despido?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en situación de paternidad tras despido?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en situación de riesgo durante embarazo?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en situación de riesgo durante lactancia?", respuesta: "Está en alta." },
{ pregunta: "¿Qué finalidad tiene la acción protectora de la Seguridad Social?", respuesta: "Proteger frente a situaciones de necesidad." },
{ pregunta: "¿Qué principio garantiza que la protección se aplica sin discriminación?", respuesta: "Igualdad." },
{ pregunta: "¿Qué principio asegura que el sistema es único y coherente?", respuesta: "Unidad." },
{ pregunta: "¿Qué principio implica que todos contribuyen según su capacidad económica?", respuesta: "Contributividad." },
{ pregunta: "¿Qué principio implica que los recursos se distribuyen para ayudar a quien lo necesita?", respuesta: "Solidaridad." },
{ pregunta: "¿Qué principio garantiza que la protección se extiende a toda la población?", respuesta: "Universalidad." },
{ pregunta: "¿Qué cubre la asistencia sanitaria dentro de la acción protectora?", respuesta: "Prevención, diagnóstico, tratamiento y rehabilitación." },
{ pregunta: "¿Qué cubren las prestaciones económicas dentro de la acción protectora?", respuesta: "Pérdida de ingresos por contingencias protegidas." },
{ pregunta: "¿Qué cubren los servicios sociales dentro de la acción protectora?", respuesta: "Rehabilitación e integración social." },
{ pregunta: "¿Qué cubren las prestaciones familiares dentro de la acción protectora?", respuesta: "Asignaciones por hijo a cargo." },
{ pregunta: "¿Qué es una prestación contributiva?", respuesta: "Exige cotización previa." },
{ pregunta: "¿Qué es una prestación no contributiva?", respuesta: "No exige cotización previa." },
{ pregunta: "¿Qué es una contingencia profesional?", respuesta: "Accidente de trabajo o enfermedad profesional." },
{ pregunta: "¿Qué es una contingencia común?", respuesta: "Enfermedad común o accidente no laboral." },
{ pregunta: "¿Qué organismo gestiona la mayoría de prestaciones económicas?", respuesta: "El INSS." },
{ pregunta: "¿Qué organismo gestiona AT y EP?", respuesta: "Las mutuas colaboradoras." },
{ pregunta: "¿Qué organismo gestiona el desempleo?", respuesta: "El SEPE." },
{ pregunta: "¿Qué organismo gestiona las pensiones no contributivas?", respuesta: "El IMSERSO." },
{ pregunta: "¿Qué organismo gestiona servicios sociales complementarios?", respuesta: "El IMSERSO." },
{ pregunta: "¿Qué es la automaticidad en el pago de prestaciones?", respuesta: "Garantía de cobro aunque falten cotizaciones." },
{ pregunta: "¿Qué es la automaticidad absoluta?", respuesta: "Prestación garantizada aunque la empresa no cotice." },
{ pregunta: "¿Qué es la automaticidad relativa?", respuesta: "Prestación garantizada si el trabajador está en alta o asimilada." },
{ pregunta: "¿Qué prestaciones tienen automaticidad absoluta?", respuesta: "AT/EP y desempleo." },
{ pregunta: "¿Qué prestaciones tienen automaticidad relativa?", respuesta: "Enfermedad común y accidente no laboral." },
{ pregunta: "¿Qué es el anticipo de prestaciones?", respuesta: "Pago provisional cuando hay dudas sobre la responsabilidad." },
{ pregunta: "¿Quién puede anticipar prestaciones?", respuesta: "El INSS o la mutua." },
{ pregunta: "¿Qué ocurre si la empresa es responsable del pago tras un anticipo?", respuesta: "Debe reintegrar el capital coste." },
{ pregunta: "¿Qué es el capital coste de pensiones?", respuesta: "Valor actuarial de la prestación que debe pagar la empresa." },
{ pregunta: "¿Qué ocurre si la empresa incumple medidas de seguridad?", respuesta: "Se aplica recargo del 30% al 50%." },
{ pregunta: "¿Quién paga el recargo por falta de medidas de seguridad?", respuesta: "La empresa, siempre." },
{ pregunta: "¿Qué es el reintegro de prestaciones indebidas?", respuesta: "Devolución de prestaciones cobradas sin derecho." },
{ pregunta: "¿Cuál es el plazo general para reclamar reintegros indebidos?", respuesta: "4 años." },
{ pregunta: "¿Qué ocurre si el cobro indebido se debe a fraude?", respuesta: "No prescribe." },
{ pregunta: "¿Qué ocurre si el cobro indebido se debe a error administrativo?", respuesta: "Debe devolverse, pero puede fraccionarse." },
{ pregunta: "¿Qué es el alta de pleno derecho?", respuesta: "Alta reconocida aunque la empresa no haya dado de alta." },
{ pregunta: "¿Qué situaciones generan alta de pleno derecho?", respuesta: "AT/EP y desempleo." },
{ pregunta: "¿Qué es una situación asimilada al alta?", respuesta: "Situación que permite acceder a prestaciones sin trabajar." },
{ pregunta: "¿Qué situación asimilada al alta es la más habitual?", respuesta: "Inscripción como demandante de empleo." },
{ pregunta: "¿Qué ocurre si el trabajador está en excedencia forzosa?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en excedencia voluntaria?", respuesta: "No está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en convenio especial?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en huelga legal?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en prisión preventiva?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en prisión cumpliendo condena?", respuesta: "No está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en traslado al extranjero?", respuesta: "Se mantiene el alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en IT tras extinguirse el contrato?", respuesta: "Se mantiene la protección." },
{ pregunta: "¿Qué ocurre si la empresa no ingresa cotizaciones?", respuesta: "No afecta al derecho del trabajador." },
{ pregunta: "¿Qué ocurre si la empresa no da de alta al trabajador?", respuesta: "Puede reconocerse alta de oficio." },
{ pregunta: "¿Qué ocurre si el trabajador no cumple la carencia exigida?", respuesta: "No puede acceder a la prestación." },
{ pregunta: "¿Qué ocurre si el trabajador cumple carencia pero no está en alta?", respuesta: "Debe estar en alta o asimilada." },
{ pregunta: "¿Qué ocurre si el trabajador está en paro involuntario?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en paro voluntario?", respuesta: "No está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en excedencia por cuidado de hijos?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en excedencia por cuidado de familiares?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en suspensión por violencia de género?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en vacaciones retribuidas no disfrutadas?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en periodo de prueba no superado?", respuesta: "Está en alta hasta la extinción." },
{ pregunta: "¿Qué ocurre si el trabajador está en prácticas no laborales?", respuesta: "No está en alta salvo cotización." },
{ pregunta: "¿Qué ocurre si el trabajador está en formación profesional dual?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en ERTE?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en suspensión por fuerza mayor?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en reducción de jornada por guarda legal?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en reducción por cuidado de familiar?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en IT por AT?", respuesta: "Tiene automaticidad absoluta." },
{ pregunta: "¿Qué ocurre si el trabajador está en IT por enfermedad común?", respuesta: "Tiene automaticidad relativa." },
{ pregunta: "¿Qué ocurre si el trabajador está en desempleo contributivo?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en subsidio por desempleo?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en jubilación activa?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en jubilación parcial?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en jubilación flexible?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en convenio especial tras despido?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en convenio especial voluntario?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en convenio especial por ERE?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en incapacidad permanente?", respuesta: "No está en alta salvo revisión." },
{ pregunta: "¿Qué ocurre si el trabajador está en revisión de incapacidad permanente?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en libertad condicional?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en retorno voluntario al país de origen?", respuesta: "No está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en misión diplomática?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en organismos internacionales?", respuesta: "Puede estar en convenio especial." },
{ pregunta: "¿Qué ocurre si el trabajador está en servicio militar obligatorio?", respuesta: "No está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en servicio social sustitutivo?", respuesta: "No está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en prácticas académicas externas?", respuesta: "Está en alta si cotiza." },
{ pregunta: "¿Qué ocurre si el trabajador está en prácticas extracurriculares?", respuesta: "Está en alta si cotiza." },
{ pregunta: "¿Qué ocurre si el trabajador está en situación de alta presunta?", respuesta: "Se considera en alta." },
{ pregunta: "¿Qué es el alta presunta?", respuesta: "Alta reconocida cuando hay indicios de relación laboral." },
{ pregunta: "¿Qué ocurre si el trabajador sufre AT sin estar dado de alta?", respuesta: "Se reconoce alta de pleno derecho." },
{ pregunta: "¿Qué ocurre si el trabajador sufre EP sin estar dado de alta?", respuesta: "Se reconoce alta de pleno derecho." },
{ pregunta: "¿Qué ocurre si el trabajador está en situación de maternidad tras despido?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en situación de paternidad tras despido?", respuesta: "Está asimilado al alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en situación de riesgo durante embarazo?", respuesta: "Está en alta." },
{ pregunta: "¿Qué ocurre si el trabajador está en situación de riesgo durante lactancia?", respuesta: "Está en alta." }
];