const preguntas = [
{ pregunta: "¿Qué prestación se reconoce a un mayor de 65 años sin recursos?", respuesta: "Pensión No Contributiva de Jubilación." },
{ pregunta: "¿Qué prestación se reconoce a un mayor de 18 años con discapacidad ≥65% sin recursos?", respuesta: "Pensión No Contributiva de Invalidez." },
{ pregunta: "¿Qué prestación cubre la vulnerabilidad económica extrema?", respuesta: "Ingreso Mínimo Vital." },
{ pregunta: "¿Qué organismo gestiona las PNC?", respuesta: "IMSERSO y Comunidades Autónomas." },
{ pregunta: "¿Qué organismo gestiona el IMV?", respuesta: "INSS." },
{ pregunta: "¿Qué grado de discapacidad exige la PNC de invalidez?", respuesta: "Igual o superior al 65%." },
{ pregunta: "¿Qué grado de discapacidad da derecho al complemento del 50% en PNC?", respuesta: "Igual o superior al 75% con necesidad de tercera persona." },
{ pregunta: "¿Qué edad mínima se exige para la PNC de invalidez?", respuesta: "18 años." },
{ pregunta: "¿Qué edad máxima se exige para la PNC de invalidez?", respuesta: "65 años." },
{ pregunta: "¿Qué requisito de residencia exige la PNC?", respuesta: "5 años en España, 2 consecutivos inmediatamente anteriores." },
{ pregunta: "¿Qué requisito de residencia exige el IMV?", respuesta: "1 año de residencia legal y efectiva." },
{ pregunta: "¿Qué requisito de edad exige el IMV individual?", respuesta: "Entre 23 y 65 años, salvo excepciones." },
{ pregunta: "¿Qué excepción permite pedir IMV con 18 años?", respuesta: "Ser huérfano absoluto o víctima de violencia de género." },
{ pregunta: "¿Qué excepción permite pedir IMV con 20 años?", respuesta: "Tener un menor a cargo." },
{ pregunta: "¿Qué documento acredita la unidad de convivencia?", respuesta: "Certificado histórico de empadronamiento." },
{ pregunta: "¿Cuántos años de vida independiente exige el IMV para menores de 30?", respuesta: "2 años." },
{ pregunta: "¿Cuántos meses de ingresos propios exige el IMV para menores de 30?", respuesta: "12 meses de alta en Seguridad Social." },
{ pregunta: "¿Qué ocurre si un emancipado no tiene ingresos suficientes?", respuesta: "Sigue formando parte de la unidad de convivencia de los padres." },
{ pregunta: "¿Qué ocurre si un emancipado no cumple 12 meses de independencia?", respuesta: "No puede pedir IMV individual." },
{ pregunta: "¿Qué ocurre si un emancipado cumple los 12 meses y 2 años?", respuesta: "Puede pedir IMV individual." },
{ pregunta: "¿Qué prestación puede cobrar un hijo con discapacidad ≥65%?", respuesta: "PNC de invalidez o IMV, según requisitos." },
{ pregunta: "¿La discapacidad para hijo a cargo es del hijo o del progenitor?", respuesta: "Del hijo." },
{ pregunta: "¿Qué discapacidad exige hijo a cargo mayor de 18 años?", respuesta: "Igual o superior al 65%." },
{ pregunta: "¿Puede un hijo con PNC seguir siendo hijo a cargo?", respuesta: "Sí, si convive y depende económicamente." },
{ pregunta: "¿Puede un hijo con IMV seguir siendo hijo a cargo?", respuesta: "Sí, si convive y depende económicamente." },
{ pregunta: "¿Es compatible la PNC con el IMV?", respuesta: "No." },
{ pregunta: "¿Es compatible la PNC con una pensión contributiva?", respuesta: "No." },
{ pregunta: "¿Es compatible el IMV con una pensión contributiva baja?", respuesta: "Sí, si no supera el umbral." },
{ pregunta: "¿Son compatibles las ayudas autonómicas con PNC?", respuesta: "Sí." },
{ pregunta: "¿Son compatibles las ayudas autonómicas con IMV?", respuesta: "Sí." },
{ pregunta: "¿Qué ocurre si la unidad de convivencia supera el límite de ingresos del IMV?", respuesta: "No se reconoce la prestación." },
{ pregunta: "¿Qué ocurre si los ingresos son inferiores al umbral del IMV?", respuesta: "Se reconoce la diferencia hasta el umbral." },
{ pregunta: "¿Qué ocurre si se superan los ingresos por un mes puntual?", respuesta: "Se revisa la prestación, pero no se extingue automáticamente." },
{ pregunta: "¿Qué ocurre si se ocultan ingresos en el IMV?", respuesta: "Sanción y devolución de cantidades." },
{ pregunta: "¿Qué ocurre si se pierde temporalmente la convivencia?", respuesta: "Puede mantenerse la unidad si es por causa justificada." },
{ pregunta: "¿Qué es la unidad de convivencia?", respuesta: "Personas que viven juntas y comparten gastos esenciales." },
{ pregunta: "¿Puede haber IMV para una sola persona?", respuesta: "Sí, IMV individual." },
{ pregunta: "¿Puede haber IMV para dos personas sin parentesco?", respuesta: "Sí, si comparten domicilio y gastos." },
{ pregunta: "¿Puede haber IMV para una pareja de hecho no registrada?", respuesta: "Sí, si conviven y comparten gastos." },
{ pregunta: "¿Puede haber IMV para estudiantes que comparten piso?", respuesta: "No, salvo que formen unidad económica real." },
{ pregunta: "¿Qué ocurre si un miembro de la unidad entra en prisión?", respuesta: "Se excluye temporalmente de la unidad." },
{ pregunta: "¿Qué ocurre si un miembro fallece?", respuesta: "Se recalcula la prestación." },
{ pregunta: "¿Qué ocurre si nace un hijo?", respuesta: "Se amplía la unidad y se recalcula el IMV." },
{ pregunta: "¿Qué ocurre si se separa una pareja?", respuesta: "Se crean dos unidades de convivencia." },
{ pregunta: "¿Qué ocurre si se produce violencia de género?", respuesta: "La víctima puede constituir unidad independiente." },
{ pregunta: "¿Qué ingresos computan para el IMV?", respuesta: "Todos los ingresos, incluidos salarios, pensiones y prestaciones." },
{ pregunta: "¿Qué ingresos no computan para el IMV?", respuesta: "Ayudas finalistas y becas de estudio." },
{ pregunta: "¿Qué patrimonio excluye el IMV?", respuesta: "Patrimonio superior al límite establecido según unidad." },
{ pregunta: "¿Cuenta la vivienda habitual como patrimonio para IMV?", respuesta: "No." },
{ pregunta: "¿Cuenta un coche como patrimonio para IMV?", respuesta: "Sí, salvo excepciones." },
{ pregunta: "¿Qué ocurre si se supera el patrimonio permitido?", respuesta: "Se deniega el IMV." },
{ pregunta: "¿Qué ocurre si se supera el patrimonio después de concedido?", respuesta: "Se extingue la prestación." },
{ pregunta: "¿Qué ocurre si se recibe una herencia?", respuesta: "Puede extinguir el IMV si supera límites." },
{ pregunta: "¿Qué ocurre si se gana la lotería?", respuesta: "Se extingue el IMV." },
{ pregunta: "¿Qué ocurre si se vende un inmueble?", respuesta: "El dinero recibido computa como patrimonio." },
{ pregunta: "¿Qué es la renta garantizada del IMV?", respuesta: "El umbral mínimo según unidad de convivencia." },
{ pregunta: "¿Qué es el complemento de monoparentalidad?", respuesta: "Un incremento para familias monoparentales." },
{ pregunta: "¿Qué es el complemento de vivienda?", respuesta: "Un incremento por alquiler o hipoteca." },
{ pregunta: "¿Qué es el complemento de discapacidad?", respuesta: "Un incremento por discapacidad en la unidad." },
{ pregunta: "¿Qué es el complemento de infancia?", respuesta: "Ayuda adicional por menores en la unidad." },
{ pregunta: "¿Puede una persona sin ingresos pedir IMV?", respuesta: "Sí, si cumple requisitos de residencia y unidad." },
{ pregunta: "¿Puede un extranjero pedir IMV?", respuesta: "Sí, si tiene residencia legal." },
{ pregunta: "¿Puede un solicitante de asilo pedir IMV?", respuesta: "No hasta obtener residencia legal." },
{ pregunta: "¿Puede un estudiante pedir IMV individual?", respuesta: "No, salvo independencia económica real." },
{ pregunta: "¿Puede un pensionista pedir IMV?", respuesta: "Sí, si su pensión es baja." },
{ pregunta: "¿Qué ocurre si se trabaja mientras se cobra IMV?", respuesta: "Es compatible con incentivos al empleo." },
{ pregunta: "¿Qué ocurre si se pierde el empleo cobrando IMV?", respuesta: "Se recalcula la prestación." },
{ pregunta: "¿Qué ocurre si se empieza a trabajar y se supera el umbral?", respuesta: "Puede suspenderse temporalmente." },
{ pregunta: "¿Qué ocurre si se trabaja en economía sumergida?", respuesta: "Sanción y devolución." },
{ pregunta: "¿Qué ocurre si se declara tarde un ingreso?", respuesta: "Regularización y posible sanción." },
{ pregunta: "¿Qué plazo tiene el INSS para resolver el IMV?", respuesta: "6 meses." },
{ pregunta: "¿Qué ocurre si no resuelve en 6 meses?", respuesta: "Silencio administrativo negativo." },
{ pregunta: "¿Qué plazo tiene el INSS para revisar el IMV?", respuesta: "Anualmente." },
{ pregunta: "¿Qué ocurre si no se presenta la declaración anual de ingresos?", respuesta: "Suspensión del IMV." },
{ pregunta: "¿Qué ocurre si se presenta fuera de plazo?", respuesta: "Regularización y posible sanción." },
{ pregunta: "¿Qué ocurre si se cambia de domicilio?", respuesta: "Debe comunicarse en 30 días." },
{ pregunta: "¿Qué ocurre si se cambia de unidad de convivencia?", respuesta: "Debe comunicarse en 30 días." },
{ pregunta: "¿Qué ocurre si se cambia de estado civil?", respuesta: "Debe comunicarse en 30 días." },
{ pregunta: "¿Qué ocurre si se cambia de trabajo?", respuesta: "Debe comunicarse en 30 días." },
{ pregunta: "¿Qué ocurre si se cambia de país?", respuesta: "Puede extinguir el IMV." },
{ pregunta: "¿Qué ocurre si se viaja al extranjero más de 90 días?", respuesta: "Se suspende el IMV." },
{ pregunta: "¿Qué ocurre si se viaja al extranjero más de 180 días?", respuesta: "Se extingue el IMV." },
{ pregunta: "¿Qué ocurre si se reside fuera de España?", respuesta: "No se puede cobrar IMV." },
{ pregunta: "¿Qué ocurre si se reside temporalmente fuera por estudios?", respuesta: "Puede mantenerse si se justifica." },
{ pregunta: "¿Qué ocurre si se reside fuera por motivos médicos?", respuesta: "Puede mantenerse si se justifica." },
{ pregunta: "¿Qué ocurre si se detecta fraude en el IMV?", respuesta: "Extinción, devolución y sanción." },
{ pregunta: "¿Qué ocurre si se detecta error del INSS?", respuesta: "Regularización sin sanción." },
{ pregunta: "¿Qué ocurre si se cobra indebidamente por error del beneficiario?", respuesta: "Devolución." },
{ pregunta: "¿Qué ocurre si se cobra indebidamente por ocultación?", respuesta: "Devolución y sanción." },
{ pregunta: "¿Qué ocurre si se cobra indebidamente por datos incorrectos?", respuesta: "Regularización." },
{ pregunta: "¿Qué ocurre si se fallece cobrando IMV?", respuesta: "Extinción inmediata." },
{ pregunta: "¿Qué ocurre si fallece un miembro de la unidad?", respuesta: "Revisión del importe." },
{ pregunta: "¿Qué ocurre si se incorpora un nuevo miembro?", respuesta: "Revisión del importe." },
{ pregunta: "¿Qué ocurre si se adopta un menor?", respuesta: "Revisión del IMV." },
{ pregunta: "¿Qué ocurre si se acoge a un menor?", respuesta: "Revisión del IMV." },
{ pregunta: "¿Qué prestación se reconoce a un mayor de 65 años sin recursos?", respuesta: "PNC de Jubilación." },
{ pregunta: "¿Qué prestación se reconoce a un mayor de 18 años con discapacidad ≥65%?", respuesta: "PNC de Invalidez." },
{ pregunta: "¿Qué organismo gestiona el IMV?", respuesta: "INSS." },
{ pregunta: "¿Qué organismo gestiona las PNC?", respuesta: "IMSERSO y CCAA." },
{ pregunta: "¿Qué residencia exige la PNC?", respuesta: "5 años, 2 consecutivos inmediatamente anteriores." },
{ pregunta: "¿Qué residencia exige el IMV?", respuesta: "1 año de residencia legal y efectiva." },
{ pregunta: "¿Qué edad mínima exige el IMV individual?", respuesta: "23 años." },
{ pregunta: "¿Qué excepción permite pedir IMV con 18 años?", respuesta: "Ser huérfano absoluto o víctima de violencia de género." },
{ pregunta: "¿Qué excepción permite pedir IMV con 20 años?", respuesta: "Tener un menor a cargo." },
{ pregunta: "¿Qué documento acredita la unidad de convivencia?", respuesta: "Certificado histórico de empadronamiento." },
{ pregunta: "¿Cuántos años de vida independiente exige el IMV para menores de 30?", respuesta: "2 años." },
{ pregunta: "¿Cuántos meses de ingresos propios exige el IMV para menores de 30?", respuesta: "12 meses de alta en Seguridad Social." },
{ pregunta: "¿Qué ocurre si un emancipado no tiene ingresos suficientes?", respuesta: "Sigue en la unidad de convivencia de los padres." },
{ pregunta: "¿Qué ocurre si no cumple los 12 meses de independencia?", respuesta: "No puede pedir IMV individual." },
{ pregunta: "¿Qué ocurre si cumple los 12 meses y 2 años?", respuesta: "Puede pedir IMV individual." },
{ pregunta: "¿Qué discapacidad exige hijo a cargo mayor de 18 años?", respuesta: "≥65%." },
{ pregunta: "¿La discapacidad para hijo a cargo es del hijo o del progenitor?", respuesta: "Del hijo." },
{ pregunta: "¿Puede un hijo con PNC ser hijo a cargo?", respuesta: "Sí." },
{ pregunta: "¿Puede un hijo con IMV ser hijo a cargo?", respuesta: "Sí." },
{ pregunta: "¿Puede un hijo con discapacidad ≥65% cobrar su propia prestación?", respuesta: "Sí, PNC o IMV." },
{ pregunta: "¿Es compatible la PNC con el IMV?", respuesta: "No." },
{ pregunta: "¿Es compatible la PNC con pensión contributiva?", respuesta: "No." },
{ pregunta: "¿Es compatible el IMV con pensión contributiva baja?", respuesta: "Sí." },
{ pregunta: "¿Son compatibles las ayudas autonómicas con PNC?", respuesta: "Sí." },
{ pregunta: "¿Son compatibles las ayudas autonómicas con IMV?", respuesta: "Sí." },
{ pregunta: "¿Qué ocurre si la unidad supera el límite de ingresos del IMV?", respuesta: "No se reconoce la prestación." },
{ pregunta: "¿Qué ocurre si los ingresos son inferiores al umbral del IMV?", respuesta: "Se reconoce la diferencia." },
{ pregunta: "¿Qué ocurre si se superan ingresos puntualmente?", respuesta: "Revisión, no extinción automática." },
{ pregunta: "¿Qué ocurre si se ocultan ingresos?", respuesta: "Sanción y devolución." },
{ pregunta: "¿Qué ocurre si se pierde temporalmente la convivencia?", respuesta: "Puede mantenerse la unidad." },
{ pregunta: "¿Qué es la unidad de convivencia?", respuesta: "Personas que viven juntas y comparten gastos." },
{ pregunta: "¿Puede haber IMV individual?", respuesta: "Sí." },
{ pregunta: "¿Puede haber IMV para dos personas sin parentesco?", respuesta: "Sí." },
{ pregunta: "¿Puede haber IMV para pareja no registrada?", respuesta: "Sí." },
{ pregunta: "¿Pueden estudiantes compartir piso y pedir IMV?", respuesta: "No, salvo unidad económica real." },
{ pregunta: "¿Qué ocurre si un miembro entra en prisión?", respuesta: "Se excluye temporalmente." },
{ pregunta: "¿Qué ocurre si un miembro fallece?", respuesta: "Se recalcula el IMV." },
{ pregunta: "¿Qué ocurre si nace un hijo?", respuesta: "Se recalcula el IMV." },
{ pregunta: "¿Qué ocurre si se separa una pareja?", respuesta: "Se crean dos unidades." },
{ pregunta: "¿Qué ocurre si hay violencia de género?", respuesta: "Unidad independiente." },
{ pregunta: "¿Qué ingresos computan para el IMV?", respuesta: "Todos los ingresos, incluidas prestaciones." },
{ pregunta: "¿Qué ingresos no computan para el IMV?", respuesta: "Ayudas finalistas y becas." },
{ pregunta: "¿Cuenta la vivienda habitual como patrimonio?", respuesta: "No." },
{ pregunta: "¿Cuenta un coche como patrimonio?", respuesta: "Sí, salvo excepciones." },
{ pregunta: "¿Qué ocurre si se supera el patrimonio permitido?", respuesta: "Se deniega el IMV." },
{ pregunta: "¿Qué ocurre si se supera el patrimonio tras conceder IMV?", respuesta: "Se extingue." },
{ pregunta: "¿Qué ocurre si se recibe una herencia?", respuesta: "Puede extinguir el IMV." },
{ pregunta: "¿Qué ocurre si se gana la lotería?", respuesta: "Extinción." },
{ pregunta: "¿Qué ocurre si se vende un inmueble?", respuesta: "El dinero computa como patrimonio." },
{ pregunta: "¿Qué ocurre si se recibe una donación elevada?", respuesta: "Puede extinguir el IMV." },
{ pregunta: "¿Qué es la renta garantizada del IMV?", respuesta: "El umbral mínimo según unidad." },
{ pregunta: "¿Qué es el complemento de monoparentalidad?", respuesta: "Incremento para familias monoparentales." },
{ pregunta: "¿Qué es el complemento de vivienda?", respuesta: "Incremento por alquiler o hipoteca." },
{ pregunta: "¿Qué es el complemento de discapacidad?", respuesta: "Incremento por discapacidad." },
{ pregunta: "¿Qué es el complemento de infancia?", respuesta: "Ayuda por menores en la unidad." },
{ pregunta: "¿Puede una persona sin ingresos pedir IMV?", respuesta: "Sí." },
{ pregunta: "¿Puede un extranjero pedir IMV?", respuesta: "Sí, con residencia legal." },
{ pregunta: "¿Puede un solicitante de asilo pedir IMV?", respuesta: "No hasta obtener residencia." },
{ pregunta: "¿Puede un estudiante pedir IMV individual?", respuesta: "No." },
{ pregunta: "¿Puede un pensionista pedir IMV?", respuesta: "Sí, si su pensión es baja." },
{ pregunta: "¿Qué ocurre si se trabaja cobrando IMV?", respuesta: "Es compatible con incentivos." },
{ pregunta: "¿Qué ocurre si se pierde el empleo cobrando IMV?", respuesta: "Se recalcula." },
{ pregunta: "¿Qué ocurre si se empieza a trabajar y se supera el umbral?", respuesta: "Puede suspenderse." },
{ pregunta: "¿Qué ocurre si se trabaja en negro?", respuesta: "Sanción y devolución." },
{ pregunta: "¿Qué ocurre si se declara tarde un ingreso?", respuesta: "Regularización." },
{ pregunta: "¿Qué plazo tiene el INSS para resolver IMV?", respuesta: "6 meses." },
{ pregunta: "¿Qué ocurre si no resuelve en 6 meses?", respuesta: "Silencio negativo." },
{ pregunta: "¿Qué ocurre si no se presenta la declaración anual?", respuesta: "Suspensión del IMV." },
{ pregunta: "¿Qué ocurre si se presenta fuera de plazo?", respuesta: "Regularización y posible sanción." },
{ pregunta: "¿Qué ocurre si se detecta fraude?", respuesta: "Extinción y sanción." },
{ pregunta: "¿Qué ocurre si se cambia de domicilio?", respuesta: "Debe comunicarse en 30 días." },
{ pregunta: "¿Qué ocurre si se cambia de unidad de convivencia?", respuesta: "Debe comunicarse en 30 días." },
{ pregunta: "¿Qué ocurre si se cambia de estado civil?", respuesta: "Debe comunicarse en 30 días." },
{ pregunta: "¿Qué ocurre si se cambia de trabajo?", respuesta: "Debe comunicarse en 30 días." },
{ pregunta: "¿Qué ocurre si se cambia de país?", respuesta: "Puede extinguir el IMV." },
{ pregunta: "¿Qué ocurre si se viaja al extranjero más de 90 días?", respuesta: "Suspensión." },
{ pregunta: "¿Qué ocurre si se viaja al extranjero más de 180 días?", respuesta: "Extinción." },
{ pregunta: "¿Qué ocurre si se reside fuera de España?", respuesta: "No se puede cobrar IMV." },
{ pregunta: "¿Qué ocurre si se reside fuera por estudios?", respuesta: "Puede mantenerse si se justifica." },
{ pregunta: "¿Qué ocurre si se reside fuera por motivos médicos?", respuesta: "Puede mantenerse si se justifica." },
{ pregunta: "¿Qué ocurre si se cobra indebidamente por error del INSS?", respuesta: "Regularización sin sanción." },
{ pregunta: "¿Qué ocurre si se cobra indebidamente por error del beneficiario?", respuesta: "Devolución." },
{ pregunta: "¿Qué ocurre si se cobra indebidamente por ocultación?", respuesta: "Devolución y sanción." },
{ pregunta: "¿Qué ocurre si se cobra indebidamente por datos incorrectos?", respuesta: "Regularización." },
{ pregunta: "¿Qué ocurre si se fallece cobrando IMV?", respuesta: "Extinción inmediata." },
{ pregunta: "¿Qué ocurre si fallece un miembro de la unidad?", respuesta: "Revisión del importe." },
{ pregunta: "¿Qué ocurre si se incorpora un nuevo miembro?", respuesta: "Revisión del IMV." },
{ pregunta: "¿Qué ocurre si se adopta un menor?", respuesta: "Revisión del IMV." },
{ pregunta: "¿Qué ocurre si se acoge a un menor?", respuesta: "Revisión del IMV." },
{ pregunta: "¿Qué ocurre si se detecta convivencia no declarada?", respuesta: "Sanción y revisión." },
{ pregunta: "¿Qué prestación garantiza ingresos mínimos a hogares vulnerables?", respuesta: "Ingreso Mínimo Vital." },
{ pregunta: "¿Qué prestación cubre a mayores de 65 sin recursos?", respuesta: "PNC de Jubilación." },
{ pregunta: "¿Qué prestación cubre a mayores de 18 con discapacidad ≥65%?", respuesta: "PNC de Invalidez." },
{ pregunta: "¿Qué organismo reconoce el IMV?", respuesta: "INSS." },
{ pregunta: "¿Qué organismo reconoce las PNC?", respuesta: "IMSERSO y CCAA." },
{ pregunta: "¿Qué residencia exige el IMV?", respuesta: "1 año de residencia legal y efectiva." },
{ pregunta: "¿Qué residencia exige la PNC?", respuesta: "5 años, 2 consecutivos inmediatamente anteriores." },
{ pregunta: "¿Qué edad mínima exige el IMV individual?", respuesta: "23 años." },
{ pregunta: "¿Qué edad mínima exige la PNC de invalidez?", respuesta: "18 años." },
{ pregunta: "¿Qué edad máxima exige la PNC de invalidez?", respuesta: "65 años." },
{ pregunta: "¿Qué discapacidad exige la PNC de invalidez?", respuesta: "≥65%." },
{ pregunta: "¿Qué discapacidad exige el complemento del 50% en PNC?", respuesta: "≥75% con tercera persona." },
{ pregunta: "¿Qué discapacidad exige hijo a cargo mayor de 18?", respuesta: "≥65%." },
{ pregunta: "¿La discapacidad para hijo a cargo es del hijo?", respuesta: "Sí." },
{ pregunta: "¿Puede un hijo con PNC ser hijo a cargo?", respuesta: "Sí." },
{ pregunta: "¿Puede un hijo con IMV ser hijo a cargo?", respuesta: "Sí." },
{ pregunta: "¿Puede un hijo con discapacidad cobrar IMV individual?", respuesta: "Sí, si cumple requisitos." },
{ pregunta: "¿Puede un hijo con discapacidad cobrar PNC?", respuesta: "Sí, si cumple requisitos." },
{ pregunta: "¿Es compatible PNC con IMV?", respuesta: "No." },
{ pregunta: "¿Es compatible PNC con contributiva?", respuesta: "No." },
{ pregunta: "¿Es compatible IMV con contributiva baja?", respuesta: "Sí." },
{ pregunta: "¿Son compatibles ayudas autonómicas con IMV?", respuesta: "Sí." },
{ pregunta: "¿Son compatibles ayudas autonómicas con PNC?", respuesta: "Sí." },
{ pregunta: "¿Qué documento acredita convivencia?", respuesta: "Certificado histórico de empadronamiento." },
{ pregunta: "¿Qué documento acredita ingresos?", respuesta: "Declaración de la renta." },
{ pregunta: "¿Qué documento acredita patrimonio?", respuesta: "Datos catastrales y bancarios." },
{ pregunta: "¿Qué ocurre si se ocultan ingresos en IMV?", respuesta: "Sanción y devolución." },
{ pregunta: "¿Qué ocurre si se oculta patrimonio en IMV?", respuesta: "Extinción y sanción." },
{ pregunta: "¿Qué ocurre si se supera el patrimonio permitido?", respuesta: "Denegación del IMV." },
{ pregunta: "¿Qué ocurre si se supera el patrimonio tras conceder IMV?", respuesta: "Extinción." },
{ pregunta: "¿Qué ocurre si se recibe una herencia?", respuesta: "Puede extinguir el IMV." },
{ pregunta: "¿Qué ocurre si se gana la lotería?", respuesta: "Extinción del IMV." },
{ pregunta: "¿Qué ocurre si se vende un inmueble?", respuesta: "El dinero computa como patrimonio." },
{ pregunta: "¿Qué ocurre si se recibe una donación elevada?", respuesta: "Puede extinguir el IMV." },
{ pregunta: "¿Qué ocurre si se recibe una beca de estudios?", respuesta: "No computa como ingreso." },
{ pregunta: "¿Qué ocurre si se trabaja cobrando IMV?", respuesta: "Es compatible con incentivos." },
{ pregunta: "¿Qué ocurre si se pierde el empleo cobrando IMV?", respuesta: "Se recalcula." },
{ pregunta: "¿Qué ocurre si se empieza a trabajar y se supera el umbral?", respuesta: "Puede suspenderse." },
{ pregunta: "¿Qué ocurre si se trabaja en negro?", respuesta: "Sanción y devolución." },
{ pregunta: "¿Qué ocurre si se declara tarde un ingreso?", respuesta: "Regularización." },
{ pregunta: "¿Qué ocurre si se cambia de domicilio?", respuesta: "Debe comunicarse en 30 días." },
{ pregunta: "¿Qué ocurre si se cambia de unidad de convivencia?", respuesta: "Debe comunicarse en 30 días." },
{ pregunta: "¿Qué ocurre si se cambia de estado civil?", respuesta: "Debe comunicarse en 30 días." },
{ pregunta: "¿Qué ocurre si se cambia de trabajo?", respuesta: "Debe comunicarse en 30 días." },
{ pregunta: "¿Qué ocurre si se cambia de país?", respuesta: "Puede extinguir el IMV." },
{ pregunta: "¿Qué ocurre si se viaja al extranjero más de 90 días?", respuesta: "Suspensión del IMV." },
{ pregunta: "¿Qué ocurre si se viaja al extranjero más de 180 días?", respuesta: "Extinción del IMV." },
{ pregunta: "¿Qué ocurre si se reside fuera de España?", respuesta: "No se puede cobrar IMV." },
{ pregunta: "¿Qué ocurre si se reside fuera por estudios?", respuesta: "Puede mantenerse si se justifica." },
{ pregunta: "¿Qué ocurre si se reside fuera por motivos médicos?", respuesta: "Puede mantenerse si se justifica." },
{ pregunta: "¿Qué ocurre si un miembro entra en prisión?", respuesta: "Se excluye temporalmente." },
{ pregunta: "¿Qué ocurre si un miembro fallece?", respuesta: "Revisión del IMV." },
{ pregunta: "¿Qué ocurre si nace un hijo?", respuesta: "Revisión del IMV." },
{ pregunta: "¿Qué ocurre si se adopta un menor?", respuesta: "Revisión del IMV." },
{ pregunta: "¿Qué ocurre si se acoge a un menor?", respuesta: "Revisión del IMV." },
{ pregunta: "¿Qué ocurre si se detecta fraude en IMV?", respuesta: "Extinción y sanción." },
{ pregunta: "¿Qué ocurre si se detecta error del INSS?", respuesta: "Regularización sin sanción." },
{ pregunta: "¿Qué ocurre si se cobra indebidamente por error del beneficiario?", respuesta: "Devolución." },
{ pregunta: "¿Qué ocurre si se cobra indebidamente por ocultación?", respuesta: "Devolución y sanción." },
{ pregunta: "¿Qué ocurre si se cobra indebidamente por datos incorrectos?", respuesta: "Regularización." },
{ pregunta: "¿Qué ocurre si se fallece cobrando IMV?", respuesta: "Extinción inmediata." },
{ pregunta: "¿Qué ocurre si se detecta convivencia no declarada?", respuesta: "Sanción y revisión." },
{ pregunta: "¿Qué ocurre si se detecta empadronamiento ficticio?", respuesta: "Denegación o extinción." },
{ pregunta: "¿Qué ocurre si se detecta domicilio falso?", respuesta: "Extinción y sanción." },
{ pregunta: "¿Qué ocurre si se detecta unidad ficticia?", respuesta: "Extinción y sanción." },
{ pregunta: "¿Qué es la renta garantizada del IMV?", respuesta: "El umbral mínimo según unidad." },
{ pregunta: "¿Qué es el complemento de monoparentalidad?", respuesta: "Incremento para familias monoparentales." },
{ pregunta: "¿Qué es el complemento de vivienda?", respuesta: "Incremento por alquiler o hipoteca." },
{ pregunta: "¿Qué es el complemento de discapacidad?", respuesta: "Incremento por discapacidad." },
{ pregunta: "¿Qué es el complemento de infancia?", respuesta: "Ayuda por menores en la unidad." },
{ pregunta: "¿Qué ingresos computan para IMV?", respuesta: "Todos los ingresos, incluidas prestaciones." },
{ pregunta: "¿Qué ingresos no computan para IMV?", respuesta: "Ayudas finalistas y becas." },
{ pregunta: "¿Qué patrimonio excluye IMV?", respuesta: "Patrimonio superior al límite." },
{ pregunta: "¿Cuenta la vivienda habitual como patrimonio?", respuesta: "No." },
{ pregunta: "¿Cuenta un vehículo como patrimonio?", respuesta: "Sí, salvo excepciones." },
{ pregunta: "¿Puede un extranjero pedir IMV?", respuesta: "Sí, con residencia legal." },
{ pregunta: "¿Puede un solicitante de asilo pedir IMV?", respuesta: "No hasta residencia legal." },
{ pregunta: "¿Puede un estudiante pedir IMV individual?", respuesta: "No." },
{ pregunta: "¿Puede un pensionista pedir IMV?", respuesta: "Sí, si su pensión es baja." },
{ pregunta: "¿Puede un trabajador pedir IMV?", respuesta: "Sí, si sus ingresos son insuficientes." },
{ pregunta: "¿Qué ocurre si se superan ingresos por un mes puntual?", respuesta: "Revisión, no extinción automática." },
{ pregunta: "¿Qué ocurre si se superan ingresos de forma continuada?", respuesta: "Extinción del IMV." },
{ pregunta: "¿Qué ocurre si se pierde la convivencia por hospitalización?", respuesta: "Puede mantenerse la unidad." },
{ pregunta: "¿Qué ocurre si se pierde la convivencia por estudios?", respuesta: "Puede mantenerse si es temporal." },
{ pregunta: "¿Qué ocurre si se pierde la convivencia por trabajo temporal?", respuesta: "Puede mantenerse si es temporal." },
{ pregunta: "¿Qué ocurre si se separa una pareja con IMV?", respuesta: "Se crean dos unidades." },
{ pregunta: "¿Qué ocurre si se forma una nueva pareja?", respuesta: "Se recalcula el IMV." },
{ pregunta: "¿Qué ocurre si se incorpora un cuidador?", respuesta: "No forma unidad salvo convivencia estable." },
{ pregunta: "¿Qué ocurre si se incorpora un familiar?", respuesta: "Puede formar unidad si conviven." },
{ pregunta: "¿Qué ocurre si se incorpora un no familiar?", respuesta: "Puede formar unidad si comparten gastos." },
{ pregunta: "¿Qué plazo tiene el INSS para resolver IMV?", respuesta: "6 meses." },
{ pregunta: "¿Qué tipo de silencio tiene el IMV?", respuesta: "Negativo." },
{ pregunta: "¿Qué ocurre si no se presenta la declaración anual?", respuesta: "Suspensión del IMV." },
{ pregunta: "¿Qué ocurre si se presenta fuera de plazo?", respuesta: "Regularización y posible sanción." },
{ pregunta: "¿Qué ocurre si se detecta error en la declaración anual?", respuesta: "Regularización." }
];
