const preguntas = [
  { pregunta: "¿Qué dos modalidades de protección estructuran el campo de aplicación de la SS?", respuesta: "La modalidad contributiva (basada en la actividad profesional) y la modalidad no contributiva (universal, basada en la residencia)." },
  { pregunta: "¿Qué principio rige la inclusión en el campo de aplicación del sistema de la SS?", respuesta: "El principio de territorialidad: se aplica a españoles y extranjeros que residan o se encuentren legalmente en España." },
  { pregunta: "¿Cuáles son los dos grandes bloques en los que se divide el sistema de la SS?", respuesta: "El Régimen General (trabajadores por cuenta ajena) y los Regímenes Especiales (RETA, Mar y Carbón)." },
  { pregunta: "¿Qué colectivos con regulación propia se integran dentro del Régimen General como 'Sistemas Especiales'?", respuesta: "Entre otros, el Sistema Especial de Trabajadores Agrarios (SETA) y el Sistema Especial de Empleados de Hogar." },
  { pregunta: "¿Quiénes están incluidos obligatoriamente en el Régimen General de la SS?", respuesta: "Los trabajadores por cuenta ajena, el personal civil no funcionario de la Administración y los socios trabajadores de sociedades de capital." },
  { pregunta: "¿Qué familiares del empresario están excluidos por norma general del Régimen General por cuenta ajena?", respuesta: "El cónyuge, descendientes, ascendientes y demás parientes por consanguinidad hasta el segundo grado inclusive que convivan con él." },
  { pregunta: "¿Cuál es la excepción para que un hijo menor de 30 años pueda cotizar en el Régimen General del padre empresario?", respuesta: "Que sea contratado como trabajador por cuenta ajena conviviendo con él, quedando excluido de la protección por desempleo." },
  { pregunta: "¿Qué criterio define la inclusión obligatoria en el RETA (Autónomos)?", respuesta: "Realizar de forma habitual, personal, directa y a título lucrativo una actividad económica sin sujeción a contrato de trabajo." },
  { pregunta: "¿Están incluidos los extranjeros en la modalidad no contributiva de la Seguridad Social?", respuesta: "Sí, los extranjeros que residan legalmente en territorio español tienen derecho a las prestaciones de modalidad no contributiva." },
  { pregunta: "¿Qué ocurre con los trabajadores autónomos económicamente dependientes (TRADE) respecto al RETA?", respuesta: "Están incluidos obligatoriamente en el RETA, pero disfrutan de una regulación específica en sus contratos y coberturas." },
  { pregunta: "¿Qué colectivo integra el Régimen Especial de la Seguridad Social de los Trabajadores del Mar?", respuesta: "Los trabajadores por cuenta ajena o propia que ejerzan su actividad en el sector marítimo-pesquero, marina mercante y acuicultura." },
  { pregunta: "¿Quién determina anualmente las bases y condiciones de los Regímenes Especiales?", respuesta: "La Ley de Presupuestos Generales del Estado (PGE), respetando los principios de homogeneidad con el Régimen General." },
  { pregunta: "¿Están incluidos los miembros de cooperativas de producción en el campo de aplicación?", respuesta: "Sí, los socios trabajadores de las cooperativas de trabajo asociado pueden optar por encuadrarse en el Régimen General o en el RETA." },
  { pregunta: "¿Qué ocurre si una persona realiza simultáneamente dos actividades que obligan a inclusión en distintos regímenes?", respuesta: "Se produce una situación de pluriactividad y el trabajador debe darse de alta y cotizar en cada uno de los regímenes correspondientes." },
  { pregunta: "¿Qué condición se exige a un extranjero para estar incluido en la modalidad contributiva del sistema?", respuesta: "Que resida o se encuentre legalmente en España." },
  { pregunta: "¿Qué condición se exige a un extranjero para estar incluido en la modalidad no contributiva?", respuesta: "Que resida legalmente en territorio español." },
  { pregunta: "¿Qué grupos de personas comprende el campo de aplicación contributivo según el art. 7.1 TRLGSS?", respuesta: "Trabajadores por cuenta ajena o asimilados, autónomos, socios de cooperativas, estudiantes y funcionarios públicos." },
  { pregunta: "¿Qué trabajadores pueden ser incluidos en el sistema por decisión del Gobierno para facilitar su integración social?", respuesta: "Los deportistas de alto nivel." },
  { pregunta: "¿Qué tipo de trabajos pueden ser excluidos del sistema por considerarse marginales?", respuesta: "Trabajos por cuenta ajena cuya jornada o retribución no constituyan medio fundamental de vida." },
  { pregunta: "¿Qué prohíbe el artículo 8 TRLGSS respecto a la inclusión múltiple?", respuesta: "Estar incluido por el mismo trabajo en más de un régimen obligatorio." },
  { pregunta: "¿Qué dos grandes bloques componen la estructura del sistema según los arts. 9 y 10 TRLGSS?", respuesta: "El Régimen General y los Regímenes Especiales." },
  { pregunta: "¿Qué regímenes especiales existen actualmente según el art. 10 TRLGSS?", respuesta: "RETA, REMAR, Funcionarios públicos, Estudiantes y Minería del Carbón." },
  { pregunta: "¿Qué dos regímenes especiales se regulan mediante ley específica?", respuesta: "El REMAR y los Funcionarios públicos." },
  { pregunta: "¿Qué requisito exige la totalización de periodos entre regímenes?", respuesta: "Que los periodos no se superpongan." },
  { pregunta: "¿Qué trabajadores se incluyen expresamente en el Régimen General según el art. 136 TRLGSS?", respuesta: "Trabajadores por cuenta ajena, socios de sociedades de capital sin control, socios de sociedades laborales sin control, personal de notarías, manipulación del plátano y personal civil no funcionario." },
  { pregunta: "¿Qué trabajos quedan excluidos del Régimen General según el art. 137 TRLGSS?", respuesta: "Servicios amistosos, benévolos, trabajos incluidos en regímenes especiales y profesores universitarios eméritos." },
  { pregunta: "¿Qué tres requisitos deben concurrir para que opere la exclusión por parentesco del art. 12 TRLGSS?", respuesta: "Parentesco hasta 2º grado, convivencia en el hogar y estar a cargo del empresario." },
  { pregunta: "¿Qué particularidad tienen los hijos menores de 30 años contratados por autónomos?", respuesta: "Pueden ser contratados como cuenta ajena, pero sin protección por desempleo." },
  { pregunta: "¿Qué plazo tiene el hijo contratado por autónomo para presentar declaración responsable al cumplir 30 años?", respuesta: "30 días." },
  { pregunta: "¿Qué ocurre si un socio posee el 50% del capital social junto con familiares convivientes?", respuesta: "Se presume control efectivo y debe encuadrarse en el RETA." },
  { pregunta: "¿Qué ocurre si un socio posee individualmente un tercio del capital social?", respuesta: "Se presume control efectivo y debe encuadrarse en el RETA." },
  { pregunta: "¿Qué ocurre si un socio posee al menos un cuarto del capital y ejerce funciones de dirección y gerencia?", respuesta: "Se presume control efectivo y debe encuadrarse en el RETA." },
  { pregunta: "¿Qué es el SETA según el art. 324 TRLGSS?", respuesta: "Un sistema especial integrado dentro del RETA para autónomos agrarios." },
  { pregunta: "¿Qué porcentaje mínimo de renta debe proceder de la actividad agraria para entrar en el SETA?", respuesta: "Al menos el 50% de la renta total, y de ese porcentaje, el 25% debe proceder de la propia explotación." },
    { pregunta: "¿Qué porcentaje mínimo de tiempo debe dedicarse personalmente a la actividad agraria para entrar en el SETA?", respuesta: "Al menos el 50% del tiempo total de trabajo." },
  { pregunta: "¿Qué requisito económico adicional exige el SETA además del porcentaje de renta agraria?", respuesta: "Que los rendimientos netos no superen el 75% de la base máxima del RETA." },
  { pregunta: "¿Qué trabajadores quedan incluidos en el Sistema Especial Agrario por cuenta ajena?", respuesta: "Trabajadores agrarios por cuenta ajena con jornadas reales o mensuales." },
  { pregunta: "¿Qué trabajadores quedan incluidos en el Sistema Especial Agrario por cuenta propia?", respuesta: "Titulares de explotaciones agrarias que cumplan los requisitos del SETA." },
  { pregunta: "¿Qué trabajadores quedan incluidos en el Sistema Especial del Mar por cuenta ajena?", respuesta: "Trabajadores embarcados en buques, personal de pesca y actividades marítimas." },
  { pregunta: "¿Qué trabajadores quedan incluidos en el Sistema Especial del Mar por cuenta propia?", respuesta: "Armadores, mariscadores y pescadores autónomos." },
  { pregunta: "¿Qué organismo gestiona el Régimen Especial del Mar?", respuesta: "El Instituto Social de la Marina (ISM)." },
  { pregunta: "¿Qué trabajadores quedan incluidos en el Régimen Especial de la Minería del Carbón?", respuesta: "Trabajadores que realizan labores mineras en explotaciones de carbón." },
  { pregunta: "¿Qué particularidad tiene la cotización en la Minería del Carbón?", respuesta: "Se aplican coeficientes reductores para anticipar la edad de jubilación." },
  { pregunta: "¿Qué trabajadores quedan incluidos en el Régimen Especial de Funcionarios Civiles del Estado?", respuesta: "Funcionarios integrados en MUFACE." },
  { pregunta: "¿Qué trabajadores quedan incluidos en el Régimen Especial de Funcionarios de la Administración de Justicia?", respuesta: "Funcionarios integrados en MUGEJU." },
  { pregunta: "¿Qué trabajadores quedan incluidos en el Régimen Especial de Funcionarios de las Fuerzas Armadas?", respuesta: "Funcionarios integrados en ISFAS." },
  { pregunta: "¿Qué trabajadores quedan incluidos en el Régimen Especial de Estudiantes?", respuesta: "Alumnos que realizan prácticas no laborales incluidas en planes de estudio." },
  { pregunta: "¿Qué ocurre si un trabajador realiza actividades en dos regímenes distintos?", respuesta: "Está en pluriactividad y cotiza en ambos regímenes." },
  { pregunta: "¿Qué ocurre si un trabajador realiza actividades en dos empresas dentro del mismo régimen?", respuesta: "Está en pluriempleo y cotiza en un único régimen con varias bases." },
  { pregunta: "¿Qué ocurre si un trabajador supera la base máxima por pluriactividad?", respuesta: "Puede solicitar devolución de cuotas por exceso." },
  { pregunta: "¿Qué ocurre si un trabajador supera la base máxima por pluriempleo?", respuesta: "No procede devolución; se suman bases hasta el tope máximo." },
  { pregunta: "¿Qué ocurre si un trabajador está incluido indebidamente en un régimen especial?", respuesta: "La TGSS corrige el encuadramiento y regulariza cuotas." },
  { pregunta: "¿Qué ocurre si un trabajador está excluido indebidamente del Régimen General?", respuesta: "La TGSS puede practicar alta de oficio y reclamar cuotas." },
  { pregunta: "¿Qué ocurre si un trabajador realiza servicios amistosos o benévolos?", respuesta: "Queda excluido del campo de aplicación del sistema." },
  { pregunta: "¿Qué ocurre si un trabajador realiza un trabajo marginal sin remuneración suficiente?", respuesta: "Puede quedar excluido del sistema por no constituir medio de vida." },
  { pregunta: "¿Qué ocurre si un profesor universitario emérito presta servicios?", respuesta: "Está excluido del Régimen General." },
  { pregunta: "¿Qué ocurre si un trabajador presta servicios en una cooperativa de trabajo asociado?", respuesta: "Su encuadramiento depende de los estatutos: RG o RETA." },
  { pregunta: "¿Qué ocurre si un socio de cooperativa cambia de régimen estatutario?", respuesta: "El cambio afecta a todos los socios por igual." },
  { pregunta: "¿Qué ocurre si un deportista de alto nivel realiza actividad profesional?", respuesta: "Puede ser incluido en el sistema por decisión del Gobierno." },
  { pregunta: "¿Qué ocurre si un extranjero trabaja sin permiso de residencia?", respuesta: "Está incluido en el sistema a efectos de Seguridad Social." },
  { pregunta: "¿Qué ocurre si un extranjero reside ilegalmente en España?", respuesta: "No puede acceder a la modalidad no contributiva." },
  { pregunta: "¿Qué ocurre si un extranjero trabaja legalmente en España?", respuesta: "Está incluido en la modalidad contributiva." },
  { pregunta: "¿Qué ocurre si un extranjero reside legalmente pero no trabaja?", respuesta: "Puede acceder a la modalidad no contributiva." },
  { pregunta: "¿Qué ocurre si un trabajador realiza actividad en España para empresa extranjera?", respuesta: "Debe cotizar en España salvo desplazamiento regulado." },
    { pregunta: "¿Qué condición exige el art. 7.1 TRLGSS para incluir a españoles en la modalidad contributiva?", respuesta: "Que residan en España." },
  { pregunta: "¿Qué condición exige el art. 7.1 TRLGSS para incluir a extranjeros en la modalidad contributiva?", respuesta: "Que residan o se encuentren legalmente en España." },
  { pregunta: "¿Qué condición exige el art. 7.2 TRLGSS para incluir a extranjeros en la modalidad no contributiva?", respuesta: "Que residan legalmente en territorio español." },
  { pregunta: "¿Qué facultad tiene el Gobierno respecto a españoles no residentes según el art. 7.2?", respuesta: "Puede establecer medidas de protección social según el país de residencia." },
  { pregunta: "¿Qué trabajadores pueden ser incluidos por decisión del Gobierno según el art. 7.4?", respuesta: "Los deportistas de alto nivel." },
  { pregunta: "¿Qué órgano debe ser oído para excluir trabajos marginales según el art. 7.5?", respuesta: "Las organizaciones sindicales más representativas o el colegio profesional competente." },
  { pregunta: "¿Qué prohíbe expresamente el art. 8 TRLGSS?", respuesta: "La inclusión múltiple por el mismo trabajo en más de un régimen obligatorio." },
  { pregunta: "¿Qué dos grandes bloques componen el sistema según los arts. 9 y 10 TRLGSS?", respuesta: "El Régimen General y los Regímenes Especiales." },
  { pregunta: "¿Qué criterio justifica la existencia de regímenes especiales según el art. 10?", respuesta: "La naturaleza, condiciones de tiempo y lugar o índole de los procesos productivos." },
  { pregunta: "¿Qué regímenes especiales existen actualmente según el art. 10 TRLGSS?", respuesta: "RETA, REMAR, Funcionarios públicos, Estudiantes y Minería del Carbón." },
  { pregunta: "¿Qué dos regímenes especiales se regulan mediante ley específica?", respuesta: "El REMAR y los Funcionarios públicos." },
  { pregunta: "¿Qué requisito exige la totalización de periodos entre regímenes?", respuesta: "Que los periodos no se superpongan." },
  { pregunta: "¿Qué ocurre si los periodos de cotización entre regímenes se superponen?", respuesta: "Solo se computa una vez el periodo coincidente." },
  { pregunta: "¿Qué trabajadores incluye el art. 136.1 TRLGSS en el Régimen General?", respuesta: "Trabajadores por cuenta ajena y asimilados, salvo que deban estar en un régimen especial." },
  { pregunta: "¿Qué trabajadores incluye expresamente el art. 136.2 TRLGSS?", respuesta: "Sistemas especiales, socios sin control, consejeros sin control, sociedades laborales sin control, notarías, plátano y personal civil no funcionario." },
  { pregunta: "¿Qué trabajos excluye el art. 137 TRLGSS del Régimen General?", respuesta: "Servicios amistosos, benévolos, trabajos incluidos en regímenes especiales y profesores universitarios eméritos." },
  { pregunta: "¿Qué tres requisitos exige la exclusión por parentesco del art. 12 TRLGSS?", respuesta: "Parentesco hasta 2º grado, convivencia y estar a cargo del empresario." },
  { pregunta: "¿Qué particularidad tienen los hijos menores de 30 años contratados por autónomos?", respuesta: "Pueden ser contratados como cuenta ajena, pero sin desempleo." },
  { pregunta: "¿Qué debe presentar el hijo contratado por autónomo al cumplir 30 años?", respuesta: "Una declaración responsable ante la TGSS en 30 días." },
  { pregunta: "¿Qué ocurre si un hijo mayor de 30 años con discapacidad ≥ 33% es contratado por un autónomo?", respuesta: "Puede ser contratado como cuenta ajena." },
  { pregunta: "¿Qué ocurre si un hijo mayor de 30 años con discapacidad física del 33% al 65% quiere ser contratado?", respuesta: "Solo si causa alta por primera vez en el sistema." },
  { pregunta: "¿Qué ocurre si un hijo mayor de 30 años con discapacidad física ≥ 65% quiere ser contratado?", respuesta: "Puede ser contratado en cualquier caso." },
  { pregunta: "¿Qué ocurre si un socio posee el 50% del capital junto con familiares convivientes?", respuesta: "Se presume control efectivo y debe encuadrarse en el RETA." },
  { pregunta: "¿Qué ocurre si un socio posee individualmente un tercio del capital social?", respuesta: "Se presume control efectivo y debe encuadrarse en el RETA." },
  { pregunta: "¿Qué ocurre si un socio posee al menos un cuarto del capital y ejerce funciones de dirección?", respuesta: "Se presume control efectivo y debe encuadrarse en el RETA." },
  { pregunta: "¿Qué ocurre si un socio laboral y su familia poseen el 50% del capital?", respuesta: "Se presume control efectivo salvo prueba de que requiere concurso de terceros." },
  { pregunta: "¿Qué trabajadores incluye el RETA según el art. 305 TRLGSS?", respuesta: "Trabajadores por cuenta propia que realizan actividad habitual, personal y directa." },
  { pregunta: "¿Qué trabajadores quedan excluidos del RETA según el vídeo del Tema 2?", respuesta: "Socios capitalistas cuyo objeto es administrar patrimonio y trabajadores del mar." },
  { pregunta: "¿Qué trabajadores incluye el REMAR por cuenta ajena?", respuesta: "Tripulantes, técnicos, mariscadores, buceadores, rederos, estibadores y prácticos." },
  { pregunta: "¿Qué trabajadores incluye el REMAR por cuenta propia?", respuesta: "Mariscadores, percebeiros, armadores y acuicultura." },
  { pregunta: "¿Qué trabajadores incluye la Minería del Carbón?", respuesta: "Trabajadores en extracción, investigación, hornos de cok y transporte fluvial." },
  { pregunta: "¿Qué coeficiente reductor se aplica a picadores y barrenistas?", respuesta: "0,50." },
  { pregunta: "¿Qué coeficiente reductor se aplica a trabajadores del exterior en minería?", respuesta: "0,05." },
  { pregunta: "¿Qué es un sistema especial según el art. 11 TRLGSS?", respuesta: "Una particularidad dentro de un régimen en materias de encuadramiento, afiliación, cotización o recaudación." },
  { pregunta: "¿Qué materia NO puede regular un sistema especial?", respuesta: "La acción protectora." },
  { pregunta: "¿Qué sistemas especiales están integrados en el Régimen General?", respuesta: "Agrario por cuenta ajena, Empleados de hogar, Frutas y Hortalizas, Hostelería." },
  { pregunta: "¿Qué sistema especial está integrado en el RETA?", respuesta: "El SETA." },
  { pregunta: "¿Qué porcentaje de renta total debe proceder de actividad agraria para entrar en el SETA?", respuesta: "Al menos el 50%." },
  { pregunta: "¿Qué porcentaje de renta total debe proceder de la propia explotación para entrar en el SETA?", respuesta: "Al menos el 25%." },
  { pregunta: "¿Qué límite económico exige el SETA respecto a la base máxima del RG?", respuesta: "No superar el 75% de la base máxima." },
  { pregunta: "¿Cuántos trabajadores fijos puede tener un autónomo del SETA?", respuesta: "No más de 2." },
  { pregunta: "¿Cuántas jornadas reales pueden realizar los temporeros contratados por un autónomo del SETA?", respuesta: "No más de 546 al año." },
  { pregunta: "¿Hasta qué grado se admite el familiar colaborador en el SETA?", respuesta: "Hasta el 3º grado." },
  { pregunta: "¿Qué trabajadores incluye el Sistema Especial Agrario por cuenta ajena?", respuesta: "Trabajadores agrarios con jornadas reales o mensuales." },
  { pregunta: "¿Qué debe comunicar el empresario agrario en los primeros 6 días del mes?", respuesta: "Las jornadas reales realizadas." },
  { pregunta: "¿Qué tipo de cotización se aplica en inactividad en el SE Agrario?", respuesta: "11,50% sobre la base mínima del grupo 7." },
  { pregunta: "¿Qué requisito exige la inactividad en el SE Agrario?", respuesta: "Jornadas reales inferiores al 76,67% de los días en alta." },
  { pregunta: "¿Qué requisito adicional exige la inactividad en el SE Agrario?", respuesta: "Haber realizado 30 jornadas reales en los últimos 365 días." },
  { pregunta: "¿Qué formulario debe usarse para solicitar la inclusión en inactividad del SE Agrario?", respuesta: "Modelo TA.0161." },
    { pregunta: "¿Qué trabajadores incluye el REMAR por cuenta ajena según la Ley 47/2015?", respuesta: "Tripulantes, técnicos, personal embarcado, mariscadores, buceadores, rederos, estibadores y prácticos de puerto." },
  { pregunta: "¿Qué trabajadores incluye el REMAR por cuenta propia?", respuesta: "Mariscadores, percebeiros, armadores y trabajadores de acuicultura." },
  { pregunta: "¿Qué grupo del REMAR incluye embarcaciones de más de 150 toneladas?", respuesta: "El primer grupo." },
  { pregunta: "¿Qué grupo del REMAR incluye pesqueros entre 50,01 y 150 toneladas?", respuesta: "El grupo A del segundo grupo." },
  { pregunta: "¿Qué grupo del REMAR incluye pesqueros entre 10,01 y 50 toneladas?", respuesta: "El grupo B del segundo grupo." },
  { pregunta: "¿Qué coeficiente corrector se aplica en el grupo A del REMAR?", respuesta: "Dos tercios (2/3)." },
  { pregunta: "¿Qué coeficiente corrector se aplica en el grupo B del REMAR?", respuesta: "La mitad (1/2)." },
  { pregunta: "¿Qué coeficiente corrector se aplica en el tercer grupo del REMAR?", respuesta: "Un tercio (1/3)." },
  { pregunta: "¿Qué trabajadores incluye el tercer grupo del REMAR?", respuesta: "Cuenta ajena retribuidos a la parte y autónomos en embarcaciones ≤ 10 toneladas." },
  { pregunta: "¿Qué trabajadores incluye la Minería del Carbón según el Tema 2?", respuesta: "Trabajadores en extracción, investigación, hornos de cok y transporte fluvial." },
  { pregunta: "¿Qué coeficiente reductor se aplica a picadores y barrenistas?", respuesta: "0,50." },
  { pregunta: "¿Qué coeficiente reductor se aplica a trabajadores del exterior en minería?", respuesta: "0,05." },
  { pregunta: "¿Qué plazo tiene el empresario minero para comunicar el alta?", respuesta: "3 días naturales." },
  { pregunta: "¿Qué materias pueden regular los sistemas especiales según el art. 11 TRLGSS?", respuesta: "Encuadramiento, afiliación, forma de cotización y recaudación." },
  { pregunta: "¿Qué materia NO pueden regular los sistemas especiales?", respuesta: "La acción protectora." },
  { pregunta: "¿Qué sistemas especiales están integrados en el Régimen General?", respuesta: "Agrario por cuenta ajena, Empleados de hogar, Frutas y Hortalizas, Hostelería." },
  { pregunta: "¿Qué sistema especial está integrado en el RETA?", respuesta: "El SETA." },
  { pregunta: "¿Qué base legal regula el Sistema Especial Agrario por cuenta ajena?", respuesta: "La Ley 28/2011 y los arts. 252-256 TRLGSS." },
  { pregunta: "¿Quién es responsable de la cotización en actividad en el SE Agrario por cuenta ajena?", respuesta: "El empresario." },
  { pregunta: "¿Quién es responsable de la cotización en inactividad en el SE Agrario por cuenta ajena?", respuesta: "El trabajador." },
  { pregunta: "¿En qué plazo deben comunicarse las jornadas reales en el SE Agrario?", respuesta: "Dentro de los 6 primeros días del mes." },
  { pregunta: "¿Qué tipo de cotización se aplica en inactividad en el SE Agrario?", respuesta: "11,50% sobre la base mínima del grupo 7." },
  { pregunta: "¿Cuándo se considera que existe inactividad en el SE Agrario?", respuesta: "Cuando las jornadas reales del mes son inferiores al 76,67% de los días en alta." },
  { pregunta: "¿Qué excepción existe a la inactividad en el SE Agrario?", respuesta: "Si realiza al menos 5 jornadas semanales para el mismo empleador." },
  { pregunta: "¿Qué requisito técnico exige la inactividad en el SE Agrario?", respuesta: "Haber realizado 30 jornadas reales en los últimos 365 días." },
  { pregunta: "¿En qué plazo debe solicitarse la inclusión en inactividad en el SE Agrario?", respuesta: "En un plazo de 3 meses." },
  { pregunta: "¿Qué formulario debe usarse para solicitar la inclusión en inactividad en el SE Agrario?", respuesta: "El modelo TA.0161." },
  { pregunta: "¿Qué porcentaje de renta total debe proceder de actividad agraria para entrar en el SETA?", respuesta: "Al menos el 50%." },
  { pregunta: "¿Qué porcentaje de renta total debe proceder de la propia explotación para entrar en el SETA?", respuesta: "Al menos el 25%." },
  { pregunta: "¿Qué límite económico exige el SETA respecto a la base máxima del RG?", respuesta: "No superar el 75% de la base máxima." },
  { pregunta: "¿Cuántos trabajadores fijos puede tener un autónomo del SETA?", respuesta: "No más de 2." },
  { pregunta: "¿Cuántas jornadas reales pueden realizar los temporeros contratados por un autónomo del SETA?", respuesta: "No más de 546 al año." },
  { pregunta: "¿Hasta qué grado se admite el familiar colaborador en el SETA?", respuesta: "Hasta el 3º grado." },
  { pregunta: "¿Qué diferencia existe entre el familiar colaborador del RETA y el del SETA?", respuesta: "En el RETA es hasta 2º grado; en el SETA hasta 3º grado." },
  { pregunta: "¿Qué ocurre si un autónomo agrario supera el límite del 75% de la base máxima?", respuesta: "No puede permanecer en el SETA." },
  { pregunta: "¿Qué ocurre si un autónomo agrario no realiza actividad personal y directa?", respuesta: "No puede estar en el SETA." },
  { pregunta: "¿Qué ocurre si un autónomo agrario supera el límite de trabajadores fijos?", respuesta: "Debe salir del SETA." },
  { pregunta: "¿Qué ocurre si un autónomo agrario supera las 546 jornadas reales contratadas?", respuesta: "Debe salir del SETA." },
  { pregunta: "¿Qué ocurre si un trabajador del mar realiza actividad terrestre no marítima?", respuesta: "Debe encuadrarse en el régimen correspondiente a esa actividad." },
  { pregunta: "¿Qué ocurre si un trabajador del mar realiza actividad marítima y terrestre simultáneamente?", respuesta: "Debe encuadrarse en el REMAR si la actividad marítima es principal." },
  { pregunta: "¿Qué ocurre si un trabajador del mar cambia de grupo de cotización?", respuesta: "Debe regularizarse su encuadramiento y cotización." },
  { pregunta: "¿Qué ocurre si un trabajador del mar pasa a actividad en embarcación de mayor tonelaje?", respuesta: "Cambia de grupo y coeficiente corrector." },
  { pregunta: "¿Qué ocurre si un trabajador del mar pasa a embarcación ≤ 10 toneladas?", respuesta: "Pasa al tercer grupo con coeficiente 1/3." },
  { pregunta: "¿Qué ocurre si un trabajador de minería cambia de puesto a uno con menor coeficiente reductor?", respuesta: "Se aplica el coeficiente correspondiente al nuevo puesto." },
  { pregunta: "¿Qué ocurre si un trabajador de minería cambia a un puesto con mayor coeficiente reductor?", respuesta: "Se aplica el coeficiente correspondiente al nuevo puesto." },
  { pregunta: "¿Qué ocurre si un trabajador de minería deja de realizar labores mineras?", respuesta: "Deja de estar incluido en el Régimen Especial de la Minería del Carbón." },
  { pregunta: "¿Qué ocurre si un trabajador realiza actividad marginal según el art. 7.5?", respuesta: "Puede ser excluido del sistema por no constituir medio fundamental de vida." },
  { pregunta: "¿Qué ocurre si un trabajador realiza servicios amistosos o benévolos?", respuesta: "Queda excluido del sistema." },
  { pregunta: "¿Qué ocurre si un trabajador está incluido indebidamente en un régimen especial?", respuesta: "La TGSS corrige el encuadramiento y regulariza cuotas." },
  { pregunta: "¿Qué ocurre si un trabajador está excluido indebidamente del Régimen General?", respuesta: "La TGSS puede practicar alta de oficio y reclamar cuotas." },
    { pregunta: "¿Qué ocurre si un trabajador realiza actividad en España para una empresa extranjera sin desplazamiento regulado?", respuesta: "Debe cotizar en España en el régimen correspondiente." },
  { pregunta: "¿Qué ocurre si un trabajador es desplazado temporalmente dentro de la UE?", respuesta: "Se aplica el Reglamento 883/2004 y el formulario A1." },
  { pregunta: "¿Qué ocurre si un trabajador es desplazado a un país con convenio bilateral?", respuesta: "Se aplica la legislación del país de origen durante el periodo autorizado." },
  { pregunta: "¿Qué ocurre si un trabajador es desplazado a un país sin convenio bilateral?", respuesta: "Debe suscribir un convenio especial para mantener cotizaciones en España." },
  { pregunta: "¿Qué ocurre si un trabajador presta servicios en España y en otro país simultáneamente?", respuesta: "Debe analizarse la legislación aplicable según normativa internacional." },
  { pregunta: "¿Qué ocurre si un trabajador realiza actividad marginal según el art. 7.5 TRLGSS?", respuesta: "Puede ser excluido del sistema por no constituir medio fundamental de vida." },
  { pregunta: "¿Qué ocurre si un trabajador realiza servicios amistosos o benévolos?", respuesta: "Queda excluido del campo de aplicación del sistema." },
  { pregunta: "¿Qué ocurre si un trabajador realiza actividad incluida en un régimen especial?", respuesta: "Debe encuadrarse en ese régimen especial y no en el Régimen General." },
  { pregunta: "¿Qué ocurre si un trabajador está incluido indebidamente en un régimen especial?", respuesta: "La TGSS corrige el encuadramiento y regulariza cuotas." },
  { pregunta: "¿Qué ocurre si un trabajador está excluido indebidamente del Régimen General?", respuesta: "La TGSS puede practicar alta de oficio y reclamar cuotas." },
  { pregunta: "¿Qué ocurre si un trabajador tiene dos actividades en el mismo régimen?", respuesta: "Está en pluriempleo y se suman bases hasta el tope máximo." },
  { pregunta: "¿Qué ocurre si un trabajador tiene dos actividades en regímenes distintos?", respuesta: "Está en pluriactividad y cotiza en ambos regímenes." },
  { pregunta: "¿Qué ocurre si un trabajador supera la base máxima por pluriactividad?", respuesta: "Puede solicitar devolución de cuotas por exceso." },
  { pregunta: "¿Qué ocurre si un trabajador supera la base máxima por pluriempleo?", respuesta: "No procede devolución; se suman bases hasta el tope máximo." },
  { pregunta: "¿Qué ocurre si un trabajador autónomo realiza actividad marítima?", respuesta: "Debe encuadrarse en el REMAR, que tiene preferencia sobre el RETA." },
  { pregunta: "¿Qué ocurre si un socio capitalista solo administra patrimonio?", respuesta: "No debe encuadrarse en el RETA." },
  { pregunta: "¿Qué ocurre si un socio laboral y su familia poseen el 50% del capital?", respuesta: "Se presume control efectivo salvo prueba en contrario." },
  { pregunta: "¿Qué ocurre si un socio laboral posee menos del 50% y no ejerce control?", respuesta: "Puede encuadrarse en el Régimen General." },
  { pregunta: "¿Qué ocurre si un consejero sin control efectivo presta servicios retribuidos?", respuesta: "Se encuadra en el Régimen General asimilado, sin desempleo ni FOGASA." },
  { pregunta: "¿Qué ocurre si un consejero con control efectivo presta servicios?", respuesta: "Debe encuadrarse en el RETA." },
  { pregunta: "¿Qué ocurre si un trabajador del mar pasa a embarcación de mayor tonelaje?", respuesta: "Cambia de grupo y coeficiente corrector." },
  { pregunta: "¿Qué ocurre si un trabajador del mar pasa a embarcación ≤ 10 toneladas?", respuesta: "Pasa al tercer grupo con coeficiente 1/3." },
  { pregunta: "¿Qué ocurre si un trabajador del mar realiza actividad terrestre no marítima?", respuesta: "Debe encuadrarse en el régimen correspondiente a esa actividad." },
  { pregunta: "¿Qué ocurre si un trabajador de minería cambia de puesto a uno con menor coeficiente reductor?", respuesta: "Se aplica el coeficiente correspondiente al nuevo puesto." },
  { pregunta: "¿Qué ocurre si un trabajador de minería cambia a un puesto con mayor coeficiente reductor?", respuesta: "Se aplica el coeficiente correspondiente al nuevo puesto." },
  { pregunta: "¿Qué ocurre si un trabajador de minería deja de realizar labores mineras?", respuesta: "Deja de estar incluido en el Régimen Especial de la Minería del Carbón." },
  { pregunta: "¿Qué ocurre si un trabajador del SE Agrario no comunica jornadas reales?", respuesta: "Puede perder la condición de trabajador agrario y la inactividad." },
  { pregunta: "¿Qué ocurre si un trabajador del SE Agrario no cumple el requisito de 30 jornadas en 365 días?", respuesta: "No puede acceder a la inactividad." },
  { pregunta: "¿Qué ocurre si un trabajador del SE Agrario no solicita la inactividad en 3 meses?", respuesta: "Pierde el derecho a ser incluido en el censo de inactividad." },
  { pregunta: "¿Qué ocurre si un autónomo agrario supera el límite del 75% de la base máxima?", respuesta: "Debe salir del SETA." },
  { pregunta: "¿Qué ocurre si un autónomo agrario supera el límite de trabajadores fijos?", respuesta: "Debe salir del SETA." },
  { pregunta: "¿Qué ocurre si un autónomo agrario supera las 546 jornadas reales contratadas?", respuesta: "Debe salir del SETA." },
  { pregunta: "¿Qué ocurre si un autónomo agrario no realiza actividad personal y directa?", respuesta: "No puede permanecer en el SETA." },
  { pregunta: "¿Qué ocurre si un familiar colaborador del SETA es de 3º grado?", respuesta: "Puede ser colaborador legítimo." },
  { pregunta: "¿Qué ocurre si un familiar colaborador del RETA es de 3º grado?", respuesta: "No puede ser colaborador; el límite es 2º grado." },
  { pregunta: "¿Qué ocurre si un trabajador del mar cambia de grupo por cambio de embarcación?", respuesta: "Debe regularizarse su cotización." },
  { pregunta: "¿Qué ocurre si un trabajador del mar realiza actividad mixta marítima-terrestre?", respuesta: "Debe encuadrarse en el REMAR si la actividad marítima es principal." },
  { pregunta: "¿Qué ocurre si un trabajador del mar realiza actividad exclusivamente terrestre?", respuesta: "Debe encuadrarse en el régimen correspondiente a esa actividad." },
  { pregunta: "¿Qué ocurre si un trabajador realiza actividad incluida en el Seguro Escolar?", respuesta: "Se encuadra en el Régimen Especial de Estudiantes." },
  { pregunta: "¿Qué ocurre si un estudiante realiza prácticas no laborales incluidas en plan de estudios?", respuesta: "Está incluido en el Régimen Especial de Estudiantes." },
  { pregunta: "¿Qué ocurre si un estudiante realiza prácticas remuneradas?", respuesta: "Debe analizarse si existe relación laboral." },
  { pregunta: "¿Qué ocurre si un funcionario está integrado en MUFACE?", respuesta: "Pertenece al Régimen Especial de Funcionarios Civiles del Estado." },
  { pregunta: "¿Qué ocurre si un funcionario está integrado en MUGEJU?", respuesta: "Pertenece al Régimen Especial de Funcionarios de Justicia." },
  { pregunta: "¿Qué ocurre si un funcionario está integrado en ISFAS?", respuesta: "Pertenece al Régimen Especial de Fuerzas Armadas." },
  { pregunta: "¿Qué ocurre si un funcionario está en prácticas?", respuesta: "Se encuadra en el Régimen General salvo que pertenezca a Clases Pasivas." },
  { pregunta: "¿Qué ocurre si un trabajador realiza actividad incluida en un sistema especial?", respuesta: "Debe encuadrarse en ese sistema especial dentro del régimen correspondiente." },
  { pregunta: "¿Qué ocurre si un sistema especial regula la acción protectora?", respuesta: "No puede; excede sus competencias según el art. 11 TRLGSS." },
  { pregunta: "¿Qué ocurre si un régimen especial regula materias ajenas a su ámbito?", respuesta: "Debe modificarse mediante ley específica o TRLGSS." },
  { pregunta: "¿Qué ocurre si un trabajador realiza actividad en España y en otro país sin coordinación internacional?", respuesta: "Debe analizarse la legislación aplicable según normativa interna." }
];