const preguntas = [

{ pregunta: "¿Qué protege la acción protectora por muerte y supervivencia?", respuesta: "La pérdida de ingresos por el fallecimiento del causante." },
{ pregunta: "¿Qué contingencias cubren estas prestaciones?", respuesta: "Contingencias comunes y profesionales." },
{ pregunta: "¿Qué prestación sustituye a la antigua orfandad absoluta?", respuesta: "La pensión en favor de familiares." },
{ pregunta: "¿Qué prestación se reconoce al cónyuge superviviente?", respuesta: "La pensión de viudedad." },
{ pregunta: "¿Qué prestación se reconoce a los hijos del causante?", respuesta: "La pensión de orfandad." },
{ pregunta: "¿Qué prestación cubre a otros familiares convivientes?", respuesta: "La pensión en favor de familiares." },
{ pregunta: "¿Qué prestación cubre los gastos del sepelio?", respuesta: "El auxilio por defunción." },
{ pregunta: "¿Cuál es la cuantía del auxilio por defunción?", respuesta: "30,05 euros." },
{ pregunta: "¿Quién tiene preferencia para cobrar el auxilio por defunción?", respuesta: "El cónyuge o pareja de hecho." },
{ pregunta: "¿Qué porcentaje de la base reguladora corresponde a la viudedad general?", respuesta: "52%." },

{ pregunta: "¿Qué porcentaje de viudedad corresponde a mayores de 65 sin ingresos?", respuesta: "60%." },
{ pregunta: "¿Qué porcentaje de viudedad corresponde con cargas familiares y bajos ingresos?", respuesta: "70%." },
{ pregunta: "¿Qué porcentaje corresponde a cada huérfano?", respuesta: "20% de la base reguladora." },
{ pregunta: "¿Cuál es el límite conjunto de viudedad + orfandad?", respuesta: "100% de la base reguladora." },
{ pregunta: "¿Qué edad máxima general tiene la orfandad?", respuesta: "21 años." },
{ pregunta: "¿Hasta qué edad puede llegar la orfandad si no trabaja?", respuesta: "25 años." },
{ pregunta: "¿Qué ocurre si el huérfano tiene discapacidad del 33% antes de los 21/25?", respuesta: "La pensión es vitalicia." },
{ pregunta: "¿Qué requisito de cotización se exige para contingencias comunes?", respuesta: "500 días en los últimos 5 años." },
{ pregunta: "¿Se exige cotización en contingencias profesionales?", respuesta: "No." },
{ pregunta: "¿Qué es la base reguladora?", respuesta: "El promedio de bases del causante según la contingencia." },

{ pregunta: "¿Puede cobrar viudedad una pareja de hecho?", respuesta: "Sí, si cumple requisitos de convivencia y económicos." },
{ pregunta: "¿Cuántos años de convivencia se exigen a la pareja de hecho?", respuesta: "5 años." },
{ pregunta: "¿Qué documento acredita la pareja de hecho?", respuesta: "Inscripción en registro o escritura pública." },
{ pregunta: "¿Puede cobrar viudedad un matrimonio separado legalmente?", respuesta: "Sí, si percibía pensión compensatoria." },
{ pregunta: "¿Qué ocurre si la pensión compensatoria se extingue por fallecimiento?", respuesta: "Da derecho a viudedad." },
{ pregunta: "¿Puede haber varios beneficiarios de viudedad?", respuesta: "Sí, se reparte proporcionalmente." },
{ pregunta: "¿Qué requisito económico se exige para el 70% de viudedad?", respuesta: "Ingresos bajos y cargas familiares." },
{ pregunta: "¿Qué requisito se exige para el 60% de viudedad?", respuesta: "Ser mayor de 65 y no tener ingresos propios." },
{ pregunta: "¿Qué ocurre si el causante estaba en alta?", respuesta: "Se calcula la BR según bases reales." },
{ pregunta: "¿Qué ocurre si el causante no estaba en alta?", respuesta: "Se aplica la BR de no alta." },

{ pregunta: "¿Qué es la situación asimilada al alta?", respuesta: "Situaciones que permiten acceder a prestaciones sin estar en alta." },
{ pregunta: "¿Qué ejemplo hay de situación asimilada al alta?", respuesta: "Desempleo con prestación." },
{ pregunta: "¿Qué ocurre si el causante fallece por accidente laboral?", respuesta: "No se exige cotización previa." },
{ pregunta: "¿Qué ocurre si fallece por enfermedad profesional?", respuesta: "No se exige cotización previa." },
{ pregunta: "¿Qué es el hecho causante?", respuesta: "El momento en que se produce el fallecimiento o declaración." },
{ pregunta: "¿Qué fecha se toma como hecho causante en desaparición?", respuesta: "La resolución judicial." },
{ pregunta: "¿Qué fecha se toma como hecho causante en accidente?", respuesta: "El día del accidente." },
{ pregunta: "¿Qué fecha se toma como hecho causante en enfermedad?", respuesta: "El día del fallecimiento." },
{ pregunta: "¿Qué ocurre si el causante estaba jubilado?", respuesta: "La BR se calcula según su pensión." },
{ pregunta: "¿Qué ocurre si el causante era pensionista de incapacidad?", respuesta: "La BR se calcula según su pensión." },

{ pregunta: "¿Qué prestación se reconoce si no hay viudo ni huérfanos?", respuesta: "Pensión en favor de familiares." },
{ pregunta: "¿Qué familiares pueden acceder a esta pensión?", respuesta: "Nietos, hermanos, ascendientes." },
{ pregunta: "¿Qué requisito exige la pensión en favor de familiares?", respuesta: "Convivencia y dependencia económica." },
{ pregunta: "¿Qué ocurre si el beneficiario trabaja?", respuesta: "Puede ser compatible según ingresos." },
{ pregunta: "¿Qué ocurre si el beneficiario supera ingresos?", respuesta: "Se suspende la pensión." },
{ pregunta: "¿Qué ocurre si el beneficiario vuelve a cumplir requisitos?", respuesta: "Se reactiva la pensión." },
{ pregunta: "¿Qué es la compatibilidad de prestaciones?", respuesta: "Posibilidad de cobrar varias si la ley lo permite." },
{ pregunta: "¿Es compatible la viudedad con trabajo?", respuesta: "Sí." },
{ pregunta: "¿Es compatible la orfandad con trabajo?", respuesta: "Sí, si ingresos < SMI anual." },
{ pregunta: "¿Qué ocurre si el huérfano supera ingresos?", respuesta: "Se suspende la pensión." },
{ pregunta: "¿Qué prestación se reconoce cuando el fallecido estaba en alta?", respuesta: "Las prestaciones de muerte y supervivencia según corresponda." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido estaba en situación asimilada al alta?", respuesta: "Las mismas que si estuviera en alta." },
{ pregunta: "¿Qué prestación cubre los gastos del sepelio?", respuesta: "El auxilio por defunción." },
{ pregunta: "¿Qué prestación recibe el cónyuge superviviente?", respuesta: "La pensión de viudedad." },
{ pregunta: "¿Qué prestación reciben los hijos del causante?", respuesta: "La pensión de orfandad." },
{ pregunta: "¿Qué prestación cubre a familiares dependientes que convivían con el causante?", respuesta: "La pensión en favor de familiares." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido era pensionista de incapacidad?", respuesta: "Las prestaciones de muerte y supervivencia según su pensión." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido era pensionista de jubilación?", respuesta: "Las prestaciones de muerte y supervivencia según su pensión." },
{ pregunta: "¿Qué prestación se reconoce si el fallecimiento es por accidente laboral?", respuesta: "Prestaciones sin requisito de cotización previa." },
{ pregunta: "¿Qué prestación se reconoce si el fallecimiento es por enfermedad profesional?", respuesta: "Prestaciones sin requisito de cotización previa." },

{ pregunta: "¿Qué prestación se reconoce si el fallecido no tenía cotización suficiente?", respuesta: "Auxilio por defunción si hay gastos." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido estaba en desempleo con prestación?", respuesta: "Prestaciones de muerte y supervivencia (asimilada al alta)." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido estaba en ERTE?", respuesta: "Prestaciones de muerte y supervivencia (asimilada al alta)." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido estaba en excedencia por cuidado de hijos?", respuesta: "Prestaciones de muerte y supervivencia (asimilada al alta)." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido estaba en convenio especial?", respuesta: "Prestaciones de muerte y supervivencia." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido estaba en pluriempleo?", respuesta: "Prestaciones con suma de bases." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido estaba en pluriactividad?", respuesta: "Prestaciones en uno o varios regímenes." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido era autónomo?", respuesta: "Prestaciones del RETA." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido era agrario?", respuesta: "Prestaciones del Sistema Especial Agrario." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido era empleada de hogar?", respuesta: "Prestaciones del Sistema Especial de Hogar." },

{ pregunta: "¿Qué prestación se reconoce si el fallecido era trabajador del mar?", respuesta: "Prestaciones gestionadas por el ISM." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido tenía lagunas de cotización?", respuesta: "Prestaciones con integración de lagunas." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido tenía bases muy bajas?", respuesta: "Prestaciones calculadas con su BR real." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido tenía bases muy altas?", respuesta: "Prestaciones con tope máximo de BR." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido tenía deudas con la Seguridad Social?", respuesta: "Las prestaciones no se ven afectadas." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido tenía sanciones?", respuesta: "Las prestaciones no se ven afectadas." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido estaba desaparecido?", respuesta: "Prestaciones tras declaración judicial de fallecimiento." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido murió en el extranjero?", respuesta: "Prestaciones con documentación acreditativa." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido murió en acto de servicio?", respuesta: "Prestaciones con posible recargo empresarial." },
{ pregunta: "¿Qué prestación se reconoce si hubo falta de medidas de seguridad?", respuesta: "Prestaciones con recargo del 30% al 50%." },

{ pregunta: "¿Qué prestación se reconoce si el cónyuge superviviente no cumple requisitos de viudedad?", respuesta: "Pensión temporal de viudedad." },
{ pregunta: "¿Qué prestación se reconoce si la pareja de hecho no acredita convivencia?", respuesta: "No procede viudedad." },
{ pregunta: "¿Qué prestación se reconoce si la pareja de hecho sí acredita convivencia?", respuesta: "Pensión de viudedad." },
{ pregunta: "¿Qué prestación se reconoce si el matrimonio estaba separado legalmente?", respuesta: "Viudedad si había pensión compensatoria." },
{ pregunta: "¿Qué prestación se reconoce si la pensión compensatoria se extinguía por fallecimiento?", respuesta: "Pensión de viudedad." },
{ pregunta: "¿Qué prestación se reconoce si hay varios excónyuges?", respuesta: "Viudedad prorrateada." },
{ pregunta: "¿Qué prestación se reconoce si el huérfano tiene discapacidad del 33%?", respuesta: "Orfandad vitalicia." },
{ pregunta: "¿Qué prestación se reconoce si el huérfano tiene 21 años y no trabaja?", respuesta: "Pensión de orfandad." },
{ pregunta: "¿Qué prestación se reconoce si el huérfano tiene 25 años y no trabaja?", respuesta: "Pensión de orfandad." },
{ pregunta: "¿Qué prestación se reconoce si el huérfano trabaja pero gana menos del SMI?", respuesta: "Pensión de orfandad compatible." },

{ pregunta: "¿Qué prestación se reconoce si el huérfano supera el SMI?", respuesta: "Suspensión de la orfandad." },
{ pregunta: "¿Qué prestación se reconoce si el huérfano vuelve a ganar menos del SMI?", respuesta: "Reactivación de la orfandad." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido tenía hijos de varios matrimonios?", respuesta: "Orfandad para todos los hijos con derecho." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido tenía nietos a cargo?", respuesta: "Pensión en favor de familiares." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido tenía hermanos a cargo?", respuesta: "Pensión en favor de familiares." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido tenía ascendientes a cargo?", respuesta: "Pensión en favor de familiares." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido convivía con sobrinos dependientes?", respuesta: "Pensión en favor de familiares si cumplen requisitos." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido convivía con un familiar discapacitado?", respuesta: "Pensión en favor de familiares." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido convivía con un familiar mayor de 65 años?", respuesta: "Pensión en favor de familiares." },
{ pregunta: "¿Qué prestación se reconoce si el fallecido convivía con un familiar sin ingresos?", respuesta: "Pensión en favor de familiares." }

];
