const preguntas = [
  { pregunta: "¿Qué es la jubilación contributiva?", respuesta: "Una pensión que sustituye las rentas del trabajo al cesar la actividad laboral." },
  { pregunta: "¿Qué edad ordinaria de jubilación hay en 2024?", respuesta: "66 años y 6 meses, o 65 si se acreditan 38 años cotizados." },
  { pregunta: "¿Qué edad ordinaria habrá en 2027?", respuesta: "67 años, o 65 con 38 años y 6 meses cotizados." },
  { pregunta: "¿Cuál es el periodo mínimo de cotización para jubilarse?", respuesta: "15 años, de los cuales 2 deben estar dentro de los 15 anteriores al hecho causante." },
  { pregunta: "¿Qué es el hecho causante en jubilación?", respuesta: "La fecha de cese en el trabajo o la solicitud si no hay cese." },
  { pregunta: "¿Qué es la base reguladora de jubilación?", respuesta: "El promedio de las bases de cotización de los últimos 25 años." },
  { pregunta: "¿Cuántos meses se usan para calcular la BR?", respuesta: "300 meses." },
  { pregunta: "¿Cómo se actualizan las bases antiguas?", respuesta: "Mediante índices de actualización excepto las 24 últimas." },
  { pregunta: "¿Qué ocurre si hay lagunas de cotización en el Régimen General?", respuesta: "Se integran con la base mínima los primeros 48 meses y con el 50% el resto." },
  { pregunta: "¿Qué ocurre con las lagunas en el RETA?", respuesta: "No se integran; se computan como cero." },
  { pregunta: "¿Qué porcentaje se aplica con 15 años cotizados?", respuesta: "50% de la base reguladora." },
  { pregunta: "¿Qué porcentaje se alcanza con 36 años y medio cotizados?", respuesta: "100% de la base reguladora." },
  { pregunta: "¿Qué porcentaje se suma por cada mes adicional?", respuesta: "Entre 0,19% y 0,21% según tramo." },
  { pregunta: "¿Qué es el complemento a mínimos?", respuesta: "Un complemento para alcanzar la cuantía mínima si no se tienen ingresos suficientes." },
  { pregunta: "¿Qué límite de ingresos existe para complemento a mínimos?", respuesta: "No superar los límites anuales fijados por ley." },
  { pregunta: "¿Qué es la jubilación anticipada voluntaria?", respuesta: "La que se solicita hasta 2 años antes de la edad ordinaria." },
  { pregunta: "¿Qué requisito de cotización exige la anticipada voluntaria?", respuesta: "35 años cotizados." },
  { pregunta: "¿Qué coeficientes reductores se aplican en la anticipada voluntaria?", respuesta: "Entre 2,81% y 21% según meses de anticipo y carrera de cotización." },
  { pregunta: "¿Qué es la jubilación anticipada involuntaria?", respuesta: "La que se produce por causas no imputables al trabajador." },
  { pregunta: "¿Cuánto puede anticiparse la involuntaria?", respuesta: "Hasta 4 años antes de la edad ordinaria." },
  { pregunta: "¿Qué requisito de cotización exige la anticipada involuntaria?", respuesta: "33 años cotizados." },
  { pregunta: "¿Qué coeficientes reductores se aplican en la involuntaria?", respuesta: "Menores que en la voluntaria, entre 0,5% y 30% según meses." },
  { pregunta: "¿Qué debe acreditarse en la anticipada involuntaria?", respuesta: "Despido objetivo, ERE, fuerza mayor o extinción por violencia de género." },
  { pregunta: "¿Qué es la jubilación por discapacidad del 45%?", respuesta: "Permite anticipar la edad si la discapacidad está en el listado oficial." },
  { pregunta: "¿Qué es la jubilación por discapacidad del 65%?", respuesta: "Permite reducir la edad aplicando coeficientes reductores." },
  { pregunta: "¿Qué es la jubilación demorada?", respuesta: "Retrasar la jubilación más allá de la edad ordinaria." },
  { pregunta: "¿Qué incentivos tiene la jubilación demorada?", respuesta: "Un porcentaje adicional del 4% por año o un pago único." },
  { pregunta: "¿Qué es la jubilación flexible?", respuesta: "Compatibilizar pensión con trabajo parcial reduciendo la pensión." },
  { pregunta: "¿Qué es la jubilación parcial?", respuesta: "Acceder a la pensión mientras se trabaja parcialmente con contrato de relevo." },
  { pregunta: "¿Qué porcentaje se reduce en jubilación parcial sin relevo?", respuesta: "No es posible sin relevo salvo excepciones." },
  { pregunta: "¿Qué el contrato de relevo?", respuesta: "Contrato que sustituye parcialmente al trabajador que accede a jubilación parcial." },
  { pregunta: "¿Qué edad mínima exige la jubilación parcial con relevo?", respuesta: "60 años si es mutualista; si no, la edad ordinaria menos 2 años." },
  { pregunta: "¿Qué cotización mínima exige la parcial con relevo?", respuesta: "33 años, o 25 si hay discapacidad del 33%." },
  { pregunta: "¿Qué es la jubilación de mutualistas?", respuesta: "Permite jubilarse a los 60 años con coeficientes reductores." },
  { pregunta: "¿Qué es la jubilación anticipada por actividad penosa?", respuesta: "Reducción de edad por coeficientes en minería, bomberos, artistas, etc." },
  { pregunta: "¿Qué ocurre si el trabajador está en pluriempleo?", respuesta: "Se suman las bases de todos los empleos." },
  { pregunta: "¿Qué ocurre si está en pluriactividad?", respuesta: "Puede generar pensión en ambos regímenes si cumple requisitos." },
  { pregunta: "Anomalía en BR - ¿Qué ocurre con las bases de los últimos 24 meses?", respuesta: "No se actualizan." },
  { pregunta: "¿Qué ocurre si no se cumple la carencia específica?", respuesta: "No se reconoce la pensión." },
  { pregunta: "¿Qué ocurre si se cotiza en varios regímenes?", respuesta: "Se totalizan las cotizaciones." },
  { pregunta: "¿Qué ocurre si no se alcanza carencia en un régimen?", respuesta: "Se aplica totalización internacional o interregímenes." },
  { pregunta: "¿Qué es la totalización internacional?", respuesta: "Sumar cotizaciones de países con convenio." },
  { pregunta: "Anomalía en BR - ¿Qué ocurre si hay lagunas en el Régimen General?", respuesta: "Se integran con base mínima los primeros 48 meses y 50% el resto." },
  { pregunta: "Anomalía en BR - ¿Qué ocurre si hay lagunas en el RETA?", respuesta: "Se computan como cero." },
  { pregunta: "Anomalía en BR - ¿Qué ocurre si el trabajador está en pluriempleo?", respuesta: "Se suman las bases de todos los empleos." },
  { pregunta: "Anomalía en BR - ¿Qué ocurre si está en pluriactividad?", respuesta: "Puede generar pensión en ambos regímenes." },
  { pregunta: "Anomalía en BR - ¿Qué ocurre si se cotiza en dos regímenes pero no se alcanza carencia en uno?", respuesta: "Se totalizan cotizaciones." },
  { pregunta: "Anomalía en BR - ¿Qué ocurre si el trabajador tiene bases muy bajas?", respuesta: "La BR será menor." },
  { pregunta: "Anomalía en BR - ¿Qué ocurre si tiene bases muy altas?", respuesta: "Se aplica el tope máximo de base." },
  { pregunta: "Anomalía en BR - ¿Qué ocurre si tiene deudas con la Seguridad Social?", respuesta: "No afecta a la pensión." },
  { pregunta: "Anomalía en BR - ¿Qué ocurre si tiene sanciones?", respuesta: "No afecta a la pensión." },
  { pregunta: "Anomalía en BR - ¿Qué ocurre si el trabajador está en convenio especial?", respuesta: "Las cotizaciones computan para jubilación." },
  { pregunta: "Anomalía en BR - ¿Qué ocurre si está en ERTE?", respuesta: "Se considera situación asimilada al alta." },
  { pregunta: "Anomalía en BR - ¿Qué ocurre si está en desempleo con prestación?", respuesta: "Situación asimilada al alta." },
  { pregunta: "Anomalía en BR - ¿Qué ocurre si está en excedencia por cuidado de hijos?", respuesta: "Situación asimilada al alta." },
  { pregunta: "Anomalía en BR - ¿Qué ocurre si está en excedencia por cuidado de familiares?", respuesta: "Situación asimilada al alta." },
  { pregunta: "Anomalía en BR - ¿Qué ocurre si el trabajador tiene cotizaciones superpuestas?", respuesta: "Se computan una sola vez." },
  { pregunta: "Anomalía en BR - ¿Qué ocurre si el trabajador tiene cotizaciones en el extranjero?", respuesta: "Se aplican convenios bilaterales o normativa UE." },
  { pregunta: "Anomalía en BR - ¿Qué ocurre si el trabajador tiene cotizaciones en países sin convenio?", respuesta: "No se totalizan." },
  { pregunta: "Anomalía en BR - ¿Qué ocurre si el trabajador tiene cotizaciones en regímenes especiales?", respuesta: "Se totalizan según normativa." },
  { pregunta: "Anomalía en BR - ¿Qué ocurre si el trabajador tiene cotizaciones como autónomo y asalariado?", respuesta: "Puede generar doble pensión si cumple requisitos." },
  { pregunta: "Anomalía en BR - ¿Qué ocurre si el trabajador tiene cotizaciones insuficientes en ambos regímenes?", respuesta: "Se totalizan para una sola pensión." },
  { pregunta: "Anomalía en BR - ¿Qué ocurre si el trabajador tiene cotizaciones en el Sistema Especial Agrario?", respuesta: "Computan para jubilación." },
  { pregunta: "Anomalía en BR - ¿Qué ocurre si el trabajador tiene cotizaciones en el Sistema Especial de Hogar?", respuesta: "Computan para jubilación." },
  { pregunta: "Anomalía en BR - ¿Qué ocurre si el trabajador tiene cotizaciones en el Régimen del Mar?", respuesta: "Computan según normativa del ISM." },
  { pregunta: "Anomalía en BR - ¿Qué ocurre si el trabajador tiene cotizaciones en minería?", respuesta: "Se aplican coeficientes reductores." },
  { pregunta: "¿Qué límite de edad máxima de reducción se aplica a los coeficientes reductores en actividades penosas o peligrosas?", respuesta: "La edad de jubilación no podrá ser, en ningún caso, inferior a los 52 años de edad." },
  { pregunta: "En el cálculo de la Base Reguladora de jubilación, ¿cuántos meses se computan de forma nominal sin actualizar?", respuesta: "Los últimos 24 meses anteriores al mes previo al hecho causante se computan por su valor nominal." },
  { pregunta: "A efectos del cálculo de la Base Reguladora de jubilación, ¿con qué índice se actualizan las bases que no son nominales?", respuesta: "Se actualizan conforme a la evolución del Índice de Precios de Consumo (IPC)." },
  { pregunta: "Si en el cálculo de la Base Reguladora de jubilación aparecen lagunas de cotización, ¿cómo se integran a partir del mes 49?", respuesta: "A partir del mes 49, las lagunas se integran con el 50% de la base mínima de cotización del Régimen General." },
  { pregunta: "¿Se aplica la integración de lagunas para el cálculo de la pensión de jubilación en el RETA (Autónomos)?", respuesta: "No, en el Régimen Especial de Trabajadores Autónomos las lagunas no se integran; se computan como cero." },
  { pregunta: "¿Qué requisito de cuantía se exige para poder percibir la jubilación anticipada por voluntad del interesado?", respuesta: "La cuantía de la pensión a percibir debe ser superior a la cuantía de la pensión mínima que le correspondería por su situación familiar al cumplir los 65 años." },
  { pregunta: "¿Qué antigüedad mínima ininterrumpida en la empresa se exige para acceder a la jubilación parcial antes de la edad ordinaria?", respuesta: "Se exige una antigüedad de al menos 6 años inmediatamente anteriores a la fecha del hecho causante." },
  { pregunta: "En la jubilación parcial con contrato de relevo, ¿cuál es el porcentaje máximo de reducción de jornada con carácter general?", respuesta: "La reducción máxima de la jornada de trabajo es del 75%." },
  { pregunta: "¿Hasta qué porcentaje puede llegar la reducción de jornada en la jubilación parcial si el relevista es contratado a jornada completa e indefinido?", respuesta: "Puede alcanzar un máximo del 85% de reducción de la jornada." },
  { pregunta: "¿Qué porcentaje de cotización adicional se aplica por cada año completo de jubilación demorada?", respuesta: "Se aplica un porcentaje adicional del 4% por cada año completo cotizado desde que se cumplió la edad ordinaria." },
  { pregunta: "Si el interesado elige la modalidad de pago único a tanto alzado en la jubilación demorada y acredita más de 44 años y 6 meses cotizados, ¿en qué porcentaje se incrementa el pago?", respuesta: "La cantidad a tanto alzado resultante se incrementa en un 10% adicional." },
  { pregunta: "¿Es compatible el complemento económico por jubilación demorada con la modalidad de jubilación flexible?", respuesta: "No, el complemento por demora es incompatible con la jubilación parcial, la jubilación flexible y el acceso desde situación asimilada al alta." },
  { pregunta: "¿Qué ocurre con las bases de cotización en los casos de pluriempleo para el cálculo de la base reguladora?", respuesta: "Las bases de cotización acreditadas en las diversas empresas se suman, sin que la suma pueda superar el tope máximo de cotización vigente." },
  { pregunta: "Para una persona que se jubila en el año 2026, ¿cuál es su edad ordinaria si acredita menos de 38 años y 3 meses cotizados?", respuesta: "Su edad ordinaria de jubilación se fija en 66 años y 10 meses." },
  { pregunta: "¿Cuál es el período de carencia específica que se exige para causar derecho a la pensión ordinaria de jubilación?", respuesta: "Acreditar al menos 2 años de cotización comprendidos dentro de los 15 años inmediatamente anteriores al hecho causante." },
  { pregunta: "¿Qué ocurre si el trabajador cumple la edad ordinaria pero no la carencia mínima?", respuesta: "No puede acceder a la jubilación contributiva." },
{ pregunta: "¿Qué ocurre si el trabajador cumple la carencia pero no la edad ordinaria?", respuesta: "Debe esperar a la edad correspondiente." },
{ pregunta: "¿Qué ocurre si el trabajador tiene 37 años cotizados en 2026?", respuesta: "La edad ordinaria será 66 años y 10 meses." },
{ pregunta: "¿Qué ocurre si el trabajador tiene 38 años y 3 meses cotizados en 2026?", respuesta: "Puede jubilarse a los 65 años." },
{ pregunta: "¿Qué ocurre si el trabajador quiere jubilarse anticipadamente de forma voluntaria?", respuesta: "Puede adelantar hasta 2 años." },
{ pregunta: "¿Qué ocurre si el trabajador quiere jubilarse anticipadamente por causa no imputable?", respuesta: "Puede adelantar hasta 4 años." },
{ pregunta: "¿Qué ocurre si el trabajador no está inscrito como demandante de empleo para la anticipada involuntaria?", respuesta: "No puede acceder a esa modalidad." },
{ pregunta: "¿Qué ocurre si el trabajador tiene 35 años cotizados pero no cumple la edad para la anticipada voluntaria?", respuesta: "Debe esperar a la edad mínima." },
{ pregunta: "¿Qué ocurre si el trabajador sigue trabajando tras la edad ordinaria?", respuesta: "Puede recibir complemento por demora." },
{ pregunta: "¿Qué ocurre si el trabajador elige la modalidad de pago único del complemento de demora?", respuesta: "Recibe un pago único según años cotizados." },
{ pregunta: "¿Qué ocurre si el trabajador elige el incremento porcentual del complemento de demora?", respuesta: "Aumenta el porcentaje de la pensión." },
{ pregunta: "¿Qué ocurre si el trabajador tiene hijos para el complemento de brecha de género?", respuesta: "Se añade un complemento mensual por hijo." },
{ pregunta: "¿Qué ocurre si el trabajador tiene 4 hijos?", respuesta: "Se aplica el máximo del complemento." },
{ pregunta: "¿Qué ocurre si el trabajador accede a la jubilación parcial sin contrato de relevo?", respuesta: "No puede acceder antes de la edad ordinaria." },
{ pregunta: "¿Qué ocurre si el contrato de relevo es indefinido y a jornada completa?", respuesta: "La reducción puede llegar al 85%." },
{ pregunta: "¿Qué ocurre si el trabajador tiene 25 años cotizados y discapacidad del 33%?", respuesta: "Puede acceder a jubilación parcial anticipada." },
{ pregunta: "¿Qué ocurre si el trabajador tiene discapacidad del 65%?", respuesta: "Puede anticipar la edad sin coeficientes reductores." },
{ pregunta: "¿Qué ocurre si el trabajador tiene coeficientes reductores por actividad penosa?", respuesta: "Se reduce la edad mínima de acceso." },
{ pregunta: "¿Qué ocurre si la edad reducida queda por debajo de 52 años?", respuesta: "No puede bajar de 52 años." },
{ pregunta: "¿Qué ocurre si el trabajador tiene cotizaciones en varios regímenes?", respuesta: "Se totalizan los periodos." },
{ pregunta: "¿Qué ocurre si el trabajador tiene cotizaciones en el extranjero UE?", respuesta: "Se totalizan según normativa comunitaria." },
{ pregunta: "¿Qué ocurre si el trabajador tiene cotizaciones en país con convenio?", respuesta: "Se totalizan según convenio bilateral." },
{ pregunta: "¿Qué ocurre si el trabajador tiene lagunas en el RG?", respuesta: "Se integran con bases mínimas." },
{ pregunta: "¿Qué ocurre si el trabajador tiene lagunas en RETA?", respuesta: "No se integran lagunas." },
{ pregunta: "¿Qué ocurre si el trabajador tiene bases topadas por máximo?", respuesta: "La BR se calcula con el tope máximo." },
{ pregunta: "¿Qué ocurre si el trabajador tiene bases muy bajas en los primeros años?", respuesta: "Se integran con base mínima." },
{ pregunta: "¿Qué ocurre si el trabajador tiene bases de los últimos 24 meses?", respuesta: "Se computan en valor nominal." },
{ pregunta: "¿Qué ocurre si el trabajador tiene bases anteriores a los últimos 24 meses?", respuesta: "Se actualizan según IPC." },
{ pregunta: "¿Qué ocurre si el trabajador no alcanza el 100% de la BR?", respuesta: "Se aplica el porcentaje correspondiente." },
{ pregunta: "¿Qué ocurre si el trabajador tiene 36 años y 6 meses cotizados en 2026?", respuesta: "Alcanza el 100% de la BR." },
{ pregunta: "¿Qué ocurre con el cómputo de la carencia específica si el trabajador accede a la jubilación desde una situación de alta sin obligación de cotizar?", respuesta: "El período de 2 años se busca dentro de los 15 años anteriores a la fecha en que cesó la obligación de cotizar." },
  { pregunta: "¿Cómo se busca la carencia específica de 2 años si se formaliza una solicitud de jubilación tardía desde una situación de no alta?", respuesta: "Se busca excepcionalmente dentro de los 3 meses anteriores o posteriores al día de la presentación de la solicitud." },
  { pregunta: "Para el cómputo de los períodos de cotización en jubilación ordinaria, ¿cómo se calculan las fracciones de meses o años?", respuesta: "Se toman únicamente años y meses completos, sin que se equiparen a ellos las fracciones de los mismos." },
  { pregunta: "¿Qué límite de incremento se aplica a las bases de cotización en los últimos 2 años para evitar fraudes en la Base Reguladora?", respuesta: "No se computan incrementos superiores al aumento medio interanual del convenio colectivo aplicable (salvo ascensos reglamentarios)." },
  { pregunta: "En el Régimen General, ¿con qué base se integran las lagunas de cotización correspondientes a las primeras 48 mensualidades?", respuesta: "Con la base mínima de cotización del Régimen General que estuviera vigente en el mes correspondiente." },
  { pregunta: "¿A partir de qué año completo de demora en la jubilación se permite computar períodos adicionales superiores a 6 meses para sumar un 2%?", respuesta: "A partir del segundo año completo de demora." },
  { pregunta: "Si se opta por el pago único en la jubilación demorada, ¿cómo se calcula el incentivo por los períodos superiores a 6 meses a partir del segundo año?", respuesta: "Se calcula aplicando un coeficiente multiplicador del 0,5 sobre la cuantía que correspondería por un año completo." },
  { pregunta: "¿Cuáles son las tres situaciones específicas de acceso a la pensión que son totalmente incompatibles con el cobro del complemento por demora?", respuesta: "La jubilación parcial, la jubilación flexible y el acceso desde una situación asimilada al alta." },
  { pregunta: "En la jubilación parcial con contrato de relevo antes de la edad ordinaria, ¿cuál es el porcentaje de reducción de jornada si el relevista es temporal?", respuesta: "La reducción de jornada del jubilado parcial estará comprendida entre un mínimo del 25% y un máximo del 50%." },
  { pregunta: "Para que un trabajador menor de 30 años pueda causar el IMV de forma individual, ¿qué doble requisito de independencia económica se le exige?", respuesta: "Haber vivido de forma independiente durante al menos 2 años y haber estado en alta en la SS al menos 12 meses." }
];