// preguntas13.js - Base de datos específica para las tarjetas del Tema 13
const preguntas = [
  { pregunta: "¿Cuál es la diferencia entre el sistema financiero de reparto y el de capitalización?", respuesta: "El de reparto (general) usa las cuotas de los activos para pagar las prestaciones actuales de los pasivos; el de capitalización (excepcional, como las Mutuas) acumula un capital coste actualizado para contingencias profesionales." },
  { pregunta: "¿Qué conceptos se financian obligatoriamente a través de la Modalidad No Contributiva?", respuesta: "La asistencia sanitaria de la SS (salvo la derivada de AT/EP), los servicios sociales (salvo AT/EP), las pensiones no contributivas por jubilación e invalidez, las prestaciones familiares y el Ingreso Mínimo Vital (IMV)." },
  { pregunta: "¿Qué prestaciones se financian siempre con cargo a la Modalidad Contributiva?", respuesta: "Las prestaciones económicas del sistema (salvo las no contributivas) y la totalidad de las prestaciones derivadas de Accidentes de Trabajo (AT) y Enfermedades Profesionales (EP)." },
  { pregunta: "¿Quién ostenta la titularidad del patrimonio de la Seguridad Social?", respuesta: "La Tesorería General de la Seguridad Social (TGSS), constituyendo un patrimonio único, separado y distinto del patrimonio del Estado." },
  { pregunta: "¿Qué prerrogativa legal protege los bienes del patrimonio de la Seguridad Social frente a los tribunales?", respuesta: "El principio de inembargabilidad absoluta. Ningún tribunal ni autoridad administrativa puede embargar o retener sus bienes, derechos o rentas." },
  { pregunta: "¿Altera la titularidad de la TGSS la adscripción de un bien inmueble a favor de la AGE?", respuesta: "No. La adscripción o cesión de uso temporal no altera en absoluto la titularidad dominical de la TGSS." },
  { pregunta: "¿Cuál es la causa general de reversión de un bien inmueble adscrito?", respuesta: "El desuso o el cambio de destino del inmueble con respecto a los fines que motivaron su adscripción, salvo autorización expresa del titular del MISSM." },
  { pregunta: "¿Qué procedimiento ordinario se exige para la adquisición onerosa de bienes inmuebles por parte de la SS?", respuesta: "El concurso público, salvo casos de urgencia extrema o necesidad excepcional autorizados directamente por el MISSM." },
  { pregunta: "¿Qué procedimiento ordinario se exige para la enajenación (venta) de inmuebles de la Seguridad Social?", respuesta: "La subasta pública. El trato directo excepcional requiere la autorización del Consejo de Ministros (o del Ministro si no supera el umbral legal)." },
  { pregunta: "¿Cuál es la duración máxima (incluyendo prórrogas) de un contrato de arrendamiento de un inmueble de la SS?", respuesta: "No podrá exceder en ningún caso los 30 años (duración inicial máxima inferior a 20 años)." },
  { pregunta: "¿Qué órgano acuerda la dotación ordinaria del Fondo de Reserva y a propuesta de quién?", respuesta: "El Consejo de Ministros, al menos una vez por ejercicio, a propuesta conjunta de los ministerios de: MISSM, Asuntos Económicos y Hacienda." },
  { pregunta: "¿Qué dos recursos capitalizan de forma automática en el Fondo de Reserva sin necesidad de acuerdo anual?", respuesta: "La recaudación líquida de la cotización finalista del MEI y los propios rendimientos financieros que generen los activos del Fondo." },
  { pregunta: "¿Cuál es el periodo de aplicación establecido para el Mecanismo de Equidad Intergeneracional (MEI)?", respuesta: "Tiene carácter temporal y finalista, estando prevista su aplicación desde el año 2023 hasta el año 2050." },
  { pregunta: "A partir de 2033, ¿cómo se calcula el límite máximo de disposición anual de activos del Fondo de Reserva?", respuesta: "Se fija como un porcentaje sobre el PIB nacional determinado por la LPGE (iniciando con un 0,10% en 2033 y un máximo del 0,50% del PIB a partir de 2053)." },
  { pregunta: "¿Qué consideración tiene la TGSS respecto al circuito financiero del sistema?", respuesta: "Es la 'Caja Única' del sistema, centralizando la gestión de ingresos, circuito de cuentas en entidades financieras y ordenación de pagos." },
  { pregunta: "¿Cuál es el plazo legal ordinario para que las pensiones periódicas estén a disposición de los beneficiarios?", respuesta: "Desde el primer día hábil del mes de su pago hasta, como máximo, el cuarto día natural del mismo mes." },
  { pregunta: "¿En cuántas pagas anuales se devengan las pensiones contributivas por contingencias comunes?", respuesta: "En 14 pagas anuales (12 mensualidades ordinarias lineales y 2 pagas extraordinarias que se abonan en junio y noviembre)." },
  { pregunta: "¿Cuáles son las fuentes de financiación del sistema según el art. 109 TRLGSS?", respuesta: "Aportaciones del Estado, cuotas, recargos y sanciones, frutos y rentas, y otros ingresos." },
{ pregunta: "¿Cuál es el principio financiero general del sistema de la Seguridad Social?", respuesta: "El principio de reparto." },
{ pregunta: "¿Qué modalidad financia el Estado mediante los Presupuestos Generales?", respuesta: "La modalidad no contributiva." },
{ pregunta: "¿Qué modalidad financia las prestaciones económicas contributivas?", respuesta: "La modalidad contributiva." },
{ pregunta: "¿Cómo se financian las prestaciones por AT y EP?", respuesta: "Por la modalidad contributiva." },
{ pregunta: "¿El IMV se financia por la modalidad contributiva o no contributiva?", respuesta: "Por la modalidad no contributiva." },

{ pregunta: "¿Quién es el titular del patrimonio único de la Seguridad Social?", respuesta: "La Tesorería General de la Seguridad Social." },
{ pregunta: "¿El patrimonio de la Seguridad Social está separado del patrimonio del Estado?", respuesta: "Sí, es completamente distinto y separado." },
{ pregunta: "¿Es embargable el patrimonio de la Seguridad Social?", respuesta: "No, es inembargable." },
{ pregunta: "¿La adscripción de un inmueble a la AGE altera la titularidad de la TGSS?", respuesta: "No, la titularidad no se altera." },
{ pregunta: "¿Qué causa la reversión de un inmueble adscrito?", respuesta: "El no uso o el cambio de destino." },
{ pregunta: "¿Qué excepción existe a la reversión de un inmueble adscrito?", respuesta: "La autorización formal del MISSM para el cambio de uso." },

{ pregunta: "¿Cuál es el procedimiento general para la adquisición onerosa de inmuebles?", respuesta: "El concurso público." },
{ pregunta: "¿Quién puede autorizar la adquisición directa por urgencia extrema?", respuesta: "El MISSM, previo informe de la TGSS." },
{ pregunta: "¿Cuál es el procedimiento general para la enajenación de inmuebles?", respuesta: "La subasta pública." },
{ pregunta: "¿Quién autoriza la enajenación directa de inmuebles?", respuesta: "El Consejo de Ministros o el Ministro según el valor." },
{ pregunta: "¿Cuándo es válida una permuta sin compensación en dinero?", respuesta: "Cuando el bien de la SS no supera el 50% del valor del otro bien." },
{ pregunta: "¿Dónde deben venderse los títulos valores del patrimonio de la SS?", respuesta: "En mercados oficiales." },
{ pregunta: "¿Cuál es el procedimiento general para arrendar inmuebles de la SS?", respuesta: "El concurso público." },
{ pregunta: "¿Cuál es la duración máxima de un arrendamiento incluyendo prórrogas?", respuesta: "30 años." },
{ pregunta: "¿Quién autoriza la cesión gratuita de uso de inmuebles?", respuesta: "El titular del MISSM, a propuesta de la TGSS." },

{ pregunta: "¿Cuál es la finalidad del Fondo de Reserva?", respuesta: "Atender necesidades financieras de prestaciones contributivas." },
{ pregunta: "¿Cuántas fuentes de financiación tiene el Fondo de Reserva?", respuesta: "Cuatro: excedentes presupuestarios, excedentes de mutuas CC, excedentes de mutuas CP y MEI." },
{ pregunta: "¿Qué órgano acuerda la dotación ordinaria del Fondo de Reserva?", respuesta: "El Consejo de Ministros." },
{ pregunta: "¿Qué ministerios proponen la dotación ordinaria del Fondo?", respuesta: "MISSM, Asuntos Económicos y Hacienda." },
{ pregunta: "¿Qué ingresos se capitalizan automáticamente sin acuerdo político?", respuesta: "La recaudación líquida del MEI y los rendimientos financieros." },
{ pregunta: "¿Desde qué año se aplica el límite anual de disposición del Fondo?", respuesta: "Desde 2033." },
{ pregunta: "¿Cuál es el límite de disposición del Fondo en 2033?", respuesta: "El 0,10% del PIB." },
{ pregunta: "¿Cuál es el límite máximo de disposición anual a partir de 2053?", respuesta: "El 0,50% del PIB." },
{ pregunta: "¿Cuál es el periodo de aplicación del MEI?", respuesta: "De 2023 a 2050." },

{ pregunta: "¿Qué organismo gestiona la caja única del sistema?", respuesta: "La Tesorería General de la Seguridad Social." },
{ pregunta: "¿Desde cuándo deben estar disponibles los pagos periódicos de prestaciones?", respuesta: "Desde el primer día hábil del mes." },
{ pregunta: "¿Cuál es el plazo máximo para que estén disponibles los pagos periódicos?", respuesta: "El cuarto día natural del mes." },
{ pregunta: "¿Cuántas pagas anuales tienen las prestaciones contributivas por contingencias comunes?", respuesta: "14 pagas." },
{ pregunta: "¿Qué naturaleza jurídica tiene el patrimonio único de la Seguridad Social?", respuesta: "Es un patrimonio de titularidad pública adscrito a la TGSS." },
{ pregunta: "¿Qué organismo administra y gestiona el patrimonio único de la Seguridad Social?", respuesta: "La Tesorería General de la Seguridad Social." },
{ pregunta: "¿Qué carácter tiene la caja única del sistema?", respuesta: "Carácter centralizado y no territorializado." },
{ pregunta: "¿Qué principio rige la gestión financiera del sistema?", respuesta: "El principio de solidaridad financiera." },
{ pregunta: "¿Qué ingresos forman parte de los frutos y rentas del patrimonio?", respuesta: "Arrendamientos, intereses, rendimientos financieros y otros productos patrimoniales." },
{ pregunta: "¿Qué ingresos se consideran 'otros ingresos' según el art. 109 TRLGSS?", respuesta: "Los no incluidos en las restantes categorías, como donaciones o legados." },
{ pregunta: "¿Qué órgano autoriza la adquisición de bienes inmuebles por permuta?", respuesta: "El MISSM, previo informe de la TGSS." },
{ pregunta: "¿Qué límite económico determina si la enajenación de inmuebles debe autorizarla el Consejo de Ministros?", respuesta: "El valor superior al umbral fijado en la Ley de Patrimonio de las Administraciones Públicas." },
{ pregunta: "¿Qué tipo de bienes pueden cederse gratuitamente por la TGSS?", respuesta: "Bienes inmuebles no necesarios para sus fines." },
{ pregunta: "¿Qué requisito exige la cesión gratuita de uso de inmuebles?", respuesta: "Que el cesionario sea una entidad pública o sin ánimo de lucro." },
{ pregunta: "¿Qué órgano autoriza la cesión gratuita de uso de inmuebles?", respuesta: "El titular del MISSM." },
{ pregunta: "¿Qué ocurre si un inmueble cedido gratuitamente deja de destinarse al fin previsto?", respuesta: "Se revoca la cesión y el inmueble revierte a la TGSS." },
{ pregunta: "¿Qué bienes pueden ser objeto de adscripción a la AGE?", respuesta: "Inmuebles del patrimonio de la Seguridad Social." },
{ pregunta: "¿Qué efecto tiene la adscripción sobre la titularidad del bien?", respuesta: "Ninguno, la titularidad sigue siendo de la TGSS." },
{ pregunta: "¿Qué órgano puede autorizar la desafectación de un bien adscrito?", respuesta: "El MISSM." },

{ pregunta: "¿Qué finalidad tiene la gestión de la caja única?", respuesta: "Garantizar la disponibilidad de fondos para el pago de prestaciones." },
{ pregunta: "¿Qué pagos tienen prioridad absoluta en la caja única?", respuesta: "Las prestaciones económicas del sistema." },
{ pregunta: "¿Qué organismo ordena los pagos del sistema?", respuesta: "La Tesorería General de la Seguridad Social." },
{ pregunta: "¿Qué organismo ejecuta materialmente los pagos?", respuesta: "Las entidades financieras colaboradoras." },

{ pregunta: "¿Qué ingresos integran el Fondo de Reserva además del MEI?", respuesta: "Excedentes presupuestarios y excedentes de mutuas por contingencias comunes y profesionales." },
{ pregunta: "¿Qué órgano autoriza la disposición del Fondo de Reserva?", respuesta: "El Consejo de Ministros." },
{ pregunta: "¿Qué informe es obligatorio antes de disponer del Fondo de Reserva?", respuesta: "Informe del MISSM y del Ministerio de Hacienda." },
{ pregunta: "¿Qué tipo de inversiones puede realizar el Fondo de Reserva?", respuesta: "Inversiones seguras, líquidas y de alta calidad crediticia." },
{ pregunta: "¿Quién gestiona materialmente las inversiones del Fondo de Reserva?", respuesta: "La Tesorería General de la Seguridad Social." },
{ pregunta: "¿Qué periodicidad tiene el informe anual del Fondo de Reserva?", respuesta: "Anual, dirigido a las Cortes Generales." },
{ pregunta: "¿Qué debe incluir el informe anual del Fondo de Reserva?", respuesta: "Movimientos, rendimientos, disposiciones y situación financiera." },

{ pregunta: "¿Qué ingresos se destinan automáticamente al Fondo de Reserva sin acuerdo del Gobierno?", respuesta: "La recaudación líquida del MEI y los rendimientos financieros del propio Fondo." },
{ pregunta: "¿Qué límite de disposición se aplica entre 2033 y 2052?", respuesta: "Un límite progresivo creciente desde el 0,10% del PIB." },
{ pregunta: "¿Qué límite máximo se aplica a partir de 2053?", respuesta: "El 0,50% del PIB." },
{ pregunta: "¿Qué objetivo tiene el MEI dentro del sistema financiero?", respuesta: "Reforzar la sostenibilidad del sistema y nutrir el Fondo de Reserva." },
{ pregunta: "¿Cuáles son las fuentes de financiación del sistema según el art. 109 TRLGSS?", respuesta: "Aportaciones del Estado, cuotas, recargos y sanciones, frutos y rentas, y otros ingresos." },
{ pregunta: "¿Cuál es el principio financiero general del sistema de la Seguridad Social?", respuesta: "El principio de reparto." },
{ pregunta: "¿Qué modalidad financia el Estado mediante los Presupuestos Generales?", respuesta: "La modalidad no contributiva." },
{ pregunta: "¿Qué modalidad financia las prestaciones económicas contributivas?", respuesta: "La modalidad contributiva." },
{ pregunta: "¿Cómo se financian las prestaciones por AT y EP?", respuesta: "Por la modalidad contributiva." },
{ pregunta: "¿El IMV se financia por la modalidad contributiva o no contributiva?", respuesta: "Por la modalidad no contributiva." },
{ pregunta: "¿Qué ingresos forman parte de los frutos y rentas del patrimonio?", respuesta: "Arrendamientos, intereses, rendimientos financieros y otros productos patrimoniales." },
{ pregunta: "¿Qué ingresos se consideran otros ingresos según el art. 109 TRLGSS?", respuesta: "Los no incluidos en las restantes categorías, como donaciones o legados." },
{ pregunta: "¿Qué principio rige la gestión financiera del sistema?", respuesta: "El principio de solidaridad financiera." },
{ pregunta: "¿Qué principio rige la financiación del sistema?", respuesta: "El principio de caja única." },

{ pregunta: "¿Quién es el titular del patrimonio único de la Seguridad Social?", respuesta: "La Tesorería General de la Seguridad Social." },
{ pregunta: "¿El patrimonio de la Seguridad Social está separado del patrimonio del Estado?", respuesta: "Sí, es completamente distinto y separado." },
{ pregunta: "¿Es embargable el patrimonio de la Seguridad Social?", respuesta: "No, es inembargable." },
{ pregunta: "¿La adscripción de un inmueble a la AGE altera la titularidad de la TGSS?", respuesta: "No, la titularidad no se altera." },
{ pregunta: "¿Qué causa la reversión de un inmueble adscrito?", respuesta: "El no uso o el cambio de destino." },
{ pregunta: "¿Qué excepción existe a la reversión de un inmueble adscrito?", respuesta: "La autorización formal del MISSM para el cambio de uso." },
{ pregunta: "¿Qué bienes pueden ser objeto de adscripción a la AGE?", respuesta: "Inmuebles del patrimonio de la Seguridad Social." },
{ pregunta: "¿Qué efecto tiene la adscripción sobre la titularidad del bien?", respuesta: "Ninguno, la titularidad sigue siendo de la TGSS." },
{ pregunta: "¿Qué órgano puede autorizar la desafectación de un bien adscrito?", respuesta: "El MISSM." },
{ pregunta: "¿Qué naturaleza jurídica tiene el patrimonio único de la Seguridad Social?", respuesta: "Es un patrimonio público adscrito a la TGSS." },

{ pregunta: "¿Cuál es el procedimiento general para la adquisición onerosa de inmuebles?", respuesta: "El concurso público." },
{ pregunta: "¿Quién puede autorizar la adquisición directa por urgencia extrema?", respuesta: "El MISSM, previo informe de la TGSS." },
{ pregunta: "¿Cuál es el procedimiento general para la enajenación de inmuebles?", respuesta: "La subasta pública." },
{ pregunta: "¿Quién autoriza la enajenación directa de inmuebles?", respuesta: "El Consejo de Ministros o el Ministro según el valor." },
{ pregunta: "¿Cuándo es válida una permuta sin compensación en dinero?", respuesta: "Cuando el bien de la SS no supera el 50% del valor del otro bien." },
{ pregunta: "¿Dónde deben venderse los títulos valores del patrimonio de la SS?", respuesta: "En mercados oficiales." },
{ pregunta: "¿Cuál es el procedimiento general para arrendar inmuebles de la SS?", respuesta: "El concurso público." },
{ pregunta: "¿Cuál es la duración máxima de un arrendamiento incluyendo prórrogas?", respuesta: "30 años." },
{ pregunta: "¿Quién autoriza la cesión gratuita de uso de inmuebles?", respuesta: "El titular del MISSM." },
{ pregunta: "¿Qué requisito exige la cesión gratuita de uso de inmuebles?", respuesta: "Que el cesionario sea una entidad pública o sin ánimo de lucro." },

{ pregunta: "¿Qué ocurre si un inmueble cedido gratuitamente deja de destinarse al fin previsto?", respuesta: "Se revoca la cesión y el inmueble revierte a la TGSS." },
{ pregunta: "¿Qué órgano autoriza la permuta de bienes inmuebles?", respuesta: "El MISSM." },
{ pregunta: "¿Qué órgano autoriza la adquisición de bienes muebles de alto valor?", respuesta: "El MISSM." },
{ pregunta: "¿Qué órgano autoriza la enajenación de bienes muebles no inventariables?", respuesta: "La TGSS." },
{ pregunta: "¿Qué órgano autoriza la enajenación de bienes muebles inventariables?", respuesta: "El MISSM." },
{ pregunta: "¿Qué procedimiento se utiliza para enajenar bienes muebles?", respuesta: "Subasta o adjudicación directa según valor." },
{ pregunta: "¿Qué órgano autoriza la cesión gratuita de bienes muebles?", respuesta: "La TGSS." },
{ pregunta: "¿Qué órgano autoriza la afectación de bienes al uso de entidades gestoras?", respuesta: "La TGSS." },
{ pregunta: "¿Qué órgano autoriza la desafectación de bienes muebles?", respuesta: "La TGSS." },
{ pregunta: "¿Qué órgano autoriza la adquisición de bienes inmuebles por donación?", respuesta: "El MISSM." },

{ pregunta: "¿Cuál es la finalidad del Fondo de Reserva?", respuesta: "Atender necesidades financieras de prestaciones contributivas." },
{ pregunta: "¿Cuántas fuentes de financiación tiene el Fondo de Reserva?", respuesta: "Cuatro: excedentes presupuestarios, excedentes de mutuas CC, excedentes de mutuas CP y MEI." },
{ pregunta: "¿Qué órgano acuerda la dotación ordinaria del Fondo de Reserva?", respuesta: "El Consejo de Ministros." },
{ pregunta: "¿Qué ministerios proponen la dotación ordinaria del Fondo?", respuesta: "MISSM, Asuntos Económicos y Hacienda." },
{ pregunta: "¿Qué ingresos se capitalizan automáticamente sin acuerdo político?", respuesta: "La recaudación líquida del MEI y los rendimientos financieros." },
{ pregunta: "¿Desde qué año se aplica el límite anual de disposición del Fondo?", respuesta: "Desde 2033." },
{ pregunta: "¿Cuál es el límite de disposición del Fondo en 2033?", respuesta: "El 0,10% del PIB." },
{ pregunta: "¿Cuál es el límite máximo de disposición anual a partir de 2053?", respuesta: "El 0,50% del PIB." },
{ pregunta: "¿Cuál es el periodo de aplicación del MEI?", respuesta: "De 2023 a 2050." },
{ pregunta: "¿Qué objetivo tiene el MEI dentro del sistema financiero?", respuesta: "Reforzar la sostenibilidad del sistema y nutrir el Fondo de Reserva." },

{ pregunta: "¿Qué organismo gestiona la caja única del sistema?", respuesta: "La Tesorería General de la Seguridad Social." },
{ pregunta: "¿Desde cuándo deben estar disponibles los pagos periódicos de prestaciones?", respuesta: "Desde el primer día hábil del mes." },
{ pregunta: "¿Cuál es el plazo máximo para que estén disponibles los pagos periódicos?", respuesta: "El cuarto día natural del mes." },
{ pregunta: "¿Cuántas pagas anuales tienen las prestaciones contributivas por contingencias comunes?", respuesta: "14 pagas." },
{ pregunta: "¿Qué pagos tienen prioridad absoluta en la caja única?", respuesta: "Las prestaciones económicas del sistema." },
{ pregunta: "¿Qué organismo ordena los pagos del sistema?", respuesta: "La TGSS." },
{ pregunta: "¿Qué organismo ejecuta materialmente los pagos?", respuesta: "Las entidades financieras colaboradoras." },
{ pregunta: "¿Qué principio garantiza la caja única?", respuesta: "La unidad de tesorería." },
{ pregunta: "¿Qué documento recoge la previsión anual de pagos?", respuesta: "El plan de disposición de fondos." },
{ pregunta: "¿Quién aprueba el plan de disposición de fondos?", respuesta: "La TGSS." },

{ pregunta: "¿Qué inversiones puede realizar el Fondo de Reserva?", respuesta: "Inversiones seguras, líquidas y de alta calidad crediticia." },
{ pregunta: "¿Quién gestiona materialmente las inversiones del Fondo de Reserva?", respuesta: "La TGSS." },
{ pregunta: "¿Qué periodicidad tiene el informe del Fondo de Reserva?", respuesta: "Anual." },
{ pregunta: "¿A quién se dirige el informe anual del Fondo de Reserva?", respuesta: "A las Cortes Generales." },
{ pregunta: "¿Qué debe incluir el informe anual del Fondo de Reserva?", respuesta: "Movimientos, rendimientos, disposiciones y situación financiera." },
{ pregunta: "¿Qué ingresos integran el Fondo de Reserva además del MEI?", respuesta: "Excedentes presupuestarios y excedentes de mutuas." },
{ pregunta: "¿Qué órgano autoriza la disposición del Fondo de Reserva?", respuesta: "El Consejo de Ministros." },
{ pregunta: "¿Qué informe es obligatorio antes de disponer del Fondo de Reserva?", respuesta: "Informe del MISSM y del Ministerio de Hacienda." },
{ pregunta: "¿Qué límite de disposición se aplica entre 2033 y 2052?", respuesta: "Un límite progresivo creciente desde el 0,10% del PIB." },
{ pregunta: "¿Qué límite máximo se aplica a partir de 2053?", respuesta: "El 0,50% del PIB." },

{ pregunta: "¿Qué principio rige la afectación de bienes al sistema?", respuesta: "El principio de destino específico." },
{ pregunta: "¿Qué bienes forman parte del patrimonio único?", respuesta: "Bienes y derechos afectos a la Seguridad Social." },
{ pregunta: "¿Qué organismo lleva el inventario de bienes de la Seguridad Social?", respuesta: "La TGSS." },
{ pregunta: "¿Qué órgano autoriza la baja de bienes muebles inventariables?", respuesta: "La TGSS." },
{ pregunta: "¿Qué órgano autoriza la baja de bienes inmuebles?", respuesta: "El MISSM." },
{ pregunta: "¿Qué órgano autoriza la cesión de uso de bienes inmuebles a comunidades autónomas?", respuesta: "El MISSM." },
{ pregunta: "¿Qué órgano autoriza la cesión de uso a ayuntamientos?", respuesta: "El MISSM." },
{ pregunta: "¿Qué órgano autoriza la ocupación temporal de bienes de la SS?", respuesta: "La TGSS." },
{ pregunta: "¿Qué órgano autoriza la concesión de uso privativo de bienes?", respuesta: "El MISSM." },
{ pregunta: "¿Qué órgano autoriza la afectación de bienes a entidades gestoras?", respuesta: "La TGSS." },

{ pregunta: "¿Qué ingresos se destinan automáticamente al Fondo de Reserva sin acuerdo del Gobierno?", respuesta: "La recaudación líquida del MEI y los rendimientos financieros." },
{ pregunta: "¿Qué finalidad tiene la gestión patrimonial de la SS?", respuesta: "Garantizar la sostenibilidad del sistema." },
{ pregunta: "¿Qué principio rige la administración del patrimonio?", respuesta: "El principio de eficacia y eficiencia." },
{ pregunta: "¿Qué órgano aprueba el inventario de bienes inmuebles?", respuesta: "La TGSS." },
{ pregunta: "¿Qué órgano autoriza la ocupación gratuita de bienes?", respuesta: "La TGSS." },
{ pregunta: "¿Qué órgano autoriza la ocupación onerosa de bienes?", respuesta: "La TGSS." },
{ pregunta: "¿Qué órgano autoriza la desafectación de bienes inmuebles?", respuesta: "El MISSM." },
{ pregunta: "¿Qué órgano autoriza la permuta de bienes muebles?", respuesta: "La TGSS." },
{ pregunta: "¿Qué órgano autoriza la venta de bienes muebles por deterioro?", respuesta: "La TGSS." },
{ pregunta: "¿Qué órgano autoriza la destrucción de bienes muebles inservibles?", respuesta: "La TGSS." }
];

