const preguntas = [
  { pregunta: "¿Qué carácter tiene el número de afiliación a la SS?", respuesta: "Es vitalicio, único para todo el sistema y no cambia jamás independientemente de los regímenes." },
  { pregunta: "¿Cuál es el plazo para tramitar el alta de un trabajador por cuenta ajena?", respuesta: "Siempre de forma previa al inicio de la actividad, hasta 60 días naturales antes de empezar a trabajar." },
  { pregunta: "¿De qué plazo dispone la empresa para comunicar bajas o variaciones de datos?", respuesta: "Un plazo máximo de 3 días naturales contados a partir del día siguiente al del cese o modificación." },
  { pregunta: "¿Qué ocurre con los efectos de un alta solicitada fuera de plazo con retraso?", respuesta: "La obligación de cotizar nace desde el inicio del trabajo, pero los efectos de las prestaciones nacen el día de la solicitud." },
  { pregunta: "¿Qué es una situación de 'alta asimilada' y qué ejemplos clave entran en examen?", respuesta: "Situación legal tras el cese laboral que mantiene la protección activa: ej. desempleo total, excedencia forzosa o maternidad." },
  { pregunta: "¿Quiénes están legitimados para solicitar la afiliación y el alta de un trabajador?", respuesta: "El empresario (obligado principal), el propio trabajador (en su defecto) o de oficio la TGSS tras una inspección." },
  { pregunta: "¿Cómo se define el 'Hecho Causante' en las prestaciones de la Seguridad Social?", respuesta: "Es la situación fáctica o jurídica que genera la contingencia y fija el momento exacto en que nace el derecho al cobro." },
  { pregunta: "¿Cuáles son los plazos para comunicar el alta y la baja en el RETA (Autónomos)?", respuesta: "Se deben comunicar obligatoriamente dentro de los 3 días naturales siguientes al inicio o cese de la actividad por cuenta propia." },
  { pregunta: "¿Cuál es el plazo de prescripción que tiene la TGSS para reclamar deudas por cuotas?", respuesta: "Un plazo de 4 años, a contar desde el día siguiente al vencimiento del plazo reglamentario de su ingreso." },
  { pregunta: "¿En qué consiste la 'Base de Cotización' y cómo se calcula?", respuesta: "Es la remuneración mensual bruta del trabajador (con extras prorrateadas), topada por máximos y mínimos según su grupo." },
  { pregunta: "¿Qué conceptos económicos están legalmente excluidos de la base de cotización?", respuesta: "Dietas y asignaciones de viaje (en topes legales), gastos de locomoción, indemnizaciones por despido y prestaciones de la SS." },
  { pregunta: "¿Cuál es el plazo reglamentario de ingreso de las cuotas de la SS por las empresas?", respuesta: "Se ingresan por mensualidades vencidas, obligatoriamente dentro del mes natural siguiente (marzo se paga en abril)." },
  { pregunta: "¿Qué recargo aplica si se presentan los documentos en plazo pero no se pagan las cuotas?", respuesta: "Aplica un recargo reducido del 10% si se abonan las cuotas dentro del primer mes natural siguiente al del vencimiento." },
  { pregunta: "¿Qué recargo aplica si NO se presentan los documentos en plazo y no se pagan las cuotas?", respuesta: "El recargo asciende de forma automática al 20% al no haberse cumplido la obligación de transmitir las relaciones de trabajadores." },
  { pregunta: "¿Qué acto administrativo asigna el Código de Cuenta de Cotización (CCC) a una empresa?", respuesta: "La inscripción de la empresa ante la TGSS." },
  { pregunta: "¿Cuál es el plazo para solicitar la inscripción de una empresa en la Seguridad Social?", respuesta: "Debe solicitarse antes del inicio de la actividad, sin límite máximo de anticipación." },
  { pregunta: "¿Qué plazo tiene la empresa para subsanar documentación en el procedimiento de inscripción?", respuesta: "10 días naturales." },
  { pregunta: "¿Cuál es el plazo de resolución de la TGSS en la inscripción de empresas?", respuesta: "45 días, con silencio administrativo estimatorio." },
  { pregunta: "¿En cuántos días debe comunicarse una variación de datos de la empresa?", respuesta: "En 3 días naturales desde que se produzca la variación." },
  { pregunta: "¿En cuántos días debe comunicarse un cambio de mutua colaboradora?", respuesta: "10 días naturales antes de la fecha de efectividad." },
  { pregunta: "¿En cuántos días debe comunicarse una sucesión empresarial?", respuesta: "6 días naturales." },
  { pregunta: "¿Qué características tiene la afiliación a la Seguridad Social?", respuesta: "Es obligatoria, única, general, exclusiva y permanente." },
  { pregunta: "¿Quién está obligado a solicitar la afiliación de un trabajador por cuenta ajena?", respuesta: "El empresario, antes del inicio de la actividad." },
  { pregunta: "¿Qué ocurre si el empresario no solicita la afiliación del trabajador?", respuesta: "El trabajador puede solicitarla directamente y la TGSS dará cuenta a la Inspección." },
  { pregunta: "¿Cuál es el plazo máximo de anticipación para comunicar un alta en el Régimen General?", respuesta: "60 días naturales antes del inicio de la actividad." },
  { pregunta: "¿Cuál es el plazo para comunicar una baja en el Régimen General?", respuesta: "3 días naturales desde el cese." },
  { pregunta: "¿Qué efectos tiene una baja comunicada fuera de plazo?", respuesta: "La obligación de cotizar continúa hasta que la TGSS tenga conocimiento del cese." },
  { pregunta: "¿Qué efectos tiene un alta fuera de plazo?", respuesta: "Surte efectos desde la fecha de la solicitud, salvo ingreso en plazo reglamentario." },
  { pregunta: "¿Qué efectos tiene un alta de oficio practicada por la Inspección de Trabajo?", respuesta: "Se retrotrae a la fecha de la actuación inspectora." },
  { pregunta: "¿Qué diferencia hay entre pluriempleo y pluriactividad?", respuesta: "Pluriempleo: varios empleadores en el mismo régimen. Pluriactividad: actividades en regímenes distintos." },
  { pregunta: "¿Quién elige el régimen de encuadramiento de los socios trabajadores de cooperativas de trabajo asociado?", respuesta: "La cooperativa, mediante sus estatutos, aplicable a todos los socios por igual." },
  { pregunta: "¿Cuál es el plazo para solicitar un convenio especial tras el cese?", respuesta: "1 año desde el día siguiente al cese." },
  { pregunta: "¿Cuántos días cotizados se exigen para suscribir un convenio especial?", respuesta: "1.080 días en los últimos 12 años." },
  { pregunta: "¿Qué tipo de silencio administrativo se aplica en la solicitud del convenio especial?", respuesta: "Silencio positivo: se entiende estimado si no hay resolución en 3 meses." },
    { pregunta: "¿Qué efectos tiene un alta fuera de plazo cuando el empresario ingresa las cuotas dentro del plazo reglamentario?", respuesta: "El alta surte efectos desde la fecha real de inicio de la actividad." },
  { pregunta: "¿Qué efectos tiene un alta fuera de plazo cuando el empresario NO ingresa las cuotas en plazo?", respuesta: "El alta surte efectos desde la fecha de la solicitud." },
  { pregunta: "¿Qué ocurre si la empresa comunica un alta con datos erróneos?", respuesta: "Debe presentar una variación de datos en 3 días naturales." },
  { pregunta: "¿Qué ocurre si la empresa comunica una baja con fecha anterior al cese real?", respuesta: "La TGSS corrige la fecha y mantiene la obligación de cotizar hasta el cese real." },
  { pregunta: "¿Qué ocurre si la empresa no comunica la baja del trabajador?", respuesta: "La obligación de cotizar continúa hasta que la TGSS tenga conocimiento del cese." },
  { pregunta: "¿Qué ocurre si la empresa comunica una baja indebida?", respuesta: "La TGSS puede anularla y dar cuenta a la Inspección de Trabajo." },
  { pregunta: "¿Qué ocurre si un trabajador inicia actividad sin estar dado de alta?", respuesta: "La TGSS puede practicar un alta de oficio con efectos retroactivos." },
  { pregunta: "¿Qué ocurre si un trabajador solicita su propia afiliación?", respuesta: "La TGSS la tramita y comunica la omisión a la Inspección." },
  { pregunta: "¿Qué ocurre si un trabajador solicita su propio alta?", respuesta: "Solo es válido en supuestos excepcionales; la obligación corresponde al empresario." },
  { pregunta: "¿Qué ocurre si un trabajador está en pluriempleo?", respuesta: "Debe tener un único número de afiliación y varios CCC asociados." },
  { pregunta: "¿Qué ocurre si un trabajador está en pluriactividad?", respuesta: "Cotiza en cada régimen por la actividad que realiza." },
  { pregunta: "¿Qué ocurre si un trabajador autónomo inicia actividad sin comunicar el alta?", respuesta: "La TGSS puede practicar un alta de oficio con efectos desde el inicio real." },
  { pregunta: "¿Qué ocurre si un autónomo comunica el cese fuera de plazo?", respuesta: "La obligación de cotizar continúa hasta la comunicación efectiva." },
  { pregunta: "¿Qué ocurre si un autónomo solicita el alta con efectos retroactivos?", respuesta: "No es posible salvo error administrativo." },
  { pregunta: "¿Qué ocurre si un autónomo societario no comunica su alta?", respuesta: "La TGSS puede practicar alta de oficio y reclamar cuotas." },
  { pregunta: "¿Qué ocurre si un socio trabajador de cooperativa cambia de régimen de encuadramiento?", respuesta: "Debe modificarse el acuerdo estatutario para todos los socios." },
  { pregunta: "¿Qué ocurre si un trabajador por cuenta ajena pasa a ser autónomo en la misma empresa?", respuesta: "Debe analizarse si existe realmente actividad independiente para evitar falsos autónomos." },
  { pregunta: "¿Qué ocurre si un trabajador es contratado por una ETT?", respuesta: "La ETT es la obligada a comunicar altas y bajas." },
  { pregunta: "¿Qué ocurre si un trabajador es cedido ilegalmente?", respuesta: "La empresa usuaria asume las obligaciones de Seguridad Social." },
  { pregunta: "¿Qué ocurre si un trabajador es desplazado temporalmente al extranjero?", respuesta: "Puede mantenerse en el sistema español mediante formulario de desplazamiento." },
  { pregunta: "¿Qué ocurre si un trabajador regresa del extranjero tras un desplazamiento?", respuesta: "Recupera su situación previa en el sistema español." },
  { pregunta: "¿Qué ocurre si un trabajador se desplaza a un país sin convenio bilateral?", respuesta: "Debe suscribir un convenio especial para mantener cotizaciones." },
  { pregunta: "¿Qué ocurre si un trabajador se desplaza a un país con convenio bilateral?", respuesta: "Se aplica la legislación del país de origen durante el periodo autorizado." },
  { pregunta: "¿Qué ocurre si un trabajador se desplaza dentro de la UE?", respuesta: "Se aplica el Reglamento 883/2004 y el formulario A1." },
  { pregunta: "¿Qué ocurre si un trabajador pierde su condición de asimilado al alta?", respuesta: "Deja de cotizar salvo que suscriba un convenio especial." },
  { pregunta: "¿Qué ocurre si un trabajador está en excedencia por cuidado de hijos?", respuesta: "Se considera situación asimilada al alta a efectos de prestaciones." },
  { pregunta: "¿Qué ocurre si un trabajador está en excedencia por cuidado de familiares?", respuesta: "Se considera situación asimilada al alta durante el primer año." },
  { pregunta: "¿Qué ocurre si un trabajador está en desempleo contributivo?", respuesta: "Se considera situación asimilada al alta y cotiza por contingencias comunes." },
  { pregunta: "¿Qué ocurre si un trabajador está en desempleo asistencial?", respuesta: "No cotiza, pero se considera asimilado al alta a efectos de prestaciones." },
  { pregunta: "¿Qué ocurre si un trabajador está en IT tras extinguirse su contrato?", respuesta: "Se considera situación asimilada al alta hasta el alta médica." },
  { pregunta: "¿Qué ocurre si un trabajador está en huelga legal?", respuesta: "Se considera situación asimilada al alta sin obligación de cotizar." },
  { pregunta: "¿Qué ocurre si un trabajador está en cierre patronal?", respuesta: "Se considera situación asimilada al alta sin obligación de cotizar." },
  { pregunta: "¿Qué ocurre si un trabajador está en prisión preventiva?", respuesta: "Se considera situación asimilada al alta si posteriormente es absuelto." },
  { pregunta: "¿Qué ocurre si un trabajador está en prisión cumpliendo condena?", respuesta: "No se considera situación asimilada al alta salvo programas específicos." },
  { pregunta: "¿Qué ocurre si un trabajador está en convenio especial?", respuesta: "Mantiene cotización voluntaria para prestaciones futuras." },
  { pregunta: "¿Qué ocurre si un trabajador deja de pagar el convenio especial?", respuesta: "Se extingue el convenio y se pierde la cobertura." },
  { pregunta: "¿Qué ocurre si un trabajador solicita el convenio especial fuera de plazo?", respuesta: "Debe iniciar un nuevo procedimiento si cumple requisitos." },
  { pregunta: "¿Qué ocurre si un trabajador quiere ampliar la base del convenio especial?", respuesta: "Debe solicitarlo antes del 1 de octubre para efectos el 1 de enero siguiente." },
  { pregunta: "¿Qué ocurre si un trabajador quiere reducir la base del convenio especial?", respuesta: "Puede solicitarlo en cualquier momento con efectos desde el mes siguiente." },
  { pregunta: "¿Qué ocurre si un trabajador se jubila estando en convenio especial?", respuesta: "El convenio se extingue automáticamente." },
  { pregunta: "¿Qué ocurre si un trabajador fallece estando en convenio especial?", respuesta: "El convenio se extingue y no genera devolución de cuotas." },
  { pregunta: "¿Qué ocurre si un trabajador en convenio especial inicia actividad laboral?", respuesta: "El convenio queda suspendido mientras dure la actividad." },
  { pregunta: "¿Qué ocurre si un trabajador en convenio especial inicia actividad a tiempo parcial?", respuesta: "El convenio puede mantenerse complementando bases." },
  { pregunta: "¿Qué ocurre si un trabajador en convenio especial entra en situación de IT?", respuesta: "No genera prestación; el convenio solo cubre jubilación y muerte/supervivencia." },
  { pregunta: "¿Qué ocurre si un trabajador en convenio especial entra en situación de maternidad o paternidad?", respuesta: "No genera prestación; el convenio no cubre estas contingencias." },
  { pregunta: "¿Qué ocurre si un trabajador en convenio especial quiere incluir contingencias profesionales?", respuesta: "No es posible; el convenio solo cubre contingencias comunes." },
    { pregunta: "¿Qué ocurre si la TGSS detecta que un trabajador está prestando servicios sin alta?", respuesta: "Puede practicar un alta de oficio con efectos retroactivos desde la fecha en que se conozcan los hechos." },
  { pregunta: "¿Qué ocurre si la Inspección de Trabajo detecta que un trabajador está sin alta?", respuesta: "El alta de oficio surte efectos desde la fecha de la actuación inspectora." },
  { pregunta: "¿Qué ocurre si la TGSS detecta un alta indebida en un régimen que no corresponde?", respuesta: "El alta es válida hasta la resolución que declare el error y se regulariza el encuadramiento." },
  { pregunta: "¿Qué ocurre si la TGSS detecta una afiliación indebida?", respuesta: "Se anula y se repone al trabajador a la situación anterior, devolviendo cuotas salvo malicia." },
  { pregunta: "¿Qué ocurre si la TGSS detecta una inscripción indebida de empresa?", respuesta: "Se anula y se regulariza desde la fecha de la resolución administrativa." },
  { pregunta: "¿Qué ocurre si una empresa inicia actividad sin inscribirse?", respuesta: "La TGSS puede inscribirla de oficio y reclamar cuotas desde el inicio real de la actividad." },
  { pregunta: "¿Qué ocurre si una empresa no comunica el cese de actividad?", respuesta: "La obligación de cotizar continúa hasta que la TGSS tenga conocimiento del cese." },
  { pregunta: "¿Qué ocurre si una empresa comunica el cese fuera de plazo?", respuesta: "La obligación de cotizar continúa hasta la fecha en que la TGSS conozca el cese." },
  { pregunta: "¿Qué ocurre si una empresa cambia de actividad económica?", respuesta: "Debe comunicarlo en 3 días naturales como variación de datos." },
  { pregunta: "¿Qué ocurre si una empresa abre un centro en otra provincia?", respuesta: "Debe solicitar un nuevo CCC para esa provincia." },
  { pregunta: "¿Qué ocurre si una empresa cambia de mutua colaboradora?", respuesta: "Debe comunicarlo con 10 días naturales de antelación a su efectividad." },
  { pregunta: "¿Qué ocurre si una empresa no formaliza la cobertura de contingencias profesionales?", respuesta: "La TGSS puede asignar de oficio la entidad gestora correspondiente." },
  { pregunta: "¿Qué ocurre si una empresa elige mutua para contingencias comunes?", respuesta: "La mutua formaliza la cobertura en 15 días y tiene vigencia anual prorrogable." },
  { pregunta: "¿Qué ocurre si una empresa quiere cambiar de mutua antes de un año?", respuesta: "No puede; la vigencia mínima es de un año salvo cese de actividad." },
  { pregunta: "¿Qué ocurre si un autónomo quiere cambiar de mutua?", respuesta: "Debe denunciar el acuerdo antes del 1 de octubre para efectos el 1 de enero siguiente." },
  { pregunta: "¿Qué ocurre si un autónomo inicia actividad en un establecimiento físico?", respuesta: "Debe solicitar el alta en la DPTGSS donde radique el establecimiento." },
  { pregunta: "¿Qué ocurre si un autónomo inicia actividad sin comunicar el alta?", respuesta: "La TGSS puede practicar alta de oficio desde el inicio real de la actividad." },
  { pregunta: "¿Qué ocurre si un autónomo comunica una variación de datos fuera de plazo?", respuesta: "La TGSS puede imponer sanciones y regularizar cotizaciones." },
  { pregunta: "¿Qué ocurre si un autónomo solicita la baja fuera de plazo?", respuesta: "La obligación de cotizar continúa hasta la comunicación efectiva." },
  { pregunta: "¿Qué ocurre si un autónomo solicita el alta con 60 días de anticipación?", respuesta: "No es posible; en el RETA no existe alta anticipada de 60 días." },
  { pregunta: "¿Qué ocurre si un trabajador está en vacaciones retribuidas no disfrutadas al finalizar el contrato?", respuesta: "Se considera situación asimilada al alta durante ese periodo." },
  { pregunta: "¿Qué ocurre si un trabajador está en desempleo contributivo?", respuesta: "Se considera situación asimilada al alta y cotiza por contingencias comunes." },
  { pregunta: "¿Qué ocurre si un trabajador está en desempleo asistencial?", respuesta: "Se considera asimilado al alta pero no cotiza." },
  { pregunta: "¿Qué ocurre si un trabajador está en excedencia forzosa?", respuesta: "Se considera situación asimilada al alta." },
  { pregunta: "¿Qué ocurre si un trabajador está en excedencia por cuidado de hijos?", respuesta: "Se considera asimilado al alta con reserva de puesto de trabajo." },
  { pregunta: "¿Qué ocurre si un trabajador está en excedencia por cuidado de familiares?", respuesta: "Se considera asimilado al alta durante el primer año." },
  { pregunta: "¿Qué ocurre si un trabajador está en servicio militar o prestación social sustitutoria?", respuesta: "Se considera situación asimilada al alta." },
  { pregunta: "¿Qué ocurre si un trabajador está desplazado al extranjero por la empresa?", respuesta: "Se considera situación asimilada al alta." },
  { pregunta: "¿Qué ocurre si un trabajador está en prisión preventiva y luego es absuelto?", respuesta: "Se considera situación asimilada al alta." },
  { pregunta: "¿Qué ocurre si un trabajador está en prisión cumpliendo condena?", respuesta: "No se considera asimilado al alta salvo programas específicos." },
  { pregunta: "¿Qué ocurre si un trabajador está en huelga legal?", respuesta: "Se considera situación asimilada al alta sin obligación de cotizar." },
  { pregunta: "¿Qué ocurre si un trabajador está en cierre patronal?", respuesta: "Se considera situación asimilada al alta sin obligación de cotizar." },
  { pregunta: "¿Qué ocurre si un trabajador está en IT tras extinguirse su contrato?", respuesta: "Se considera asimilado al alta hasta el alta médica." },
  { pregunta: "¿Qué ocurre si un trabajador está en periodo de inactividad entre trabajos de temporada?", respuesta: "Se considera situación asimilada al alta." },
  { pregunta: "¿Qué ocurre si un trabajador está en convenio especial?", respuesta: "Se considera situación asimilada al alta a efectos de prestaciones cubiertas." },
  { pregunta: "¿Qué ocurre si un trabajador deja de pagar el convenio especial durante 3 meses seguidos?", respuesta: "El convenio se extingue automáticamente." },
  { pregunta: "¿Qué ocurre si un trabajador deja de pagar el convenio especial 5 meses alternos?", respuesta: "El convenio se extingue automáticamente." },
  { pregunta: "¿Qué ocurre si un trabajador en convenio especial inicia actividad con base inferior?", respuesta: "El convenio se suspende salvo que opte por mantenerlo." },
  { pregunta: "¿Qué ocurre si un trabajador en convenio especial inicia actividad con base igual o superior?", respuesta: "El convenio se extingue." },
  { pregunta: "¿Qué ocurre si un trabajador solicita el convenio especial dentro de los 90 días del cese?", respuesta: "Puede elegir efectos desde el día siguiente al cese o desde la solicitud." },
  { pregunta: "¿Qué ocurre si un trabajador solicita el convenio especial fuera de los 90 días pero dentro del año?", respuesta: "Los efectos son desde la fecha de la solicitud." },
  { pregunta: "¿Qué ocurre si la TGSS no resuelve el convenio especial en 3 meses?", respuesta: "Se entiende estimado por silencio positivo." },
  { pregunta: "¿Qué ocurre si un trabajador quiere aumentar la base del convenio especial?", respuesta: "Debe solicitarlo antes del 1 de octubre para efectos el 1 de enero siguiente." },
  { pregunta: "¿Qué ocurre si un trabajador quiere reducir la base del convenio especial?", respuesta: "Puede solicitarlo en cualquier momento con efectos desde el mes siguiente." },
  { pregunta: "¿Qué ocurre si un trabajador obtiene pensión de jubilación estando en convenio especial?", respuesta: "El convenio se extingue automáticamente." },
  { pregunta: "¿Qué ocurre si un trabajador fallece estando en convenio especial?", respuesta: "El convenio se extingue sin devolución de cuotas." },
  { pregunta: "¿Qué ocurre si un trabajador en convenio especial entra en situación de IT?", respuesta: "No genera prestación; el convenio no cubre IT." },
  { pregunta: "¿Qué ocurre si un trabajador en convenio especial entra en maternidad o paternidad?", respuesta: "No genera prestación; el convenio no cubre estas contingencias." },
  { pregunta: "¿Qué ocurre si un trabajador en convenio especial quiere incluir contingencias profesionales?", respuesta: "No es posible; el convenio solo cubre contingencias comunes." },
    { pregunta: "¿Qué ocurre si un trabajador está en situación de alta presunta?", respuesta: "Se considera en alta a todos los efectos mientras se determina la situación real." },
  { pregunta: "¿Qué ocurre si un trabajador sufre un accidente antes de que la empresa comunique el alta?", respuesta: "Se considera en alta de pleno derecho a efectos de prestaciones." },
  { pregunta: "¿Qué ocurre si la empresa comunica un alta con fecha posterior al inicio real?", respuesta: "La TGSS puede retrotraer el alta a la fecha real y reclamar cuotas." },
  { pregunta: "¿Qué ocurre si la empresa comunica un alta con fecha futura?", respuesta: "El alta futura es válida siempre que no supere los 60 días de anticipación." },
  { pregunta: "¿Qué ocurre si un trabajador presta servicios en dos empresas del mismo régimen?", respuesta: "Está en pluriempleo y debe tener un único número de afiliación." },
  { pregunta: "¿Qué ocurre si un trabajador presta servicios en dos regímenes distintos?", respuesta: "Está en pluriactividad y cotiza en ambos regímenes." },
  { pregunta: "¿Qué ocurre si un trabajador autónomo trabaja simultáneamente por cuenta ajena?", respuesta: "Está en pluriactividad y cotiza en ambos sistemas." },
  { pregunta: "¿Qué ocurre si un trabajador autónomo solicita devolución por exceso de cotización en pluriactividad?", respuesta: "La TGSS devuelve el exceso automáticamente al finalizar el ejercicio." },
  { pregunta: "¿Qué ocurre si un trabajador autónomo societario no comunica su alta?", respuesta: "La TGSS puede practicar alta de oficio y reclamar cuotas desde el inicio real." },
  { pregunta: "¿Qué ocurre si un autónomo societario cesa en la sociedad?", respuesta: "Debe comunicar la baja en 3 días naturales." },
  { pregunta: "¿Qué ocurre si un autónomo societario mantiene participación pero deja de trabajar?", respuesta: "Debe analizarse si procede baja en RETA o mantenimiento por control efectivo." },
  { pregunta: "¿Qué ocurre si un administrador de sociedad limitada no tiene control efectivo?", respuesta: "Puede estar encuadrado en Régimen General asimilado." },
  { pregunta: "¿Qué ocurre si un administrador tiene control efectivo?", respuesta: "Debe encuadrarse en RETA." },
  { pregunta: "¿Qué ocurre si un socio trabajador tiene más del 33% del capital y trabaja en la empresa?", respuesta: "Debe encuadrarse en RETA." },
  { pregunta: "¿Qué ocurre si un socio trabajador tiene menos del 33% y no es administrador?", respuesta: "Puede encuadrarse en Régimen General." },
  { pregunta: "¿Qué ocurre si un socio trabajador tiene entre el 25% y el 33% y es administrador?", respuesta: "Debe encuadrarse en RETA." },
  { pregunta: "¿Qué ocurre si un socio trabajador tiene menos del 25% y es administrador?", respuesta: "Puede encuadrarse en Régimen General asimilado." },
  { pregunta: "¿Qué ocurre si un trabajador autónomo colabora en el negocio familiar?", respuesta: "Debe encuadrarse como autónomo colaborador." },
  { pregunta: "¿Qué ocurre si un autónomo colaborador deja de trabajar?", respuesta: "Debe comunicarse la baja en 3 días naturales." },
  { pregunta: "¿Qué ocurre si un autónomo colaborador quiere cotizar por contingencias profesionales?", respuesta: "Debe hacerlo obligatoriamente desde 2019." },
  { pregunta: "¿Qué ocurre si un trabajador autónomo no elige mutua?", respuesta: "La TGSS asigna de oficio una mutua colaboradora." },
  { pregunta: "¿Qué ocurre si un autónomo quiere cambiar su base de cotización?", respuesta: "Puede hacerlo hasta 4 veces al año según los trimestres naturales." },
  { pregunta: "¿Qué ocurre si un autónomo quiere cambiar su base fuera de plazo trimestral?", respuesta: "Debe esperar al siguiente periodo habilitado." },
  { pregunta: "¿Qué ocurre si un autónomo está en tarifa plana y cesa?", respuesta: "Pierde el beneficio salvo reincorporación dentro del plazo legal." },
  { pregunta: "¿Qué ocurre si un autónomo reanuda actividad tras cese?", respuesta: "Debe comunicar un nuevo alta en RETA." },
  { pregunta: "¿Qué ocurre si un autónomo reanuda actividad dentro de los 3 años posteriores?", respuesta: "No puede volver a disfrutar de tarifa plana." },
  { pregunta: "¿Qué ocurre si un autónomo reanuda actividad tras más de 3 años?", respuesta: "Puede volver a disfrutar de tarifa plana si cumple requisitos." },
  { pregunta: "¿Qué ocurre si un trabajador está en situación de alta especial por huelga?", respuesta: "Se considera asimilado al alta sin obligación de cotizar." },
  { pregunta: "¿Qué ocurre si un trabajador está en cierre patronal?", respuesta: "Se considera asimilado al alta sin obligación de cotizar." },
  { pregunta: "¿Qué ocurre si un trabajador está en IT tras finalizar contrato?", respuesta: "Se considera asimilado al alta hasta el alta médica." },
  { pregunta: "¿Qué ocurre si un trabajador está en vacaciones retribuidas no disfrutadas tras el cese?", respuesta: "Se considera asimilado al alta durante ese periodo." },
  { pregunta: "¿Qué ocurre si un trabajador está en desempleo contributivo?", respuesta: "Se considera asimilado al alta y cotiza por contingencias comunes." },
  { pregunta: "¿Qué ocurre si un trabajador está en desempleo asistencial?", respuesta: "Se considera asimilado al alta pero no cotiza." },
  { pregunta: "¿Qué ocurre si un trabajador está en excedencia por cuidado de hijos?", respuesta: "Se considera asimilado al alta con reserva de puesto." },
  { pregunta: "¿Qué ocurre si un trabajador está en excedencia por cuidado de familiares?", respuesta: "Se considera asimilado al alta durante el primer año." },
  { pregunta: "¿Qué ocurre si un trabajador está en excedencia voluntaria?", respuesta: "No se considera asimilado al alta." },
  { pregunta: "¿Qué ocurre si un trabajador está en servicio militar o prestación social sustitutoria?", respuesta: "Se considera asimilado al alta." },
  { pregunta: "¿Qué ocurre si un trabajador está desplazado temporalmente al extranjero?", respuesta: "Se considera asimilado al alta mediante formulario de desplazamiento." },
  { pregunta: "¿Qué ocurre si un trabajador está desplazado dentro de la UE?", respuesta: "Se aplica el Reglamento 883/2004 y el formulario A1." },
  { pregunta: "¿Qué ocurre si un trabajador está desplazado a país con convenio bilateral?", respuesta: "Se aplica la legislación del país de origen durante el periodo autorizado." },
  { pregunta: "¿Qué ocurre si un trabajador está desplazado a país sin convenio?", respuesta: "Debe suscribir un convenio especial para mantener cotizaciones." },
  { pregunta: "¿Qué ocurre si un trabajador pierde la condición de asimilado al alta?", respuesta: "Debe suscribir un convenio especial si quiere mantener cotización." },
  { pregunta: "¿Qué ocurre si un trabajador solicita convenio especial tras más de un año del cese?", respuesta: "No puede; el plazo máximo es 1 año." },
  { pregunta: "¿Qué ocurre si un trabajador solicita convenio especial dentro de los 90 días del cese?", respuesta: "Puede elegir efectos desde el día siguiente al cese o desde la solicitud." },
  { pregunta: "¿Qué ocurre si un trabajador solicita convenio especial fuera de los 90 días pero dentro del año?", respuesta: "Los efectos son desde la fecha de la solicitud." },
  { pregunta: "¿Qué ocurre si la TGSS no resuelve el convenio especial en 3 meses?", respuesta: "Se entiende estimado por silencio positivo." },
  { pregunta: "¿Qué ocurre si un trabajador deja de pagar el convenio especial 3 meses seguidos?", respuesta: "El convenio se extingue automáticamente." },
  { pregunta: "¿Qué ocurre si un trabajador deja de pagar el convenio especial 5 meses alternos?", respuesta: "El convenio se extingue automáticamente." },
  { pregunta: "¿Qué ocurre si un trabajador en convenio especial inicia actividad laboral?", respuesta: "El convenio queda suspendido mientras dure la actividad." },
  { pregunta: "¿Qué ocurre si un trabajador en convenio especial inicia actividad con base igual o superior?", respuesta: "El convenio se extingue." },
    { pregunta: "¿Qué ocurre si un trabajador está en situación de alta presunta y sufre un accidente laboral?", respuesta: "Se considera en alta de pleno derecho a efectos de prestaciones." },
  { pregunta: "¿Qué ocurre si un trabajador está en alta presunta y la empresa niega la relación laboral?", respuesta: "La TGSS mantiene el alta presunta hasta que se determine la situación real." },
  { pregunta: "¿Qué ocurre si un trabajador está en alta especial por huelga y sufre un accidente?", respuesta: "No genera prestación económica, pero mantiene la condición de asimilado al alta." },
  { pregunta: "¿Qué ocurre si un trabajador está en cierre patronal y sufre un accidente?", respuesta: "No genera prestación económica, pero mantiene la condición de asimilado al alta." },
  { pregunta: "¿Qué ocurre si un trabajador está en IT y la empresa comunica una baja indebida?", respuesta: "La TGSS anula la baja y mantiene la obligación de cotizar." },
  { pregunta: "¿Qué ocurre si un trabajador está en IT y finaliza su contrato?", respuesta: "Se considera asimilado al alta hasta el alta médica." },
  { pregunta: "¿Qué ocurre si un trabajador está en IT y pasa a situación de desempleo?", respuesta: "Continúa en IT cobrando la prestación correspondiente." },
  { pregunta: "¿Qué ocurre si un trabajador está en IT y la empresa cierra?", respuesta: "Se mantiene la situación de asimilado al alta." },
  { pregunta: "¿Qué ocurre si un trabajador está en maternidad o paternidad y finaliza su contrato?", respuesta: "Se mantiene la prestación hasta su finalización." },
  { pregunta: "¿Qué ocurre si un trabajador está en maternidad o paternidad y la empresa comunica una baja indebida?", respuesta: "La TGSS anula la baja y mantiene la obligación de cotizar." },
  { pregunta: "¿Qué ocurre si un trabajador está en riesgo durante el embarazo y finaliza su contrato?", respuesta: "Pasa a situación de asimilado al alta y mantiene la prestación." },
  { pregunta: "¿Qué ocurre si un trabajador está en riesgo durante la lactancia y finaliza su contrato?", respuesta: "Pasa a situación de asimilado al alta y mantiene la prestación." },
  { pregunta: "¿Qué ocurre si un trabajador está en excedencia voluntaria y quiere suscribir un convenio especial?", respuesta: "No puede; la excedencia voluntaria no es situación asimilada al alta." },
  { pregunta: "¿Qué ocurre si un trabajador está en excedencia por cuidado de hijos y quiere suscribir un convenio especial?", respuesta: "Puede hacerlo para complementar cotizaciones." },
  { pregunta: "¿Qué ocurre si un trabajador está en excedencia por cuidado de familiares y quiere suscribir un convenio especial?", respuesta: "Puede hacerlo tras el primer año, que es asimilado al alta." },
  { pregunta: "¿Qué ocurre si un trabajador está en desempleo contributivo y quiere suscribir un convenio especial?", respuesta: "No es necesario; ya cotiza por contingencias comunes." },
  { pregunta: "¿Qué ocurre si un trabajador está en desempleo asistencial y quiere suscribir un convenio especial?", respuesta: "Puede hacerlo para mantener cotizaciones." },
  { pregunta: "¿Qué ocurre si un trabajador está en prisión preventiva y quiere suscribir un convenio especial?", respuesta: "Puede hacerlo si posteriormente es absuelto." },
  { pregunta: "¿Qué ocurre si un trabajador está en prisión cumpliendo condena y quiere suscribir un convenio especial?", respuesta: "No puede salvo programas específicos de reinserción." },
  { pregunta: "¿Qué ocurre si un trabajador está en situación de convenio especial y quiere incluir lagunas de cotización?", respuesta: "El convenio especial ya cubre lagunas para jubilación." },
  { pregunta: "¿Qué ocurre si un trabajador quiere suscribir un convenio especial por cese involuntario?", respuesta: "Debe solicitarlo dentro del año siguiente al cese." },
  { pregunta: "¿Qué ocurre si un trabajador quiere suscribir un convenio especial por reducción de jornada?", respuesta: "Puede hacerlo para mantener la base previa." },
  { pregunta: "¿Qué ocurre si un trabajador quiere suscribir un convenio especial por ERE?", respuesta: "Puede suscribirlo si cumple los requisitos del acuerdo colectivo." },
  { pregunta: "¿Qué ocurre si un trabajador quiere suscribir un convenio especial por jubilación anticipada?", respuesta: "Puede hacerlo para completar cotizaciones previas a la jubilación." },
  { pregunta: "¿Qué ocurre si un trabajador quiere suscribir un convenio especial por cuidado de hijos?", respuesta: "No es necesario; la excedencia ya es asimilada al alta." },
  { pregunta: "¿Qué ocurre si un trabajador quiere suscribir un convenio especial por cuidado de familiares?", respuesta: "Puede hacerlo tras el primer año de excedencia." },
  { pregunta: "¿Qué ocurre si un trabajador quiere suscribir un convenio especial por traslado al extranjero?", respuesta: "Puede hacerlo para mantener cotizaciones en España." },
  { pregunta: "¿Qué ocurre si un trabajador quiere suscribir un convenio especial por pluriactividad?", respuesta: "No procede; ya cotiza en ambos regímenes." },
  { pregunta: "¿Qué ocurre si un trabajador quiere suscribir un convenio especial por pluriempleo?", respuesta: "No procede; ya cotiza en el mismo régimen por varias empresas." },
  { pregunta: "¿Qué ocurre si un trabajador quiere suscribir un convenio especial por reducción de base en autónomos?", respuesta: "Puede hacerlo para mantener la base previa." },
  { pregunta: "¿Qué ocurre si un trabajador quiere suscribir un convenio especial por cese voluntario?", respuesta: "Puede hacerlo dentro del año siguiente al cese." },
  { pregunta: "¿Qué ocurre si un trabajador quiere suscribir un convenio especial por despido disciplinario?", respuesta: "Puede hacerlo dentro del año siguiente al cese." },
  { pregunta: "¿Qué ocurre si un trabajador quiere suscribir un convenio especial por despido improcedente?", respuesta: "Puede hacerlo dentro del año siguiente al cese." },
  { pregunta: "¿Qué ocurre si un trabajador quiere suscribir un convenio especial por despido colectivo?", respuesta: "Puede hacerlo si cumple los requisitos del acuerdo colectivo." },
  { pregunta: "¿Qué ocurre si un trabajador quiere suscribir un convenio especial por jubilación parcial?", respuesta: "Puede hacerlo para mantener la base previa." },
  { pregunta: "¿Qué ocurre si un trabajador quiere suscribir un convenio especial por jubilación flexible?", respuesta: "Puede hacerlo para complementar cotizaciones." },
  { pregunta: "¿Qué ocurre si un trabajador quiere suscribir un convenio especial por jubilación activa?", respuesta: "No procede; ya está en situación de pensionista." },
  { pregunta: "¿Qué ocurre si un trabajador quiere suscribir un convenio especial por incapacidad permanente?", respuesta: "No procede; ya es pensionista." },
  { pregunta: "¿Qué ocurre si un trabajador quiere suscribir un convenio especial por muerte y supervivencia?", respuesta: "No procede; el convenio no cubre estas contingencias." },
  { pregunta: "¿Qué ocurre si un trabajador quiere suscribir un convenio especial por accidente laboral?", respuesta: "No procede; el convenio solo cubre contingencias comunes." },
  { pregunta: "¿Qué ocurre si un trabajador quiere suscribir un convenio especial por enfermedad profesional?", respuesta: "No procede; el convenio solo cubre contingencias comunes." },
  { pregunta: "¿Qué ocurre si un trabajador quiere suscribir un convenio especial por maternidad o paternidad?", respuesta: "No procede; el convenio no cubre estas contingencias." },
  { pregunta: "¿Qué ocurre si un trabajador quiere suscribir un convenio especial por riesgo durante el embarazo?", respuesta: "No procede; el convenio no cubre estas contingencias." },
  { pregunta: "¿Qué ocurre si un trabajador quiere suscribir un convenio especial por riesgo durante la lactancia?", respuesta: "No procede; el convenio no cubre estas contingencias." },
  { pregunta: "¿Qué ocurre si un trabajador quiere suscribir un convenio especial por cuidado de menores con enfermedad grave?", respuesta: "No procede; esta situación no afecta al alta." },
  { pregunta: "¿Qué ocurre si un trabajador quiere suscribir un convenio especial por reducción de jornada por guarda legal?", respuesta: "Puede hacerlo para mantener la base previa." },
  { pregunta: "¿Qué ocurre si un trabajador quiere suscribir un convenio especial por reducción de jornada por cuidado de familiar?", respuesta: "Puede hacerlo para mantener la base previa." },
  { pregunta: "¿Qué ocurre si un trabajador quiere suscribir un convenio especial por reducción de jornada por violencia de género?", respuesta: "Puede hacerlo para mantener la base previa." },
  { pregunta: "¿Qué ocurre si un trabajador quiere suscribir un convenio especial por reducción de jornada por violencia terrorista?", respuesta: "Puede hacerlo para mantener la base previa." },
  { pregunta: "¿Qué ocurre si un trabajador quiere suscribir un convenio especial por reducción de jornada por enfermedad grave del menor?", respuesta: "Puede hacerlo para mantener la base previa." }
];