const preguntas = [
  {
    pregunta: "¿Cuál es la duración general del subsidio por nacimiento y cuidado de menor para cada uno de los progenitores?",
    respuesta: "Tiene una duración de 16 semanas, de las cuales las 6 semanas inmediatas posteriores al parto (o resolución judicial en adopción) son obligatorias, ininterrumpidas y a jornada completa."
  },
  {
    pregunta: "¿Qué periodos de cotización previa se exigen para la prestación contributiva por nacimiento según la edad del trabajador?",
    respuesta: "Menores de 21 años: no se exige carencia. Entre 21 y 26 años: 90 días en los 7 años anteriores o 180 días en toda su vida laboral. Mayores de 26 años: 180 días en los 7 años anteriores o 360 días en total."
  },
  {
    pregunta: "En caso de parto múltiple, adopción o acogimiento múltiple, ¿cuánto se amplía la prestación por nacimiento?",
    respuesta: "Se amplía en 2 semanas para cada progenitor por cada hijo/a a partir del segundo (1 semana obligatoria y 1 voluntaria para cada uno)."
  },
  {
    pregunta: "¿En qué supuestos familiares y con qué duración se amplía el subsidio no contributivo por nacimiento de la madre biológica?",
    respuesta: "La duración general es de 42 días naturales (cuantía 100% IPREM). Se amplía en 14 días más en casos de nacimiento en familia numerosa, monoparental o si la madre o el menor presentan una discapacidad ≥ 65%."
  },
  {
    pregunta: "¿Cuál es la cuantía económica y la base de referencia para el cálculo de la prestación por nacimiento en el Régimen General?",
    respuesta: "Es un subsidio equivalente al 100% de la base reguladora, la cual coincide con la base de cotización por contingencias comunes del mes anterior al del inicio del descanso."
  },
  {
    pregunta: "¿Qué requisitos concurrentes se exigen para causar el derecho al subsidio por ejercicio corresponsable del cuidado del lactante?",
    respuesta: "Que ambos progenitores trabajen y reduzcan su jornada ordinaria en media hora. La prestación compensa la pérdida salarial desde que el menor cumple 9 meses hasta que alcanza los 12 meses de edad."
  },
  {
    pregunta: "¿Cuál es la base de cotización de referencia para el cálculo del subsidio por riesgo durante el embarazo o lactancia natural?",
    respuesta: "Al ser contingencias profesionales puras, equivale al 100% de la base reguladora de contingencias profesionales (tomando la base de AT/EP del mes anterior, descontando horas extras)."
  },
  {
    pregunta: "¿Qué periodo de cotización previa o carencia exige la ley para causar las prestaciones por riesgo durante el embarazo o lactancia?",
    respuesta: "No se exige ningún periodo previo de cotización (carencia cero) por estar asimiladas conceptualmente a contingencias profesionales y de salud laboral."
  },
  {
    pregunta: "¿En qué momento exacto se extingue el subsidio por riesgo durante la lactancia natural?",
    respuesta: "Se extingue obligatoriamente el día en que el hijo o menor lactante cumple los 9 meses de edad, o antes si la trabajadora se reincorpora a su puesto o a otro compatible."
  },
  {
    pregunta: "¿Qué porcentaje mínimo de reducción de jornada se exige para acceder al subsidio por cuidado de menores afectados por cáncer u otra enfermedad grave (CUME)?",
    respuesta: "Se exige una reducción de la jornada de trabajo de al menos el 50% para el cuidado directo, continuo y permanente del menor."
  },
  {
    pregunta: "¿Hasta qué edad máxima se puede percibir el subsidio por CUME según las últimas reformas (RDL 9/2025 y concordantes)?",
    respuesta: "Con carácter general hasta los 23 años. Se prorroga excepcionalmente hasta los 26 años si el hijo/a mantiene un grado de discapacidad igual o superior al 65%."
  },
  {
    pregunta: "¿Qué consideración tienen los periodos de excedencia por cuidado de hijo a efectos de las prestaciones de la Seguridad Social?",
    respuesta: "Los 3 primeros años de excedencia tienen la consideración de periodo de cotización efectiva para jubilación, incapacidad permanente, muerte y supervivencia, nacimiento y cuidado de menor."
  },
  {
    pregunta: "Si un autónomo (RETA) cesa temporalmente por nacimiento, ¿qué beneficio se le reconoce sobre su obligación pautada de cotizar?",
    respuesta: "Disfruta de una bonificación del 100% de la cuota de autónomos (cuota cero) durante todo el periodo de descanso, calculada sobre la base media de los 12 meses anteriores."
  },
  { pregunta: "¿Qué prestación sustituye al antiguo permiso de maternidad y paternidad?", respuesta: "La prestación por nacimiento y cuidado del menor." },
{ pregunta: "¿Qué organismo gestiona la prestación por nacimiento y cuidado del menor?", respuesta: "El Instituto Nacional de la Seguridad Social (INSS)." },
{ pregunta: "¿Qué duración tiene el descanso por nacimiento y cuidado del menor?", respuesta: "16 semanas." },
{ pregunta: "¿Cuántas semanas son obligatorias tras el parto para cada progenitor?", respuesta: "6 semanas ininterrumpidas." },
{ pregunta: "¿Cuántas semanas pueden disfrutarse de forma flexible?", respuesta: "10 semanas, hasta que el menor cumpla 12 meses." },
{ pregunta: "¿Qué ampliación se aplica en caso de parto múltiple?", respuesta: "+1 semana por cada hijo a partir del segundo para cada progenitor." },
{ pregunta: "¿Qué ampliación se aplica en caso de discapacidad del hijo?", respuesta: "+2 semanas, una para cada progenitor." },
{ pregunta: "¿Qué ampliación se aplica en caso de hospitalización del neonato?", respuesta: "Hasta 13 semanas adicionales si la hospitalización supera 7 días." },
{ pregunta: "¿Qué ocurre si el hijo fallece durante el permiso?", respuesta: "La duración no se reduce salvo que el trabajador solicite reincorporarse tras las 6 semanas obligatorias." },
{ pregunta: "¿Qué ocurre si ambos progenitores trabajan en la misma empresa y solicitan simultáneamente tramos flexibles?", respuesta: "La empresa puede limitarlo por razones fundadas y objetivas, motivándolo por escrito." },

{ pregunta: "¿Qué requisito de cotización se exige para mayores de 26 años?", respuesta: "180 días en los 7 años anteriores o 360 días en toda la vida laboral." },
{ pregunta: "¿Qué requisito de cotización se exige para menores de 26 años?", respuesta: "90 días en los 7 años anteriores o 180 días en toda la vida laboral." },
{ pregunta: "¿Qué requisito se exige para menores de 21 años?", respuesta: "Ninguno." },
{ pregunta: "¿Qué base reguladora se usa para calcular la prestación?", respuesta: "La base reguladora de IT por contingencias comunes." },
{ pregunta: "¿Qué porcentaje se aplica sobre la base reguladora?", respuesta: "El 100%." },
{ pregunta: "¿Qué ocurre si el trabajador ingresó en la empresa el mismo mes del hecho causante?", respuesta: "La BR se calcula con la base de cotización de ese mismo mes." },
{ pregunta: "¿Qué puede hacer el INSS si no dispone de la base correcta para calcular la BR?", respuesta: "Reconocer provisionalmente la prestación y recalcularla en 3 meses." },
{ pregunta: "¿Qué regla rige la edad para exigir periodo mínimo de cotización?", respuesta: "La edad se toma en el inicio del descanso, pero el PMC se exige en la fecha del parto." },
{ pregunta: "¿Qué ocurre si el trabajador está en situación de IT al inicio del descanso?", respuesta: "Se suspende la IT y comienza la prestación por nacimiento y cuidado del menor." },
{ pregunta: "¿Qué ocurre si el trabajador está en desempleo contributivo?", respuesta: "Se suspende el desempleo y se percibe la prestación por nacimiento y cuidado del menor." },

{ pregunta: "¿Qué organismo paga la prestación por nacimiento y cuidado del menor?", respuesta: "El INSS o el ISM, según el régimen." },
{ pregunta: "¿Qué ocurre si el trabajador no cumple los requisitos de cotización?", respuesta: "Puede acceder al subsidio especial no contributivo." },
{ pregunta: "¿Cuál es la cuantía del subsidio especial no contributivo?", respuesta: "100% del IPREM o la BR si es inferior." },
{ pregunta: "¿Cuál es la duración base del subsidio especial no contributivo?", respuesta: "6 semanas (42 días), ininterrumpidas y a jornada completa." },
{ pregunta: "¿Qué ampliación tiene el subsidio especial por parto múltiple?", respuesta: "+14 días, ampliación única y no acumulable." },
{ pregunta: "¿Qué ampliación tiene el subsidio especial por discapacidad del menor o progenitor?", respuesta: "+14 días, ampliación única y no acumulable." },
{ pregunta: "¿Qué ampliación tiene el subsidio especial por familia monoparental?", respuesta: "+14 días, ampliación única y no acumulable." },
{ pregunta: "¿Qué regla define las ampliaciones del subsidio especial?", respuesta: "Son únicas y no acumulables, aunque concurran varias circunstancias." },
{ pregunta: "¿Qué organismo gestiona el subsidio especial no contributivo?", respuesta: "El INSS." },
{ pregunta: "¿Qué requisito personal se exige para el subsidio especial?", respuesta: "Estar en alta o asimilada al alta en el momento del hecho causante." },

{ pregunta: "¿Qué prestación protege la situación de riesgo durante el embarazo?", respuesta: "La prestación por riesgo durante el embarazo." },
{ pregunta: "¿Qué organismo gestiona la prestación por riesgo durante el embarazo?", respuesta: "La mutua colaboradora o el INSS." },
{ pregunta: "¿Qué requisito adicional deben cumplir las autónomas para riesgo durante el embarazo?", respuesta: "Estar al corriente de pago; cualquier deuda bloquea la prestación." },
{ pregunta: "¿Qué documento deben presentar las autónomas para riesgo durante el embarazo?", respuesta: "Una declaración de situación de actividad acreditando que no existe puesto compatible." },
{ pregunta: "¿Quién certifica el riesgo durante el embarazo en autónomas?", respuesta: "Los servicios médicos de la mutua o entidad gestora." },
{ pregunta: "¿Qué ocurre si una autónoma está en IT y solicita riesgo durante el embarazo?", respuesta: "No se reconoce el riesgo hasta que finalice la IT; nunca se solapan." },
{ pregunta: "¿Qué base reguladora se usa para riesgo durante el embarazo?", respuesta: "La BR de IT por contingencias profesionales." },
{ pregunta: "¿Qué porcentaje se aplica sobre la base reguladora en riesgo durante el embarazo?", respuesta: "El 100%." },
{ pregunta: "¿Qué causa extingue la prestación por riesgo durante el embarazo?", respuesta: "El parto o interrupción del embarazo." },
{ pregunta: "¿Qué ocurre si la trabajadora cambia a un puesto compatible?", respuesta: "Se extingue la prestación por riesgo durante el embarazo." },

{ pregunta: "¿Qué prestación protege la situación de riesgo durante la lactancia natural?", respuesta: "La prestación por riesgo durante la lactancia natural." },
{ pregunta: "¿Qué organismo gestiona la prestación por riesgo durante la lactancia?", respuesta: "La mutua colaboradora o el INSS." },
{ pregunta: "¿Qué base reguladora se usa para riesgo durante la lactancia?", respuesta: "La BR de IT por contingencias profesionales." },
{ pregunta: "¿Qué porcentaje se aplica sobre la base reguladora en riesgo durante la lactancia?", respuesta: "El 100%." },
{ pregunta: "¿Qué causa extingue la prestación por riesgo durante la lactancia cuando el hijo cumple 9 meses?", respuesta: "Extinción automática por edad del menor." },
{ pregunta: "¿Qué causa extingue la prestación por riesgo durante la lactancia si la madre interrumpe la lactancia natural?", respuesta: "Extinción inmediata de la prestación." },
{ pregunta: "¿Qué causa extingue la prestación por riesgo durante la lactancia si se reincorpora al puesto compatible?", respuesta: "Extinción por reincorporación." },
{ pregunta: "¿Qué causa extingue la prestación por riesgo durante la lactancia si se extingue el contrato?", respuesta: "Extinción por fin de la relación laboral." },
{ pregunta: "¿Qué causa extingue la prestación por riesgo durante la lactancia si fallece la beneficiaria?", respuesta: "Extinción automática." },
{ pregunta: "¿Qué ocurre si la trabajadora pasa de lactancia a IT?", respuesta: "Se extingue la prestación por lactancia y comienza la IT." },

{ pregunta: "¿Qué duración tiene el permiso parental del TREBEP?", respuesta: "8 semanas, continuas o discontinuas, por semanas completas." },
{ pregunta: "¿Hasta qué edad del menor puede usarse el permiso parental del TREBEP?", respuesta: "Hasta que el menor cumpla 8 años." },
{ pregunta: "¿Qué naturaleza tiene el permiso parental del TREBEP?", respuesta: "No retribuido." },
{ pregunta: "¿Puede la Administración aplazar el permiso parental del TREBEP?", respuesta: "Sí, si altera gravemente el funcionamiento del servicio, justificándolo por escrito."},
{ pregunta: "¿Qué derecho garantiza el TREBEP al finalizar el permiso parental?", respuesta: "Reincorporación en términos no menos favorables"},
{ pregunta: "¿Qué ocurre si el hijo fallece durante el permiso por nacimiento y cuidado del menor?", respuesta: "La duración no se reduce salvo que el trabajador solicite reincorporarse tras las 6 semanas obligatorias." },
{ pregunta: "¿Qué ampliación se aplica en caso de parto múltiple?", respuesta: "+1 semana por cada hijo a partir del segundo para cada progenitor." },
{ pregunta: "¿Qué ampliación se aplica en caso de discapacidad del hijo?", respuesta: "+2 semanas, una para cada progenitor." },
{ pregunta: "¿Qué ampliación se aplica en caso de hospitalización del neonato?", respuesta: "Hasta 13 semanas adicionales si la hospitalización supera 7 días." },
{ pregunta: "¿Qué ocurre si ambos progenitores trabajan en la misma empresa y solicitan simultáneamente tramos flexibles?", respuesta: "La empresa puede limitarlo por razones fundadas y objetivas, motivándolo por escrito." },
{ pregunta: "¿Qué ocurre si el trabajador ingresó en la empresa el mismo mes del hecho causante?", respuesta: "La base reguladora se calcula con la base de cotización de ese mismo mes." },
{ pregunta: "¿Qué puede hacer el INSS si no dispone de la base correcta para calcular la BR?", respuesta: "Reconocer provisionalmente la prestación y recalcularla en 3 meses." },
{ pregunta: "¿Qué regla rige la edad para exigir periodo mínimo de cotización?", respuesta: "La edad se toma en el inicio del descanso, pero el PMC se exige en la fecha del parto." },
{ pregunta: "¿Qué ocurre si el trabajador está en situación de IT al inicio del descanso?", respuesta: "Se suspende la IT y comienza la prestación por nacimiento y cuidado del menor." },
{ pregunta: "¿Qué ocurre si el trabajador está en desempleo contributivo?", respuesta: "Se suspende el desempleo y se percibe la prestación por nacimiento y cuidado del menor." },

{ pregunta: "¿Qué requisito adicional deben cumplir las autónomas para riesgo durante el embarazo?", respuesta: "Estar al corriente de pago; cualquier deuda bloquea la prestación." },
{ pregunta: "¿Qué documento deben presentar las autónomas para riesgo durante el embarazo?", respuesta: "Una declaración de situación de actividad acreditando que no existe puesto compatible." },
{ pregunta: "¿Quién certifica el riesgo durante el embarazo en autónomas?", respuesta: "Los servicios médicos de la mutua o entidad gestora." },
{ pregunta: "¿Qué ocurre si una autónoma está en IT y solicita riesgo durante el embarazo?", respuesta: "No se reconoce el riesgo hasta que finalice la IT; nunca se solapan." },
{ pregunta: "¿Qué base reguladora se usa para riesgo durante el embarazo?", respuesta: "La base reguladora de IT por contingencias profesionales." },
{ pregunta: "¿Qué porcentaje se aplica sobre la base reguladora en riesgo durante el embarazo?", respuesta: "El 100%." },
{ pregunta: "¿Qué causa extingue la prestación por riesgo durante el embarazo?", respuesta: "El parto o interrupción del embarazo." },
{ pregunta: "¿Qué ocurre si la trabajadora cambia a un puesto compatible?", respuesta: "Se extingue la prestación por riesgo durante el embarazo." },
{ pregunta: "¿Qué organismo gestiona la prestación por riesgo durante el embarazo?", respuesta: "La mutua colaboradora o el INSS." },
{ pregunta: "¿Qué ocurre si la trabajadora pasa de riesgo a IT?", respuesta: "Se extingue la prestación por riesgo y comienza la IT." },

{ pregunta: "¿Qué prestación protege la situación de riesgo durante la lactancia natural?", respuesta: "La prestación por riesgo durante la lactancia natural." },
{ pregunta: "¿Qué base reguladora se usa para riesgo durante la lactancia?", respuesta: "La base reguladora de IT por contingencias profesionales." },
{ pregunta: "¿Qué porcentaje se aplica sobre la base reguladora en riesgo durante la lactancia?", respuesta: "El 100%." },
{ pregunta: "¿Qué causa extingue la prestación por riesgo durante la lactancia cuando el hijo cumple 9 meses?", respuesta: "Extinción automática por edad del menor." },
{ pregunta: "¿Qué causa extingue la prestación por riesgo durante la lactancia si la madre interrumpe la lactancia natural?", respuesta: "Extinción inmediata de la prestación." },
{ pregunta: "¿Qué causa extingue la prestación por riesgo durante la lactancia si se reincorpora al puesto compatible?", respuesta: "Extinción por reincorporación." },
{ pregunta: "¿Qué causa extingue la prestación por riesgo durante la lactancia si se extingue el contrato?", respuesta: "Extinción por fin de la relación laboral." },
{ pregunta: "¿Qué causa extingue la prestación por riesgo durante la lactancia si fallece la beneficiaria?", respuesta: "Extinción automática." },
{ pregunta: "¿Qué ocurre si la trabajadora pasa de lactancia a IT?", respuesta: "Se extingue la prestación por lactancia y comienza la IT." },
{ pregunta: "¿Qué organismo gestiona la prestación por riesgo durante la lactancia?", respuesta: "La mutua colaboradora o el INSS." },
{ pregunta: "¿Cuál es la duración máxima del permiso parental del TREBEP?", respuesta: "8 semanas, continuas o discontinuas, por semanas completas." },
{ pregunta: "¿Hasta qué edad del menor puede usarse el permiso parental del TREBEP?", respuesta: "Hasta que el menor cumpla 8 años." },
{ pregunta: "¿Qué naturaleza tiene el permiso parental del TREBEP?", respuesta: "No retribuido." },
{ pregunta: "¿Puede la Administración aplazar el permiso parental del TREBEP?", respuesta: "Sí, si altera gravemente el funcionamiento del servicio, justificándolo por escrito." },
{ pregunta: "¿Qué derecho garantiza el TREBEP al finalizar el permiso parental?", respuesta: "Reincorporación en términos no menos favorables y acceso a mejoras producidas." },
{ pregunta: "¿Cuántas semanas dura con carácter general el permiso por nacimiento?", respuesta: "16 semanas, de las cuales 6 son obligatorias e ininterrumpidas tras el parto." },
{ pregunta: "¿El permiso por nacimiento es transferible entre progenitores?", respuesta: "No, es un derecho individual e intransferible." },
{ pregunta: "¿Puede iniciarse el permiso por nacimiento antes del parto?", respuesta: "Sí, hasta 4 semanas antes de la fecha prevista del parto." },
{ pregunta: "¿Qué ocurre con el permiso por nacimiento si el recién nacido fallece?", respuesta: "La persona progenitora conserva el derecho íntegro al permiso." },
{ pregunta: "¿Qué ampliación se reconoce en caso de parto múltiple?", respuesta: "1 semana adicional por cada hijo a partir del segundo." },
{ pregunta: "¿Qué ampliación se reconoce si el hijo presenta discapacidad?", respuesta: "1 semana adicional para cada progenitor." },
{ pregunta: "¿Puede disfrutarse el permiso por nacimiento a tiempo parcial?", respuesta: "Sí, si existe acuerdo entre la persona trabajadora y la empresa." },
{ pregunta: "¿Hasta cuándo puede disfrutarse el permiso por nacimiento?", respuesta: "Hasta que el menor cumpla 12 meses." },
{ pregunta: "¿Qué prestación económica corresponde durante el permiso por nacimiento?", respuesta: "El 100% de la base reguladora." },
  { pregunta: "¿Qué ocurre si el parto es prematuro y el neonato requiere hospitalización superior a 7 días?", respuesta: "El permiso se amplía tantos días como dure la hospitalización, con un máximo de 13 semanas adicionales." },
  { pregunta: "¿El permiso por lactancia puede disfrutarse por ambos progenitores?", respuesta: "Sí, es un derecho individual e intransferible." },
  { pregunta: "¿Cuánto dura el permiso por lactancia en su modalidad ordinaria?", respuesta: "Una hora diaria de ausencia hasta que el menor cumpla 9 meses." },
  { pregunta: "¿Puede acumularse el permiso por lactancia en jornadas completas?", respuesta: "Sí, si lo prevé el convenio o se pacta con la empresa." },
  { pregunta: "¿Qué ocurre con el permiso por lactancia en caso de parto múltiple?", respuesta: "Se incrementa proporcionalmente por cada hijo adicional." },
  { pregunta: "¿Qué requisito previo se exige para reconocer el riesgo durante el embarazo?", respuesta: "Un informe del Servicio de Prevención acreditando que no es posible adaptar el puesto." },
  { pregunta: "¿Qué prestación económica corresponde en el riesgo durante el embarazo?", respuesta: "El 100% de la base reguladora." },
  { pregunta: "¿Cuándo finaliza la situación de riesgo durante el embarazo?", respuesta: "Cuando se inicia el permiso por nacimiento." },
  { pregunta: "¿Hasta qué edad del menor puede reconocerse el riesgo durante la lactancia natural?", respuesta: "Hasta que el menor cumpla 9 meses." },
  { pregunta: "¿Qué implica el riesgo durante la lactancia natural?", respuesta: "La suspensión del contrato y una prestación del 100% de la base reguladora." },
  { pregunta: "¿El permiso por nacimiento interrumpe el periodo de prueba?", respuesta: "Sí, el periodo de prueba queda suspendido." },
  { pregunta: "¿Qué ocurre si la empresa se niega a conceder el permiso por nacimiento?", respuesta: "No puede negarse; es un derecho individual e intransferible reconocido por ley." },
  { pregunta: "¿Puede la empresa exigir preaviso para el inicio del permiso por nacimiento?", respuesta: "Sí, pero solo para la parte voluntaria; nunca para las 6 semanas obligatorias." },
  { pregunta: "¿Qué ocurre si el parto se adelanta respecto a la fecha prevista?", respuesta: "El permiso comienza el día real del parto sin afectar al total de semanas." },
  { pregunta: "¿Qué sucede si el parto se retrasa más allá de la fecha prevista?", respuesta: "Las semanas anticipadas ya disfrutadas no se amplían; el cómputo sigue igual." },
  { pregunta: "¿Puede el permiso por nacimiento disfrutarse en periodos no consecutivos?", respuesta: "Sí, siempre en bloques semanales y dentro de los 12 meses del menor." },
  { pregunta: "¿Qué ocurre si durante el permiso por nacimiento la persona trabajadora es despedida?", respuesta: "El despido es nulo automáticamente salvo causa objetiva ajena al permiso." },
  { pregunta: "¿Qué ocurre si la persona trabajadora está en IT cuando da a luz?", respuesta: "La IT se extingue y pasa a permiso por nacimiento." },
  { pregunta: "¿Puede disfrutarse el permiso por nacimiento a jornada parcial sin acuerdo de la empresa?", respuesta: "No, requiere acuerdo expreso entre empresa y persona trabajadora." },
  { pregunta: "¿Qué ocurre si la empresa no responde a la solicitud de disfrute parcial del permiso?", respuesta: "Se entiende denegado; no existe silencio positivo." },
  { pregunta: "¿Qué ocurre si el menor nace con una enfermedad grave que requiere hospitalización prolongada?", respuesta: "Se amplía el permiso tantos días como dure la hospitalización, hasta 13 semanas." },
  { pregunta: "¿Qué ocurre si el menor es adoptado y tiene más de 6 años?", respuesta: "Solo procede permiso si tiene discapacidad o especiales dificultades de inserción." },
  { pregunta: "¿Puede iniciarse el permiso por adopción antes de la resolución judicial?", respuesta: "Sí, en adopción internacional hasta 4 semanas antes." },
  { pregunta: "¿Qué ocurre si la adopción no llega a formalizarse?", respuesta: "El permiso se extingue desde ese momento, sin obligación de devolver prestaciones ya percibidas." },
  { pregunta: "¿Qué ocurre si ambos progenitores trabajan en la misma empresa y solicitan simultáneamente el permiso por nacimiento?", respuesta: "La empresa no puede limitarlo; ambos tienen derecho pleno." },
  { pregunta: "¿Puede la empresa exigir que el permiso por nacimiento se disfrute de forma continuada?", respuesta: "No, la ley permite el disfrute fraccionado en semanas." },
  { pregunta: "¿Qué ocurre si el menor es prematuro y requiere ingreso inmediato?", respuesta: "Las 6 semanas obligatorias pueden diferirse tras el alta hospitalaria." },
  { pregunta: "¿Qué ocurre si el menor nace muerto?", respuesta: "Se mantiene íntegro el derecho al permiso por nacimiento." },
  { pregunta: "¿Qué ocurre si el menor fallece durante el permiso?", respuesta: "El permiso continúa salvo renuncia expresa de la persona trabajadora." },
  { pregunta: "¿Qué ocurre si el menor es entregado en adopción durante el permiso por nacimiento?", respuesta: "El permiso continúa hasta su finalización." },
  { pregunta: "¿Puede el permiso por nacimiento disfrutarse simultáneamente por ambos progenitores?", respuesta: "Sí, salvo las 6 semanas obligatorias que son individuales." },
  { pregunta: "¿Qué ocurre si la empresa modifica unilateralmente la concreción horaria del permiso por lactancia?", respuesta: "La persona trabajadora puede demandar; la concreción le corresponde a ella." },
  { pregunta: "¿Puede la empresa negar la acumulación del permiso por lactancia si el convenio no lo prevé?", respuesta: "Sí, salvo pacto individual; no existe derecho automático a acumular." },
  { pregunta: "¿Qué ocurre si el convenio reconoce la acumulación del permiso por lactancia?", respuesta: "La empresa está obligada a concederla." },
  { pregunta: "¿Puede el permiso por lactancia disfrutarse en teletrabajo?", respuesta: "Sí, no existe limitación legal." },
  { pregunta: "¿Qué ocurre si el menor es alimentado con leche artificial?", respuesta: "El permiso por lactancia sigue existiendo; no exige lactancia natural." },
  { pregunta: "¿Puede el permiso por lactancia disfrutarse por progenitores no gestantes?", respuesta: "Sí, es un derecho individual de ambos." },
  { pregunta: "¿Qué ocurre si el menor es adoptado o acogido?", respuesta: "Se reconoce igualmente el permiso por lactancia." },
  { pregunta: "¿Qué ocurre si el menor tiene discapacidad?", respuesta: "El permiso por lactancia se incrementa proporcionalmente en caso de múltiples hijos, pero no por discapacidad." },
  { pregunta: "¿Qué ocurre si la empresa exige justificar la lactancia natural para el permiso de riesgo?", respuesta: "No puede; basta acreditar que el menor tiene menos de 9 meses." },
  { pregunta: "¿Qué ocurre si el Servicio de Prevención determina que el puesto es compatible con la lactancia?", respuesta: "No procede la suspensión por riesgo." },
  { pregunta: "¿Qué ocurre si la empresa no puede adaptar el puesto para eliminar el riesgo durante el embarazo?", respuesta: "Debe suspenderse el contrato y tramitarse la prestación." },
  { pregunta: "¿Qué ocurre si la empresa ofrece un puesto alternativo compatible y la trabajadora lo rechaza?", respuesta: "No procede la suspensión por riesgo." },
  { pregunta: "¿Qué ocurre si la trabajadora está en riesgo durante el embarazo y la empresa cierra temporalmente?", respuesta: "La prestación continúa mientras dure la suspensión por riesgo." },
  { pregunta: "¿Qué ocurre si el riesgo durante el embarazo coincide con una IT por enfermedad común?", respuesta: "La IT se extingue y pasa a riesgo durante el embarazo." },
  { pregunta: "¿Qué ocurre si la trabajadora está en riesgo durante la lactancia y el menor cumple 9 meses?", respuesta: "Finaliza la suspensión y la prestación." },
  { pregunta: "¿Qué ocurre si el riesgo durante la lactancia coincide con el permiso por nacimiento del otro progenitor?", respuesta: "No afecta; ambos permisos son independientes." },
  { pregunta: "¿Qué ocurre si la empresa no comunica a la Seguridad Social la suspensión por riesgo?", respuesta: "No afecta al derecho; la prestación se reconoce igualmente." },
  { pregunta: "¿Qué ocurre si la trabajadora solicita el riesgo durante el embarazo sin informe del Servicio de Prevención?", respuesta: "No procede; el informe es requisito indispensable." },
  { pregunta: "¿Qué ocurre si el Servicio de Prevención tarda en emitir el informe?", respuesta: "La empresa debe adoptar medidas provisionales de protección." },
  { pregunta: "¿Qué ocurre si la trabajadora está embarazada y realiza trabajo nocturno?", respuesta: "Debe evaluarse el riesgo; si no es compatible, procede adaptación o suspensión." },
  { pregunta: "¿Qué ocurre si la trabajadora está embarazada y realiza turnos rotatorios?", respuesta: "Debe evaluarse el riesgo; si afecta a la salud, procede adaptación o suspensión." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo con exposición a agentes químicos?", respuesta: "Debe suspenderse el contrato si no es posible la adaptación." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo con cargas físicas elevadas?", respuesta: "Debe adaptarse el puesto o suspenderse si no es posible." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo con radiaciones ionizantes?", respuesta: "Debe suspenderse el contrato inmediatamente." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo con riesgo biológico?", respuesta: "Debe evaluarse y, si no es compatible, suspenderse el contrato." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo en cámaras frigoríficas?", respuesta: "Debe evaluarse el riesgo y suspenderse si no es compatible." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo en altura?", respuesta: "Debe suspenderse el contrato por riesgo evidente." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo con manipulación de cargas?", respuesta: "Debe adaptarse el puesto o suspenderse si no es posible." },
    { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo con exposición a temperaturas extremas?", respuesta: "Debe evaluarse el riesgo y, si no es compatible, suspenderse el contrato." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo con vibraciones mecánicas intensas?", respuesta: "Debe suspenderse el contrato si no es posible la adaptación." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo en ambientes con ruido elevado?", respuesta: "Debe evaluarse el riesgo y adoptar medidas de protección o suspensión." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo con riesgo eléctrico?", respuesta: "Debe evaluarse y, si existe riesgo, suspenderse el contrato." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo en espacios confinados?", respuesta: "Debe suspenderse el contrato por riesgo evidente." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo con exposición a agentes cancerígenos?", respuesta: "Debe suspenderse el contrato inmediatamente." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo con exposición a plomo?", respuesta: "Debe suspenderse el contrato por riesgo para el feto." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo con exposición a mercurio?", respuesta: "Debe suspenderse el contrato por riesgo para el desarrollo fetal." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo con exposición a citotóxicos?", respuesta: "Debe suspenderse el contrato si no es posible la adaptación." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo con riesgo de agresiones físicas?", respuesta: "Debe evaluarse el riesgo y suspenderse si no es posible garantizar la seguridad." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo con riesgo de caídas al mismo nivel?", respuesta: "Debe evaluarse y adaptar el puesto; si no es posible, suspenderse." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo con riesgo de caídas en altura?", respuesta: "Debe suspenderse el contrato inmediatamente." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo con manipulación de sustancias inflamables?", respuesta: "Debe evaluarse el riesgo y suspenderse si no es compatible." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo con maquinaria peligrosa?", respuesta: "Debe suspenderse el contrato si no es posible la adaptación." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo con riesgo de atrapamiento?", respuesta: "Debe suspenderse el contrato por riesgo evidente." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo con conducción profesional prolongada?", respuesta: "Debe evaluarse el riesgo y suspenderse si afecta a la salud." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo con posturas forzadas continuadas?", respuesta: "Debe adaptarse el puesto o suspenderse si no es posible." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo con movimientos repetitivos intensos?", respuesta: "Debe evaluarse y suspenderse si existe riesgo para la gestación." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo con largas jornadas de pie?", respuesta: "Debe adaptarse el puesto o suspenderse si no es posible." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo con turnos de más de 8 horas?", respuesta: "Debe evaluarse el riesgo y suspenderse si afecta a la salud." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo nocturno continuado?", respuesta: "Debe evaluarse y, si no es compatible, suspenderse el contrato." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo en solitario en horario nocturno?", respuesta: "Debe evaluarse el riesgo y suspenderse si no se garantiza la seguridad." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo en zonas aisladas?", respuesta: "Debe evaluarse y suspenderse si existe riesgo para la salud." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo con exposición a humo ambiental?", respuesta: "Debe suspenderse el contrato si no es posible eliminar la exposición." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo con exposición a pesticidas?", respuesta: "Debe suspenderse el contrato por riesgo para el feto." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo con exposición a disolventes orgánicos?", respuesta: "Debe suspenderse el contrato si no es posible la adaptación." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo con exposición a anestésicos volátiles?", respuesta: "Debe evaluarse y suspenderse si existe riesgo para la gestación." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo con exposición a gases medicinales?", respuesta: "Debe evaluarse y suspenderse si no es compatible." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo en quirófano?", respuesta: "Debe evaluarse el riesgo y suspenderse si no es posible garantizar la seguridad." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo en laboratorio con agentes biológicos?", respuesta: "Debe suspenderse el contrato si no es posible la adaptación." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo en laboratorio con agentes químicos?", respuesta: "Debe suspenderse el contrato si existe riesgo para la gestación." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo en laboratorio con riesgo de pinchazos accidentales?", respuesta: "Debe evaluarse y suspenderse si no es posible garantizar la seguridad." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo en servicios de emergencia?", respuesta: "Debe evaluarse el riesgo y suspenderse si no es compatible." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo en transporte sanitario?", respuesta: "Debe evaluarse y suspenderse si existe riesgo para la gestación." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo en vigilancia de seguridad?", respuesta: "Debe evaluarse y suspenderse si no se garantiza la seguridad." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo en hostelería con cargas físicas elevadas?", respuesta: "Debe adaptarse el puesto o suspenderse si no es posible." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo en limpieza con productos químicos agresivos?", respuesta: "Debe suspenderse el contrato si no es posible la adaptación." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo en industria alimentaria con cámaras frigoríficas?", respuesta: "Debe evaluarse y suspenderse si no es compatible." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo en agricultura con exposición a fitosanitarios?", respuesta: "Debe suspenderse el contrato por riesgo para el feto." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo en construcción?", respuesta: "Debe suspenderse el contrato por riesgo evidente." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo en minería?", respuesta: "Debe suspenderse el contrato inmediatamente." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo en transporte de mercancías pesadas?", respuesta: "Debe evaluarse y suspenderse si no es compatible." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo en almacenes con manipulación de cargas?", respuesta: "Debe adaptarse el puesto o suspenderse si no es posible." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo en cadenas de producción rápidas?", respuesta: "Debe evaluarse y suspenderse si existe riesgo para la gestación." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo en peluquería con exposición a químicos?", respuesta: "Debe evaluarse y suspenderse si no es compatible." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo en estética con exposición a vapores químicos?", respuesta: "Debe evaluarse y suspenderse si existe riesgo." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo en centros educativos con riesgo biológico?", respuesta: "Debe evaluarse y suspenderse si no es posible garantizar la seguridad." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo en guarderías con riesgo de contagio?", respuesta: "Debe evaluarse y suspenderse si existe riesgo para la gestación." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo en atención al público con riesgo de agresiones?", respuesta: "Debe evaluarse y suspenderse si no se garantiza la seguridad." },
  { pregunta: "¿Qué ocurre si la trabajadora embarazada realiza trabajo en centros penitenciarios?", respuesta: "Debe evaluarse y suspenderse si existe riesgo para la gestación." }
];